### ISSUE TITLE
cg_autoactivate bug

### ISSUE THREAD

**Issue by donizettilorenzo** [iortcw/iortcw#10]
I have cg_autoactivate set to  "0" but it's not working (items are gathered automatically)

**Comment by MAN-AT-ARMS** [comment]
I'm not able to reproduce this behavior. Check your config.

**Comment by donizettilorenzo** [comment]
Here's a video (with cg_autoactivate in console showing its "0") and see the second medkit behaviour: http://www46.zippyshare.com/v/Uw1ceGvR/file.html

**Comment by MAN-AT-ARMS** [comment]
OK...so did you check your config?
I'm not able to reproduce the behavior. Posting a video is not helpful at all.

**Comment by donizettilorenzo** [comment]
Yes, I did check, and I simply can't explain why!

**Comment by MAN-AT-ARMS** [comment]
How about posting your config or a console log or something?

**Comment by MAN-AT-ARMS** [comment]
Closing due to lack of information. Was not able to reproduce this with iortcw game modules.
