### ISSUE TITLE
iortcw 1.51c not starting up on W10

### ISSUE THREAD

**Issue by masi0** [iortcw/iortcw#102]
getting black window with no visible actions and request to copy log to the clipboard:

iortcw 1.51c-SP win_mingw64-x64 Mar 16 2019
SSE instruction set enabled
----- FS_Startup -----
Current search path:
C:\Users\dryba\OneDrive\Documents\RTCW\main
C:\Games\RTWC\main\sp_pak4.pk3 (21 files)
C:\Games\RTWC\main\sp_pak3.pk3 (14 files)
C:\Games\RTWC\main\sp_pak2.pk3 (232 files)
C:\Games\RTWC\main\sp_pak1.pk3 (1342 files)
C:\Games\RTWC\main\pak0.pk3 (4775 files)
C:\Games\RTWC\main
c:/games/steam\SteamApps\common\Return To Castle Wolfenstein\main

----------------------
6384 files in pk3 files
execing default.cfg
execing wolfconfig.cfg
execing autoexec.cfg
Minimum com_hunkMegs is 128, allocating 128 megs.
Hunk_Clear: reset the hunk ok
Bypassing CD checks
----- Client Initialization -----
Couldn't read rtcwhistory.
Cmd_AddCommand: map_restart already defined
----- Initializing Renderer ----
Trying to load "renderer_sp_opengl1_x64.dll" from "C:\Games\RTWC"...
---- Renderer Initialization Complete ----
RTCWKEY found.
----- Client Initialization Complete -----
----- R_Init -----
SDL using driver "windows"
Initializing OpenGL display
Display aspect: 1.600
...setting mode 3: 640 480
Using 24 color bits, 24 depth, 8 stencil display.
Available modes: '320x200 640x400 1280x800 1440x900 1680x1050 1920x1200 1280x768 1360x768 1280x720 1366x768 1600x900 1920x1080 320x240 400x300 512x384 640x480 800x600 1024x768 1152x864 1280x960 1400x1050 1600x1200 1280x1024 1280x600'
GL_RENDERER: GeForce GTX 1650 Ti/PCIe/SSE2
Initializing OpenGL extensions
...using GL_EXT_texture_compression_s3tc
...using GL_EXT_texture_env_add
...using GL_ARB_multitexture
...using GL_EXT_compiled_vertex_array
...ignoring GL_EXT_texture_filter_anisotropic
Initializing Shaders
^3WARNING: In shader file scripts/common.shader...Shader "textures/sfx/portal3a_back2" on line 822 is missing closing brace^3.
^3WARNING: In shader file scripts/ui_wolf.shader...Invalid shader name "}" on line 1849.
----- finished R_Init -----
------ Initializing Sound ------
Trying to load "OpenAL64.dll"...
Allocated 128 sources.
OpenAL default capture device is 'OpenAL Soft on Mikrofon (Thronmax MDrill Zero Plus)'
OpenAL capture device opened.
OpenAL info:
  Vendor:         OpenAL Community
  Version:        1.1 ALSOFT 1.17.2
  Renderer:       OpenAL Soft
  AL Extensions:  AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_BFORMAT AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length
  ALC Extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFTX_device_clock ALC_SOFT_HRTF ALC_SOFT_loopback ALC_SOFT_pause_device
  Device:         OpenAL Soft on Speakers (Realtek(R) Audio)
  Available Devices:
OpenAL Soft on Speakers (Realtek(R) Audio)
  Input Device:   OpenAL Soft on Mikrofon (Thronmax MDrill Zero Plus)
  Available Input Devices:
OpenAL Soft on Mikrofon (Thronmax MDrill Zero Plus)
OpenAL Soft on Microphone (Realtek(R) Audio)
Sound initialization successful.
--------------------------------
----- Client Shutdown (Client fatal crashed: VM_Create on UI failed) -----
RE_Shutdown( 1 )
Hunk_Clear: reset the hunk ok
OpenAL capture device closed.
-----------------------

**Comment by masi0** [comment]
resolved due to follow another article

**Comment by MAN-AT-ARMS** [comment]
Do you have the .dll files in the main folder?
