### ISSUE TITLE
Quicksaving with grenade cooking causes softlock

### ISSUE THREAD

**Issue by krittinen** [iortcw/iortcw#107]
Using version 1.51c

**Problem:**
If you cook a grenade (hold fire button with grenade held) then quicksave and quickload the now live grenade will be stuck in your hand, causing a death as you can't throw it or switch weapons and the damage also goes through godmode.

**Expected behavior:**
The grenade timer stops or the grenade will be thrown as soon as the game loads.

**Steps to reproduce:**

1. Start a new game and use the give all command to get grenades, or load a savefile with grenades.
2. Select grenade, hold the fire button and quicksave while holding it.
3. Load the quicksave.

**Comment by MAN-AT-ARMS** [comment]
It's a feature, not a bug
