### ISSUE TITLE
cg_drawfps missing

### ISSUE THREAD

**Issue by user85475485** [iortcw/iortcw#109]
Coudnt find a command on how to show fps in game.
cg_drawfps 1 dosent work :/

**Comment by MAN-AT-ARMS** [comment]
It's not missing. It works

**Comment by user85475485** [comment]
![grafik](https://user-images.githubusercontent.com/64977518/100820861-77172b80-344f-11eb-9ba7-baeb601ba477.png)
I compiled it from source for me there seems to be no such command

**Comment by wolfetplayer** [comment]
Maybe it's in-game CVAR? Can you try that in-game and not in the menu?

**Comment by user85475485** [comment]
Oh ok im dumb lmao.In game it works fine 
thx for the help tho
