### ISSUE TITLE
Supporting XDG base directory specification

### ISSUE THREAD

**Issue by shmerl** [iortcw/iortcw#11]
I just tried building iortcw from source on Linux (Debian testing), and it works quite well. I only noticed that it uses `$HOME/.iortcw` for storing saves and settings. I patched the game to use `$XDG_DATA_HOME/return-to-castle-wolfenstein` (or `$HOME/.local/share/return-to-castle-wolfenstein` if $XDG_DATA_HOME is undefined). This makes it compliant with XDG base directory spec and stores data neatly without cluttering $HOME.

Are you interested in that patch? It involves changing mostly code/sys/sys_unix.c
Is that something that you regularly pull from upstream, or you can accept patches specific to your codebase in it? I made a merge request here: https://github.com/iortcw/iortcw/pull/12

Let me know if it's OK or needs any adjustments / changes to approach.

**Comment by MAN-AT-ARMS** [comment]
I only use the .iortcw directory for non-release patchsets.
I use the the old default of .wolf for releases where players and admins are more likely to have their existing vanilla logs/configs.

I suspect that many package maintainers may want to include something like this though in their own patchsets. Maybe I'll merge this in a future release.

**Comment by pingrage11** [comment]
Hi MMA,

sorry to track you down on this page but i couldnt find any other way to contact you. Not sure if you know by Jun1or took down the website, so if and when you turn the server on no one will know. 

I'm pleading with you now to Please turn the server back on. Sorry to annoying here on this webpage. 

If you wish to reply email me? at Coskey7 at hotmail dot com

**Comment by MAN-AT-ARMS** [comment]
Merged in 96eb4af (but made optional)
