### ISSUE TITLE
x86 failed to load renderer

### ISSUE THREAD

**Issue by wolfetplayer** [iortcw/iortcw#110]
x86 compiles just fine. When I try to launch it it gives me the "Failed to load renderer" error.
For some reason it fails to find renderer_sp_opengl1_x86.dll, but it's in the folder.
Not sure what is the issue, it was working fine before.
Issue is persist on both realrtcw and iortcw.
Tried to compile on 2 different machines.(win7 and win10)

x64 works fine

**Comment by MAN-AT-ARMS** [comment]
Make sure you have the SDL2.dll file in the folder alongside the .exe and your video card drivers are installed.

**Comment by Batti992** [comment]
Hi,
wonderfull mod! but im habing the same problem as above :/
i got the SDL2.dll in the right place but notthing.
what i do is:
got a woking iortcw package, (which i can play)
try to build with cygwin the x86 project
after that, i bring all filed inside "Build\release-mingw32-x86\" folder into iortcw working folder.
i miss something??
many thankss!

**Comment by Batti992** [comment]
this is the log, if useful
----- Initializing Renderer ----
Trying to load "renderer_sp_opengl1_x86.dll" from "D:\Users\Davide\Desktop\iortcw-1.51c-win-x64"...
Loading "renderer_sp_opengl1_x86.dll" failed
failed:
"Failed loading D:\Users\Davide\Desktop\iortcw-1.51c-win-x64\renderer_sp_opengl1_x86.dll: The specified module could not be found.
"

**Comment by MAN-AT-ARMS** [comment]
The file should be in the same folder as the .exe.

If it is, try adding the following to you commandline to build:
LDFLAGS='-static-libgcc'

eg:
ARCH=x86_64 LDFLAGS='-static-libgcc' make

**Comment by Batti992** [comment]
thanks, i will try ARCH=x86 LDFLAGS='-static-libgcc' make !!
i'm trying to use x86

**Comment by MAN-AT-ARMS** [comment]
OK yes. The files you need will be in the build folder with the exe files. (renderer dll files)

**Comment by Batti992** [comment]
it workeeeddd!!!
but when i start new game i get in yellow window "Couldn't register weapon 1 ()  Failed to parse weapon.cfg

**Comment by Batti992** [comment]
If i put an original cgame_sp_x86.dll on Main folder, the game works
i build the clean git clone, i have not edit anything

But my objective is to mod weapons config (like i would try a mp40 with 300 round on magazine, instead of 32)

**Comment by MAN-AT-ARMS** [comment]
For 32 bit you should copy the vm folder into the Main and not replace the original dll files.

Game modifications is outside the scope of this project.

**Comment by Batti992** [comment]
uhm, 
VM folder is empty in my build folder

anyway, due to the fact i'm building the game, i will not be able to change some code like weapons properties?

**Comment by MAN-AT-ARMS** [comment]
If you're building SP, you're right, the vm folder will be empty. In that case you do want to copy the dll files into the Main folder.

Obviously any changes you make to the code require you copying the modified/built files to your game directory.

**Comment by wolfetplayer** [comment]
> ARCH=x86_64 LDFLAGS='-static-libgcc' make

Thanks man. This helped
