### ISSUE TITLE
Error on RPI3 (with solution): "Couldn't register weapon 1 () (failed to parse weapon.cfg)"

### ISSUE THREAD

**Issue by goph-R** [iortcw/iortcw#113]
Hi!

I successfully compiled the engine on RPI3 (Raspbian OS Buster). I had the error message ("Couldn't register weapon 1 () (failed to parse weapon.cfg)") after I started a new game. I searched for the issue in the code, and I found the problematic part in "SP/code/cgame/cg_weapons.c" beginning at line 1083.

The issue is the line below, because it removes the directory part from the full path:
`COM_StripFilename( item->world_model[W_FP_MODEL], path );`

I removed that line, and wrote this:
`strcpy( path, item->world_model[W_TP_MODEL] );
char* dname = dirname(path);`

..and modified the next if:
`if ( !CG_ParseWeaponConfig( va( "%s/weapon.cfg", dname ), weaponInfo, weaponNum ) ) {`

Now it works for me, or at least I could play the first level.

I don't know is this an issue on other platforms as well, but on RPI3 surely it is.

**Comment by MAN-AT-ARMS** [comment]
You're right. Should be fixed in efc4ecc
