### ISSUE TITLE
issue with the screen stretching / filling (kinda solved)

### ISSUE THREAD

**Issue by Hoxie69** [iortcw/iortcw#118]
the problem is that no matter what i do the screen always appears to be cut from top and a bit from the bottom, as if its not stretching the image across the screen (im playing with a 1600x900 monitor and yes i have my scale at 100% and tried changing the high DPI settings on the EXE) also changing /cg_fixedaspect didn't help, any help would be much appreciated.
![20210228152432_1](https://user-images.githubusercontent.com/25549332/109416745-8ae41680-79d9-11eb-8b54-5806bd74bf0f.jpg)
![20210228151555_1](https://user-images.githubusercontent.com/25549332/109416749-8f103400-79d9-11eb-8e00-06f845d47eea.jpg)

**Comment by Hoxie69** [comment]
i seem to have fixed the issue by changing r_customheight and r_customweidth to my resolution but changing the resolution to it from the settings will cause the same issue, i still have a problem with the weapons FOV / placement though, it doesn't seem to fit the original, it's more sunken down the screen

**Comment by MAN-AT-ARMS** [comment]
To use r_customheight and r_customwidth you need to set r_mode to -1

r_mode -2 auto detects uses the resolution of your desktop

r_fullscreen 1 is to use not use window borders
