### ISSUE TITLE
Framerate issue ?

### ISSUE THREAD

**Issue by Segasensei** [iortcw/iortcw#119]
While using high quality graphics, I noticed the FPS are a bit tanky. 

I tried using the "cl_renderer opengl1;vid_restart" but it didn't change anything, not even the renderer.

I have :
AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx, 2300Mhz
Windows 10
GeForce RTX 2060

Also a weird thing : I did not install the game in the original RTCW steam folder, I just made another folder with the necessary game data files. I have zero config folder for iortcw and don't know where to change it. I am a total newbie concernig game modification shenanigans I have to say.

**Comment by MAN-AT-ARMS** [comment]
Do you know which cvar it was?

**Comment by Segasensei** [comment]
Sorry for the late reply, it was : \r_forcesun 0
