### ISSUE TITLE
CG_LoseArmor is not working

### ISSUE THREAD

**Issue by wolfetplayer** [iortcw/iortcw#124]
I just copied this chunk of code from vanilla code.
Now proper armor chunks are dropping from damaging protos and uber soldat.
Here's the fix:
https://github.com/wolfetplayer/RealRTCW/commit/2fe22c5a84c5a18efc90d024a34f8c2a582ca0c8

**Comment by MAN-AT-ARMS** [comment]
I'll have to check. I don't recall why I removed all that from the vanilla source. Probably was unused or something. I'll check it

**Comment by MAN-AT-ARMS** [comment]
Should be fixed in ec05613
