### ISSUE TITLE
FPS cap works weird

### ISSUE THREAD

**Issue by Kappa971** [iortcw/iortcw#125]
Hi, I think the command seta com_maxfps "XXX" doesn't work correctly.
What happens is:
1. Only the values 76 and 125 are "recognized" correctly. For example by entering 95, the fps are locked at 100 while by entering 120, they are locked at 125 (this also happens in the original game, without iortcw)
2. I have a 144hz freesync monitor and strangely the game runs smoothly only with seta com_maxfps "125". For example, if you enter 76 or 144, the mouselook isn't smooth

**Comment by quake1982** [comment]
This is a minor bug in the Q3 engine. Higher fps usually leads to unstable rendering issues, which may trigger graphic glitches. If you want fps of more than 125, you need to input g_cynchronousclients 1. Also, the command cl_aviframerate value needs to be equal to the value of the com_maxfps.
PS: g_cynchronousclients only works when you are in the gameplay, which means it does't work under the menu.

**Comment by quake1982** [comment]
> This is a minor bug in the Q3 engine. Higher fps usually leads to unstable rendering issues, which may trigger graphic glitches. If you want fps of more than 125, you need to input g_cynchronousclients 1. Also, the command cl_aviframerate value needs to be equal to the value of the com_maxfps.
> PS: g_cynchronousclients only works when you are in the gameplay, which means it does't work under the menu.

sorry wrong spelling, it should be g_synchronousclients.

**Comment by Kappa971** [comment]
Thanks for the reply. Reading the iortcw "README" file, the command "cl_aviframerate" affects the frames for capturing the video, so it is not linked to com_maxfps (unless it captures a video). I still tried to set it from 25 to 144 but it doesn't change anything. The command "g_synchronousclients" is not recognized by the console so I couldn't test it. Anyway I will continue to play at 125 fps as it is smoother than 144 fps (very strange but it is), at least as long as this "bug" is present.

**Comment by quake1982** [comment]
> Thanks for the reply. Reading the iortcw "README" file, the command "cl_aviframerate" affects the frames for capturing the video, so it is not linked to com_maxfps (unless it captures a video). I still tried to set it from 25 to 144 but it doesn't change anything. The command "g_synchronousclients" is not recognized by the console so I couldn't test it. Anyway I will continue to play at 125 fps as it is smoother than 144 fps (very strange but it is), at least as long as this "bug" is present.

Hi there:
please check the spelling, make sure that is /g_synchronousclients 1
Also, as I mentioned you need to input this command when you start the gameplay, which means you have to type this command in SP or MP mode. If you type this under the game menu, it can not be recognised by the console.

**Comment by quake1982** [comment]
![image](https://user-images.githubusercontent.com/77327148/127321790-03f1e5d8-cb46-43d6-82dc-aa9838f66b32.png)

**Comment by Kappa971** [comment]
> Hi there:
please check the spelling, make sure that is /g_synchronousclients 1
Also, as I mentioned you need to input this command when you start the gameplay, which means you have to type this command when you have already been in SP or MP mode. If you type this under the game menu, it can not be recognised by the console.

Sorry I did not understand. Now I started the game, I entered the command / g_synchronousclients 1 (the console recognized it this time) but unfortunately nothing has changed. Even so, 125 fps is smoother than 144. It means that I will have to settle for 125 fps :) It is not the first source port to have problems with freesync monitors, probably the developers do not have them so they cannot test the software they develop (on the other hand they do it for free). Thanks for everything

**Comment by quake1982** [comment]
> > Hi there:
> > please check the spelling, make sure that is /g_synchronousclients 1
> > Also, as I mentioned you need to input this command when you start the gameplay, which means you have to type this command when you have already been in SP or MP mode. If you type this under the game menu, it can not be recognised by the console.
> 
> Sorry I didn't understand. Now I started the game, I entered the command /g_synchronousclients 1 (the console recognized it this time) but unfortunately nothing has changed. Even so, 125 fps is smoother than 144. It means that I will have to settle for 125 fps :) It isn't the first source port to have problems with freesync monitors, probably the developers don't have them so they cannot test the software they develop (on the other hand they do it for free). Thanks for everything

Which renderer do you use? I didn't test cl_renderer opengl2. The method that I provided is based on cl_renderer opengl1, the default.
Besides, I also have a freesync monitor with AMD Radeon 7, and I have enabled the Adaptive Sync Compatible in the panel. Meanwhile, I have set com_maxfps 1000. The game is perfectly running on my computer.
Basically, please follow these procedures:
1, double-click ioWolfSP.x64 in the folder;
2, under the game menu, open the console and type /com_maxfps 1000;
3, click "play" to enter in the SP story, or load your previous saved games;
4, open the console again, and type /g_synchronousclients 1.
Before you start the game, please check your monitor refresh rate is under 144 Hz or more (if higher refresh rate is available).
Some other parameters may help you to stabilise the game:
please make sure that you turn on the OpenGL Triple Buffering in the driver (control panel) of your video card. 
Again, when you start the game, check the following console commands below:
/r_lodbias -10
/r_lodcurveerror 10000
/r_stencilbits 8
/r_subdivisions 1
/r_flares 1
/vid_restart   ---- restart the game
I sincerely hope these methods can help you. Good luck.    : )

**Comment by Kappa971** [comment]
> Which renderer do you use? I didn't test cl_renderer opengl2. The method that I provided is based on cl_renderer opengl1, the default.
Besides, I also have a freesync monitor with AMD Radeon 7, and I have enabled the Adaptive Sync Compatible in the panel. Meanwhile, I have set com_maxfps 1000. The game is perfectly running on my computer.
Basically, please follow these procedures:
1, double-click ioWolfSP.x64 in the folder;
2, under the game menu, open the console and type /com_maxfps 1000;
3, click "play" to enter in the SP story, or load your previous saved games;
4, open the console again, and type /g_synchronousclients 1.
Before you start the game, please check your monitor refresh rate is under 144 Hz or more (if higher refresh rate is available).
Some other parameters may help you to stabilise the game:
please make sure that you turn on the OpenGL Triple Buffering in the driver (control panel) of your video card.
Again, when you start the game, check the following console commands below:
/r_lodbias -10
/r_lodcurveerror 10000
/r_stencilbits 8
/r_subdivisions 1
/r_flares 1
/com_hunkmegs 1024
/vid_restart ---- restart the game
I sincerely hope these methods can help you. Good luck. : )

I entered all the commands but nothing changes. I want to specify that the game runs at 144fps but moving the view with the mouse, it isn't 100% smooth, there is a feeling of "flickering" of the view, as if the game couldn't synchronize perfectly with the monitor. I have a 144 hz LG 27GL650F monitor and a GTX 1060 6GB, Freesync (or G-Sync compatible) and V-Sync are active in the Nvidia control panel (I haven't activated Triple Buffering because they don't recommend it with these types of monitors) and it works in all games, even in this one as if I set com_maxfps 125, the monitor indicates 125hz. Playing at 125 fps, the game feels perfectly smooth, it's really weird. I use cl_renderer opengl1 as the performance is much better than the new render. Maybe it depends on the game, maybe it depends on Nvidia's freesync implementation, maybe the type of monitor that doesn't get along with this game (and some other source ports too) ... Anyway thanks for the helpfulness and patience :)

**Comment by MAN-AT-ARMS** [comment]
The Q3 engine uses values for FPS that divide equally into 1000, with certain framerates giving better jump height, distance, etc.
Same goes for cl_maxpackets...use a number divisible by the FPS (up to 125)

**Comment by Kappa971** [comment]
So, if I understand correctly, it is not recommended to exceed 125 fps as it would change some behavior of the game?
