### ISSUE TITLE
 3D positional audio engine distant sounds accuracy

### ISSUE THREAD

**Issue by jan-kleks** [iortcw/iortcw#134]
Hello,

I have recently watched a video demonstrating iortcw HRTF on a channel which specializes in showing many 3D positional audio engines: https://www.youtube.com/watch?v=iDwbo-ecJQw They wrote this about iortcw's implementation: "iortcw seems to use a variant of ioquake3's 3D positional audio engine. It feels like distant sounds are a bit less accurate than ioquake3, but in return it has vertical HRTF."

Do you think that this distant sounds accuracy could be improved? Or the creator of the video is just being picky?

Regards

**Comment by MAN-AT-ARMS** [comment]
There are very slight differences related to distance...specifically rolloff distance for reasons of hearing spoken dialog, scripted events, etc. that you are not near. Quake3 has no such events to consider. RTCW also has some sound type prioritization that Q3 doesn't.
I think it's probably being picky. I just tried to keep the sound as close to the vanilla game despite being on a different sound engine.
