### ISSUE TITLE
NetBSD build issue

### ISSUE THREAD

**Issue by Adrien2002** [iortcw/iortcw#14]
The whole build is full of the same error :
make: "/home/Adrien2002/iortcw-1.42d/SP/Makefile" line 2849: Missing dependency operator
make: "/home/Adrien2002/iortcw-1.42d/SP/Makefile" line 2851: Need an operator

I just download the sources, entered in SP folder and wrote "make" as described in the README. Maybe the NetBSD part in the Makefile is not compatible anymore with how NetBSD is nowadays, I'm not an expert at all about it. If we success to build it, I'll port it to pkgsrc.

**Comment by MAN-AT-ARMS** [comment]
Try using gmake (instead of make)
Thats what I use on FreeBSD...havent personally tried a NetBSD build

**Comment by Adrien2002** [comment]
It worked perfectly.

Now, I have this : http://pastebin.com/LDXPeFje

There isn't any client to run, only some libs

**Comment by MAN-AT-ARMS** [comment]
Open Makefile with your favorite text editor.
In the NetBSD section remove the line that says BUILD_CLIENT = 0

Let me know your result. Like I said, it is untested.

**Comment by Adrien2002** [comment]
gmake error because of a file not found
http://pastebin.com/Uj3yzvxW

**Comment by Adrien2002** [comment]
I don't know if it is important but it seems that the build is looking for SDL.h in the wrong folder : 
code/client/../sys/sys_loadlib.h:39:19: fatal error: SDL.h: No such file or directory
The file is in code/SDL2/include/SDL.h
I don't know if it is the correct file, how to fix that ?

**Comment by MAN-AT-ARMS** [comment]
You need SDL2 and its associated development files on your system. (as well as a working implementation of opengl)

libsdl.org

Im not sure of the status of opengl on netbsd.

Both would be system requirements for a working client.

**Comment by Adrien2002** [comment]
Here is what I can install from pkgsrc
http://pkgsrc.se/search.php?so=sdl2

I have devel/SDL2 actually installed, should I install another package with it ?

**Comment by MAN-AT-ARMS** [comment]
Maybe Mesa and pkgconfig?

Im not super familiar with that OS...not sure.

You migh have to manually set the SDL include / lib directories. Or you can try copying the settings from one of the other BSDs to the NetBSD section of Makefile.

**Comment by Adrien2002** [comment]
Games are working well with NetBSD : Minecraft, DosBOX games, redeclipse etc... Some games like that.

I know that the packages are not in "/" but in "/usr/pkg" (if I delete /usr/pkg, I delete all my softwares)
I will try and see :)
Thank you very much for your help, I will come back with new informations about that build

**Comment by Adrien2002** [comment]
I come back with new informations.

So I changed some SDL lines to point in the correct folder but now, I'm stuck on this part :
http://pastebin.com/GzwrbNM2

It is building the client but stops on this error.
Am I doing something wrong ?

Here is the 2175 line

   2172 
   2173 ifneq ($(USE_RENDERER_DLOPEN),0)
   2174 $(B)/$(CLIENTBIN)$(FULLBINEXT): $(Q3OBJ) $(LIBSDLMAIN)
   2175         $(echo_cmd) "LD $@"
   2176         $(Q)$(CXX) $(CLIENT_CFLAGS) $(CFLAGS) $(CLIENT_LDFLAGS) $(LDFLAGS) \
   2177                 -o $@ $(Q3OBJ) \
   2178                 $(LIBSDLMAIN) $(CLIENT_LIBS) $(LIBS)

**Comment by Adrien2002** [comment]
I'm back.

So, I disabled Mumble in the Makefile to skip this error and added path to SDL, it builds pretty far but stopped at sdl_input.c without any understandable error for me
Here is what I have :
http://pastebin.com/WGwgCCc9

**Comment by zturtleman** [comment]
The sdl_input.c errors look like you pointed it to SDL 1.2 header file but it needs SDL 2.

**Comment by MAN-AT-ARMS** [comment]
I've been working on this a little in VirtualBox. I will probably commit some needed changes later.
The libGL isn't found and the one in /usr/X11R7/lib doesn't seem to work either.

I did need to install pkg-config and Mesa though as I mentioned earlier.

BTW...This OS is garbage.

**Comment by Adrien2002** [comment]
Exactly zturtleman, it worked. I am now continuing the build process, fixing path

**Comment by MAN-AT-ARMS** [comment]
I didn't have to change any paths and I have it fully compiling but the GL extensions are undefined.

**Comment by Adrien2002** [comment]
On NetBSD ?

**Comment by MAN-AT-ARMS** [comment]
yeah

**Comment by Adrien2002** [comment]
My NetBSD is one year old, maybe some things have changed since then... I think I will give it a try in a VM.

**Comment by Adrien2002** [comment]
But, you used pkg_add right ? I don't know if packages go in the same place as pkgsrc. Your SDL was in /usr/pkg ?

**Comment by MAN-AT-ARMS** [comment]
I think you just need to install pkg-config for the paths

**Comment by Adrien2002** [comment]
I already have pkg-config

**Comment by Adrien2002** [comment]
Why you say this OS is garbage ?

**Comment by MAN-AT-ARMS** [comment]
Try this build...

http://64.237.36.250/iortcw/iowolfsp-git-netbsd-test.zip

I had to copy the libGL.* files from /usr/X11R7/lib to /usr/pkg/lib for libGL to link. Not sure if you will have to do the same or not.

**Comment by Adrien2002** [comment]
It perfectly runs with your binary :)
I just reinstalled NetBSD and changed some mistakes I made.
For libs, just have to export the LD_LIBRARY_PATH variable to /usr/X11R7/lib (a little script and it's good)
I will also try to build it by myself with this new installed NetBSD.
Thank you very much for your patience and NO, it is not garbage, it is different :p

**Comment by Adrien2002** [comment]
I have "spies" all around the level and the crosshair is weird for now. I might be missing something
http://image.noelshack.com/fichiers/2016/22/1464809025-2016-06-01-212219-1920x1080-scrot.png

**Comment by Adrien2002** [comment]
It is "GL Extensions", everything is normal when disabling it

**Comment by Adrien2002** [comment]
That's strange, I still have to manually set the SDL path even having pkg-config installed. What do we have different ?

**Comment by MAN-AT-ARMS** [comment]
Not sure but I will commit my changes when I get a chance.

**Comment by Adrien2002** [comment]
You did some changes ?
Do I close this topic ?

**Comment by MAN-AT-ARMS** [comment]
Ill close it after I commit the changes and you can verify a good build

**Comment by MAN-AT-ARMS** [comment]
I have committed my changes. Please clone a fresh copy of the repository and try building again. Let me know your results.

**Comment by Adrien2002** [comment]
I had to change a line :

RENDERER_LIBS = $(SDL_LIBS) -lGL
RENDERER_LIBS = /usr/X11R7/lib/libGL.so.2.0

And before you think NetBSD is garbage, let me explain you WHY.

1. We can decide to install xorg from ISO in NetBSD
If so, all xorg sets will go in /usr/X11R7
Why ? Simply because it is not a pkg from pkgsrc so we had to put it in the system itself to don't mix it with pkgsrc softwares.

2. We can decide to use meta-pkgs/xorg-modular from pkgsrc
If so, xorg will be installed inside /usr/pkg as any other software from pkgsrc.

Except for this, it is perfect :-) thank you very much for helping us MAN-AT-ARMS. Even you don't like NetBSD that much, they all thank you.

**Comment by MAN-AT-ARMS** [comment]
2. sounds like a good option or maybe even just installing symlinks or something.

The "garbage" comment was a joke...

NetBSD seems to be fine if you want something minimal. It could certainly use some help in the hardware support and software/package/dependency management department though.

**Comment by Adrien2002** [comment]
Will you also make the changes in RTCWCoop ? Can we use the same Makefile ?

**Comment by MAN-AT-ARMS** [comment]
It will eventually end up in RTCWCoop repository once I merge the iortcw updates. Obviously, you can manually make those changes to the Makefile if you don't want to wait for that.

**Comment by Adrien2002** [comment]
I already tried and, yes, it works if I apply the same changes as you did for ioRTCW so now I have them both

**Comment by MAN-AT-ARMS** [comment]
I will probably sync up after I put out next iortcw release 1.42e. It probably won't be too long after that provided there are no major issues with merge. There are a few other Coop related fixes that need to go in before next release of that though.
