### ISSUE TITLE
Hard to kill

### ISSUE THREAD

**Issue by amc777** [iortcw/iortcw#142]
Hi I've followed all the instructions to make RTCW work on Win10 and it works brilliantly , thank you!  The only difference I've noticed compared to the original, however, is that it seems unfeasibly difficult to kill enemies now for some reason? Even if I put the game on the easiest setting, I need to unload a full machine gun clip at very close range to knock someone down. Seems odd, but does seem like an affect of the patch. Any ideas?

**Comment by wolfetplayer** [comment]
Iortcw does not affect AI balance in any way.

**Comment by MAN-AT-ARMS** [comment]
There were no changes of this type made...
What files are present in your 'main' folder?
