### ISSUE TITLE
Broken deathcam angles

### ISSUE THREAD

**Issue by wolfetplayer** [iortcw/iortcw#143]
Angles on deathcam are broken.

Try to use /kill in vanilla and in iortcw to see what I mean.

For some reason iortcw uses thirdperson angles for deathcam even in firstperson.

It's probably something connected to "player_die" or "LookAtKiller". But I failed to fix it in RealRTCW so far. 

Should be something else.

**Comment by wolfetplayer** [comment]
Found the problem. Need to revert this commit in order to fix deathcam.
https://github.com/iortcw/iortcw/commit/9cf3f734c1ced4c4932563e6aca8790e9aa89409

**Comment by MAN-AT-ARMS** [comment]
Revert this commit? There isn't been any changes made here from vanilla

**Comment by wolfetplayer** [comment]
Look at the SP part again. Its different in iortcw,I checked the vanilla code.

**Comment by MAN-AT-ARMS** [comment]
Got it...Done
