### ISSUE TITLE
Current commit - MP/code/cgame/cg_draw.c compile issue

### ISSUE THREAD

**Issue by CrimsonKnight13** [iortcw/iortcw#15]
https://github.com/iortcw/iortcw/blob/master/MP/code/cgame/cg_draw.c

https://github.com/iortcw/iortcw/commit/ab6ca55a0d167d1140dc2f404f119bf7cbe2de4a#diff-4786a6184d5e18fe119c9917c381718eR3517

Line 3517 has a colon (:) instead of a semicolon (;)

Change/Revert
```javascript
CG_FillRect( 0, 0, 640, 480, color ):
```
to
```javascript
CG_FillRect( 0, 0, 640, 480, color );
```

This allows it to compile correctly. I was able to compile the game w/o any issues before the current commit as well.

**Comment by MAN-AT-ARMS** [comment]
Thank you!

**Comment by CrimsonKnight13** [comment]
Glad to help!

**Comment by CrimsonKnight13** [comment]
It compiles correctly. Thanks!
