### ISSUE TITLE
wolfanim.script error line 10

### ISSUE THREAD

**Issue by dipol0** [iortcw/iortcw#150]
OS Ubuntu 20.04
Try iortcw 1.42b and iortcw-1.51c

Then start new game get script error:
![Return To Castle Wolfenstein_001](https://user-images.githubusercontent.com/32021806/170345258-90022712-668d-4ebe-b0f8-0de06ff7844f.png)

**Comment by MAN-AT-ARMS** [comment]
Wrong repository...
https://github.com/wolfetplayer/RealRTCW
