### ISSUE TITLE
Provide sp_pak4.pk3 seperately

### ISSUE THREAD

**Issue by MarBg92** [iortcw/iortcw#152]
`sp_pak4.pk3` is specific to iortcw, so it should be packed within the iortcw package itself (like `mp_bin0.pk3`, `sp_rend2_shaders0.pk3` and `mp_rend2_shaders0.pk3`), rather than `patch-data-141.zip` (which contains the patch data for version 1.41).

This was already the case in the past for iortcw 1.42b release.

It confused me that, however I had patched the retail version to 1.41, iortcw said it's missing `sp_pak4.pk3`.

**Comment by MAN-AT-ARMS** [comment]
sp_pak4 is an official pk3. It was on the Game of the Year CD-ROM but was mistakenly not included in any of the upgrade patches.
