### ISSUE TITLE
On a Map restart memory belonging to the old UNLOADED qagame shared library is accessed - causing a crash on some systems.

### ISSUE THREAD

**Issue by emileb** [iortcw/iortcw#154]
When a map is restarted (E.G when you die)  the engine tries to read some memory which is belonging the old qagame.so shared library which has just been unloaded (and reloaded)

Clearly on PC this does not causes on a issue, but on some systems the act to unloading the library will also invalidate (and unmap) the memory of that library, and reloading the libraries allocated new memory.

The memory is in g_main.c:
gentity_t g_entities[MAX_GENTITIES];

..and a pointer to it ends up saved in svs.clients[x].gentity

I have done a fix here but I do not know if this has other implications or if there is a better fix.

https://github.com/emileb/iortcw/commit/a161754e3de388536bc3989f412a98278c87dcfa

May be other instances of this elsewhere?

**Comment by emileb** [comment]
Had a another crash sometimes when loading a game, I think the same issue occurs in cg_main.c:

Probably with centity_t cg_entities[MAX_GENTITIES];

**Comment by wolfetplayer** [comment]
Interesting, was it signal 11 crash?

**Comment by emileb** [comment]
Yes it caused a segfault. When debugging the debugger could not read the memory at that pointer in svs

**Comment by wolfetplayer** [comment]
Im asking because some players experiencing signal 11 crashes in RealRTCW(based on io). I will deploy your fix on experimental branch and see how it goes.

**Comment by emileb** [comment]
Ah you're the realrtcw dev, cool! Yeah maybe the same issue I'm not sure, I've played the game with that fix a bit and it fixed this particular issue for me and didn't *seem* to break anything else. Would be interesting to see if it helps.

**Comment by emileb** [comment]
Another issue with cgame using memory from the server after it has been unloaded:

trap_GetModelInfo gets memory from the server (G_Alloc), but after a load of the game, depending on exact state of the animations, an Entity will try to access memory from the old modelinfo which has JSUT been unloaded from memory.
G_Alloc takes memory from 'static char memoryPool[POOLSIZE];' which belongs to the shared library.

Anyway this fixes it for me:
https://github.com/emileb/iortcw/commit/8321584a52babb03cf75e1021308cf31c45fca10

In I think the only negative effect of this is the comment below that fix from 'zturtleman'

**Comment by emileb** [comment]
To add to this, I think the reason this is a problem is because the the 'maprestart' command does not get run immediately by cgame after the server has restarted the map, due to interpolation a few frames are run before the the next server game tick.

**Comment by tarasis** [comment]
I am getting a crash on map restart on macOS (13 beta 6) on an M1 MacBook Air. Will try and grab a crash log next time it happens.

I am running a build from MacSource Ports iortcw_20211223

**Comment by emileb** [comment]
> I am getting a crash on map restart on macOS (13 beta 6) on an M1 MacBook Air. Will try and grab a crash log next time it happens.
> 
> I am running a build from MacSource Ports iortcw_20211223

Can you rebuild from this source?

**Comment by tarasis** [comment]
> Can you rebuild from this source?

Yes, same issue. After dying the app begins beach balling (hanging) and I have to force quit it. (I have applied patch 1.4.1, but just trying to play single player)

Attached is the log after I force-quit

[iortcw.txt](https://github.com/iortcw/iortcw/files/9437835/iortcw.txt)

Can do further tests if you would like

**Comment by emileb** [comment]
Ok great, in the top comment here i link to a fix I did, it could be the same issue, could try copy copying the change I did to your source and try again.
Seems like it could be the same problem it's definitely a problem on ARM on Android.

**Comment by tarasis** [comment]
@emileb your change / fix works for the macOS client. I deliberately died 5 times and each time restarted perfectly.

**Comment by emileb** [comment]
> @emileb your change / fix works for the macOS client. I deliberately died 5 times and each time restarted perfectly.

Ah good news! You'll also want this change otherwise it will randomly crash sometimes when you load a game: https://github.com/emileb/iortcw/commit/8321584a52babb03cf75e1021308cf31c45fca10

**Comment by tarasis** [comment]
> > @emileb your change / fix works for the macOS client. I deliberately died 5 times and each time restarted perfectly.
> 
> Ah good news! You'll also want this change otherwise it will randomly crash sometimes when you load a game: [emileb@8321584](https://github.com/emileb/iortcw/commit/8321584a52babb03cf75e1021308cf31c45fca10)

Thank you, I assume the ifdef would need to be extended from just __ANDROID__ to Android and something else like __MACOSX__ ?

**Comment by emileb** [comment]
> > > @emileb your change / fix works for the macOS client. I deliberately died 5 times and each time restarted perfectly.
> > 
> > 
> > Ah good news! You'll also want this change otherwise it will randomly crash sometimes when you load a game: [emileb@8321584](https://github.com/emileb/iortcw/commit/8321584a52babb03cf75e1021308cf31c45fca10)
> 
> Thank you, I assume the ifdef would need to be extended from just `__ANDROID__` to Android and something else like `__MACOSX__` ?

Oh yeah or just change to __ANDROID__ to '1' or delete the other code

**Comment by ram-on** [comment]
I also had the same issue on macOS x86_64 - i.e. iortcw crashed after I die and when it tries to automatically load a map, as described by @tarasis.  @emileb your patch solved my issue.  Did you submit a pull request by any change?

**Comment by emileb** [comment]
> I also had the same issue on macOS x86_64 - i.e. iortcw crashed after I die and when it tries to automatically load a map, as described by @tarasis. @emileb your patch solved my issue. Did you submit a pull request by any change?

I have not done a PR, wasn't sure if there were any negative effects of the fix, also not tested on Windows. I think it's good to go though.

**Comment by ram-on** [comment]
@emileb I've tested this on macOS (single player) and the crash when loading the map (after dying) got resolved.  Did not note any unwanted side effects.  Perhaps you want to submit the pull request?
