### ISSUE TITLE
Implementation for Wolfenstein: Enemy Territory?

### ISSUE THREAD

**Issue by Zaithe** [iortcw/iortcw#159]
Hello, i was wondering if its possible this could be implemented into Enemy Territory perhaps to the [ET: Legacy project](https://www.etlegacy.com/) which seeks to modernize the base game? From what i hear the engine and code are nearly identical to RTCW. Thanks in advance!

**Comment by wolfetplayer** [comment]
ETL and io are two very different codebases. What is the point of merging them anyway?

**Comment by Zaithe** [comment]
> 

To merge with ET: Legacy mod which seeks to improve the game also the raytracing mod for RTCW uses iortcw which i hope can be brought over to ET. I'm in talks with the developer for it to bring it over to ET as well since it has an almost identical engine.

**Comment by wolfetplayer** [comment]
Despite similarities - those are two different codebases. Besides both iortcw and etl are achieving the same thing. There is like 0 point in this merge.
