### ISSUE TITLE
Chair swing animation missing

### ISSUE THREAD

**Issue by maximus105** [iortcw/iortcw#166]
In the original RTCW, if you hold a chair in your hand, you can hit enemies with it. In ioRTCW, the chair does not hit when the button is pressed (only the sound of the chair swinging is heard, there is no animation of the chair swinging). This bug appeared in ioRTCW after commit 069725d "All: Fix listen server sending snapshots each client frame" from Sep 19, 2017. After reverting this commit, the chair swing animation works fine.

**Comment by MAN-AT-ARMS** [comment]
Reverted in ecf3359b84d2989e35ab52abd6c56f12c31ec50f
