### ISSUE TITLE
ioWolfSP.x64 crashes after cutscene19

### ISSUE THREAD

**Issue by maximus105** [iortcw/iortcw#169]
After the last cutscene (cutscene19) with Blazkowicz, the main menu does not appear and the game crashes to the Windows 10 desktop. This error only occurs on ioWolfSP.x64. Everything works fine in ioWolfSP.x86. To reproduce this bug, launch ioWolfSP.x64, type \spdevmap cutscene19 in the console and wait for the cutscene to end. After Blazkowicz appears and destroys the wall, the game crashes to the Windows 10 desktop.

**Comment by MAN-AT-ARMS** [comment]
https://github.com/iortcw/iortcw/issues/149
