### ISSUE TITLE
[Warning] Knightmare's 1.42d

### ISSUE THREAD

**Issue by SilentMRG** [iortcw/iortcw#171]
Hello everybody!

Surely most are aware of this patch, but for those who are not here it is: http://www.markshan.com/knightmare/downloads.htm

The patch aims to fix the single player mode, and it works perfectly with iortcw. =) And I didn't need to install "patch-data-141.zip." Finally, instead of running "ioWolfSP.exe", run "WolfSP.exe" that comes with the patch.

Cheers!

**Comment by Mateos81** [comment]
You know that KM is far behind ioRtCW in terms of fixes, especially security-wise, no longer maintained, that all its fixes are already in ioRtCW for ages, and that most mods are based on ioRtCW nowadays?

**Comment by SilentMRG** [comment]
Honestly I didn't know because I discovered ioRTCW these days. Weirdly, ioRTCW runs weird on my PC with "dynamic shadows" that don't exist in the vanilla version and RealRTCW. The patch mentioned above "fixed" these weird "dynamic shadows". Is there a way to disable them in ioRTCW?

**Comment by SilentMRG** [comment]
I'm thinking here that the "dynamic shadows" must be the fault of "patch-data-141.zip". The files I have here from RTCW are the files from the GOG release, which is probably patched, and when I applied the 1.41 patch, it must have broken something in the game, so I'm going to test ioRTCW without the 1.41 patch and with just the GOG "sp and mp" files.

Just for the record the GOG version comes with the "sp_pak4.pk3" file. And the 1.41 patch simply replaced that file with another version.

**Comment by MAN-AT-ARMS** [comment]
The sp_pak4.pk3 file included with Knightmare is not an official pk3. The one in patch-data-141 is.
Knightmare unfortunately named his file the same as an official file.

**Comment by SilentMRG** [comment]
I have all the sp and mp pk3 files taken from the GOG version. Even with these files is it necessary to apply patch 1.41 on ioRtcw? I have this cruel doubt!

Thanks in advance!

**Comment by MAN-AT-ARMS** [comment]
iortcw wouldn't run without all of the correct pk3's being preset. GOG does have the correct version of sp_pak4.pk3

**Comment by MAN-AT-ARMS** [comment]
If you have the graphics set to High Quality in the options it is probably using the new renderer. I think that's what you might be referring to "dynamic shadows." If you don't want to use the new renderer (which has higher system requirements) open console and do /cl_renderer opengl1;vid_restart

**Comment by SilentMRG** [comment]
Exactly my man! That's what I meant. I already solved the problem consulting this issue: https://github.com/iortcw/iortcw/issues/64

But I couldn't write to the console, when I opened it, and tried to type anything, it (console) immediately closed, so I created an "autoexec" file and threw it in the "Main" directory with the cl_renderer opengl1 command inside. Can you tell me if this same command works in RealRTCW? It runs pretty well on my PC but the loading screens are extremely slow.

Thank you for your attention and I apologize for my amateurism and lack of knowledge about the whole project.

And send a hug to He-Man on my behalf. =D

**Comment by MAN-AT-ARMS** [comment]
RealRTCW uses iortcw as it's base so it should be similar to setup. The graphics options may be different though for the various quality settings.

**Comment by Mateos81** [comment]
From the top of my head, Venom Mod, which is also based on ioRtCW IIRC

**Comment by SilentMRG** [comment]
> From the top of my head, Venom Mod, which is also based on ioRtCW IIRC

Hey man, these are cool mods...

https://www.moddb.com/games/return-to-castle-wolfenstein/addons/rw

https://www.moddb.com/games/return-to-castle-wolfenstein/addons/swaggletooths-realistic-sound-mod-fixed

https://www.moddb.com/games/return-to-castle-wolfenstein/downloads/sp-pak2020-wpk

It's nothing like the quality of RealRTCW's weapons, but it makes things a little better. The Venom mod is basically RealRTCW in a nutshell.

Cheers!
