### ISSUE TITLE
Subtitles support

### ISSUE THREAD

**Issue by DropsMJay** [iortcw/iortcw#172]
Hello. There's this post on Splash Damage forums that say it add suports to subtitles on the game:
https://forums.splashdamage.com/t/rtcw-with-support-subtitles/139652
A tutorial how to add:
https://wolfmap.ru/forum/viewtopic.php?p=29467#p29467

But it looks like there's some step missing, because I'm not getting it to work. I know there are subtitles in the RealRTCW mod, but I would like a more vanilla option.

Link to the "mod" i made with only the texts:
https://drive.google.com/file/d/1qvmf7NBxQSEfyvdSddLLpnufHm5pfasp/view?usp=share_link

Thank you

**Comment by MAN-AT-ARMS** [comment]
Game mods are outside the scope of this project
