### ISSUE TITLE
Mac os Latest version Apple silicon running with rosetta 2

### ISSUE THREAD

**Issue by haad** [iortcw/iortcw#173]
Game works well with rosetta only issue is that if you try to load a saved game from already running game ti hangs. I'm willing to debug it, just not sure how.

**Comment by KuehnhammerTobias** [comment]
Idk, but maybe related or the same issue as: https://github.com/iortcw/iortcw/issues/147

**Comment by haad** [comment]
I compiled new applicaiton from source code and it works as a charm.
