### ISSUE TITLE
Brightness slider does not work on linux build

### ISSUE THREAD

**Issue by SimonasZab** [iortcw/iortcw#180]
Tested on Steam Deck OLED with linux-x64 and win-x64 builds. Win-x64 brightness works normally, while linux-x64 slider does not work and the game is very dark. set r_ignorehwgamma 0 brightens the game, but then the brightness slider is hidden from the menu and the colors still feel off compared to win-x64 build and non iortcw build with 1.42d patch. Playing around with r_mapoverbrightbits, r_overbrightbits,  r_intensity and r_gamma I couldnt reproduce the correct image as I think r_gamma does not work after set r_ignorehwgamma 0

**Comment by MAN-AT-ARMS** [comment]
That's what r_ignorehwgamma is supposed to do. If you're trying to brighten the image try r_intensity instead.

**Comment by SimonasZab** [comment]
Yes I read that. But still the main problem exists which is that the brightness slider does not for on linux build

**Comment by SimonasZab** [comment]
I understand that, but Im saying that the brightness slider does not work on a fresh installed linux build and without executing any commands in the console.

**Comment by MAN-AT-ARMS** [comment]
I'm not able to reproduce that behavior. Open console and type r_ignorehwgamma (without value) and see what value it shows that it is set to. Possible also check your graphics driver settings

**Comment by SimonasZab** [comment]
It says that it is 0. Maybe it has something to do with SteamOS

**Comment by MAN-AT-ARMS** [comment]
r_ignorehwgamma is a latched cvar so if it is 0 in console try doing a vid_restatt and seeing if it still doesn't work. If it does work after a vid restart there may be a wolfconfig.cfg file somewhere on your system that has it set to 1
