### ISSUE TITLE
Machine gunner with MG-42 is bugged

### ISSUE THREAD

**Issue by SimonasZab** [iortcw/iortcw#181]
Machine gunner AI does not target player character and just shoots in a straight line or at the sky.

Tested iortcw linux-x64, win-x64 and GOG game with 1.42d patch. GOG game with 1.42d patch machine gunner works correct while both iortcw builds do not.

**Comment by MAN-AT-ARMS** [comment]
Sounds like you have your install fucked up.

**Comment by SimonasZab** [comment]
How is my install messed up? I did sepparate installs for each build and only on GOG RTCW without ioRTCW this works as intended

**Comment by SimonasZab** [comment]
I used the 1.51c build. I can see now that its oledr than this commit. Thanks, and will there be a new release any time soon?

**Comment by MAN-AT-ARMS** [comment]
Here is a current build for you to try...
http://beach.ecgnetwork.co/iortcw/iortcw-1.51d-Win.zip

**Comment by SimonasZab** [comment]
Yes, this is fixed in 1.51d
