### ISSUE TITLE
iortcw compilation on Ubuntu 16.10: I can not launch iortcw directly

### ISSUE THREAD

**Issue by legluondunet** [iortcw/iortcw#19]
Hello,

I upgraded to ubuntu 16.10 and when I compile iortcw, I can no more launch it directly from the explorer files (Nautilus), only from a terminal like this:
$ ./iortcw64
Do you think it is related to this:
https://wiki.ubuntu.com/SecurityTeam/PIE ?
Is iortcw compiled by default with pie on or off?

Iortcw is not the only open source software concerned by this Ubuntu change:
I had the same bug with Dolphin-emu (https://bugs.dolphin-emu.org/issues/9853), mame or nuke32.

Thank you for your help.

LGDN

**Comment by MAN-AT-ARMS** [comment]
https://bugzilla.icculus.org/show_bug.cgi?id=6429

Can you test this?
Replace the code/qcommon/vm_x86.c file with the one from this repo: 
https://github.com/thiloschulz/ioq3

Direct link to file:
https://raw.githubusercontent.com/thiloschulz/ioq3/master/code/qcommon/vm_x86.c

**Comment by legluondunet** [comment]
I just compiled iortcw, no change.

**Comment by MAN-AT-ARMS** [comment]
When I get a chance, I'll test an Ubuntu 16.10 install and attempt to resolve.

**Comment by MAN-AT-ARMS** [comment]
Seems to be an issue with Nautilus in 16.10 and not iortcw.
The behavior is the same even when not compiled as PIE.

Nemo file manager in Cinnamon on 16.10 allows binary (unmodified) to be launched without issue.

**Comment by legluondunet** [comment]
I'm not alone: it seems to be related to PIE and file manager:
https://bugs.launchpad.net/ubuntu/+source/gcc-defaults/+bug/1639531
https://ubuntuforums.org/showthread.php?t=2341593

**Comment by MAN-AT-ARMS** [comment]
Not sure about Dolphin but I did compile without PIE and it behaved the same.
The issue here is the file manager / mime handling in Nautilus and not iortcw.

**Comment by MAN-AT-ARMS** [comment]
It might be possible to use a launch script like the ones installed by the vanilla game:

#!/bin/sh
# Needed to make symlinks/shortcuts work.
# the binaries must run with correct working directory
cd "<path to application"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:."
exec ./iowolfmp.x86_64 "$@"

**Comment by legluondunet** [comment]
So it is not related to your soft, thank you for your help.
