### ISSUE TITLE
resolution

### ISSUE THREAD

**Issue by legluondunet** [iortcw/iortcw#20]
Hello,

I just compiled lastest iortcw version from git and I can not set correctly my resolution:
even if I choose 1920x1080 fullscreen (my desktop resolution), it stays in an inferior resolution. 
In the window mode  the resolution seems buggy too.
How do I can help you for debugging this?

Thank you for your help.

LGDN
config:
Ubuntu 16.10 64 bits
NVIDIA GeForce GTX 770
official Ubuntu Nvidia drivers 367.57 - 1920x1080

**Comment by MAN-AT-ARMS** [comment]
What cvars are you setting? 

For desktop resolution, use r_mode -2 and r_fullscreen 1
(Or alternatively, r_customheight 1080, r_customwidth 1920, r_mode -1, and r_fullscreen 1)

The config files are saved in $HOME/.wolf/main by default. (Named wolfconfig.cfg for SP and wolfconfig_mp.cfg for MP.)

You can edit those cvars in the config with your favorite editor, or set the cvars directly in the game console.

**Comment by legluondunet** [comment]
I changed directly values in the wolfconfig.cfg and wolfconfig_mp.cfg:
seta r_mode "-2" 
seta r_fullscreen "1"
seta r_noborder "0"
seta r_customwidth ""
seta r_customheight ""

I don't know why I had "23" value for r_mode
I erased r_customwidth and r_customheight "" values

Now the game uses my desktop resolution.
But if I change my resolution from the game interface, it does not work as expected.
It always put me a "24" or "26" values for r_mode. (SP)
In the multiplayer interface, I have only one resolution for WS mode: 856x480

**Comment by MAN-AT-ARMS** [comment]
The in game menu doesn't support those resolutions. For 1920x1080 you have to set the cvars that I mentioned directly via console or config file.

The resolutions available in the game menus were hardcoded by id Software / Nerve and are not changeable, so you don't want to use those at this time. I may attempt working around that limitation at some point but I haven't done that yet.

If the r_mode is getting changed after starting game, you may want to check and see if it is being reset by another config file (such as the autoexec.cfg file)

**Comment by legluondunet** [comment]
> The resolutions available in the game menus were hardcoded by id Software / Nerve and are not changeable, so you don't want to use those at this time. I may attempt working around that limitation at some point but I haven't done that yet.

> 

I didn't know this feature is not yet implemented.

**Comment by MAN-AT-ARMS** [comment]
Implemented in 7a71031
