### ISSUE TITLE
Cannot enter CD-Key

### ISSUE THREAD

**Issue by OlliC** [iortcw/iortcw#22]
To play online some servers require to have a CD-Key set. 
I tried to enter mine in the Settings but it cannot be entered. 
The cursor just keeps blinking while typing. 

System Info: 
Arch Linux
Gnome Shell
Nvidia GTX 660 (Driver 375.20)

**Comment by MAN-AT-ARMS** [comment]
You can enter it and this is something I forgot to address before 
putting out the release.

The four boxes where you enter your key are actually filled with spaces. 
So if you click inside a box hit the backspace and/or delete key inside 
the box to clear the spaces in there.
You will be able to enter the key after clearing out the spaces in there.

Donny

**Comment by OlliC** [comment]
Oh ok. Makes sense. 

Solved it by copying the rtcwkey file from the CD to the main folder and then edited the key ingame. I tought that maybe you have to have this file before starting up the game.

**Comment by MAN-AT-ARMS** [comment]
Fixed in 133cb06
