### ISSUE TITLE
Mac version unable to enter cd key

### ISSUE THREAD

**Issue by crichardson32** [iortcw/iortcw#23]
On the mac version i am unable to enter the cd key for some reason.

I can reasign mapped keys under keyboard config fine, type in console, enter letters in the very last box of key and even tab between the boxes but for some reason it doesnt register any keys in the first 4 boxes

This is on a macbook pro

sw_vers 
ProductName:	Mac OS X
ProductVersion:	10.11.4
BuildVersion:	15E65

**Comment by crichardson32** [comment]
So just an update .. i still cant enter my key so instead i modified the code here https://github.com/iortcw/iortcw/blob/master/MP/code/qcommon/common.c#L2492
and added
Q_strncpyz( cl_cdkey, "my key no dashes", 17 );                                                                                                                                                                                               
return;

I know dirty nono but i wanted to play

**Comment by MAN-AT-ARMS** [comment]
See here:
https://github.com/iortcw/iortcw/issues/22
