### ISSUE TITLE
Build from source fails on linux

### ISSUE THREAD

**Issue by phenixia2003** [iortcw/iortcw#24]
Hello,

Building iortcw 1.5a from source  on linux (slackware 14.1/14.2) fails with error :

`make[2]: *** No rule to make target '../.git/index', needed by 'build/release-linux-x86_64/client/cl_console.o'.  Stop.`

I checked the Makefile and found that error is due to the line #2661 which makes reference to file ../.git/index that is not part of source archive. Since line #2662 and #2663 make reference to this file as well, I removed these lines and compilation went well this time. 

It seems that issue comes from commit [d6094c](https://github.com/iortcw/iortcw/commit/d6094cdec43aaaeaa2dd445de97b794188986332)

-- 
SeB

**Comment by MAN-AT-ARMS** [comment]
You're right...

Lines 2706-2708 (MP) and 2672-2674 (SP) in the Makefile should have been removed as well.

**Comment by MAN-AT-ARMS** [comment]
Should work with this release tarball. Thanks
