### ISSUE TITLE
Unpure client detected

### ISSUE THREAD

**Issue by crichardson32** [iortcw/iortcw#25]
Version: iortcw master(133cb06cd303b5b992c38f6b4b9935d19a8e4bae)
System: Mac
Message: Unpure client detected invalid pk3 files referenced.
When: Trying to join a mp server

pk3s
MD5 (main/mp_bin.pk3) = 7651d02fe51fc8a949536f3e0cfa8dd6
MD5 (main/mp_pak0.pk3) = 62641cffd9a8ad0f62cc1cca867d51f8
MD5 (main/mp_pak1.pk3) = 22b972974f499a237c96a2200b0d019e
MD5 (main/mp_pak2.pk3) = 30f29ffa81748a957e0441af8c14cb56
MD5 (main/mp_pak3.pk3) = fdc00dfd72b888e92a4387e1933826e4
MD5 (main/mp_pak4.pk3) = c5f76bbde262eba577a00bebe9cd4f8f
MD5 (main/mp_pak5.pk3) = d17df62d6c71078ed137aefc69d80f30
MD5 (main/mp_pakmaps0.pk3) = f2d361a0082ed9bc1e26d2327b4f22db
MD5 (main/mp_pakmaps1.pk3) = d1856aa9bc62f719a400428b9ec27ebb
MD5 (main/mp_pakmaps2.pk3) = a0ee8714c6f7ee72680293778c22d6ee
MD5 (main/mp_pakmaps3.pk3) = 01bb7c4fb3b11273d75ae658fb4de0cc
MD5 (main/mp_pakmaps4.pk3) = a39525809f7a0780f5546063dad1e5d1
MD5 (main/mp_pakmaps5.pk3) = bb24fb011b0f4b84335c66a869d1ab1c
MD5 (main/mp_pakmaps6.pk3) = 397e0b48673a1a8e0ec25eb0f3ccae9d
MD5 (main/pak0.pk3) = ce92b11df889cb0a045762bb5fd7cde5
MD5 (main/sp_pak1.pk3) = a0d3fe956f85f40c8efd6babe0d09832
MD5 (main/sp_pak2.pk3) = 330b272d5261fe19fcf3c3fbc943c7f3
MD5 (main/sp_pak3.pk3) = cf25d6731ed29c80303febbb177aa585
MD5 (main/sp_pak4.pk3) = 4223cc6588594ec0ceee186f0e73a6e9

**Comment by MAN-AT-ARMS** [comment]
You're missing some of the pk3 files from the release zip. In particular, mp_bin0.pk3.

What server is it?

**Comment by crichardson32** [comment]
I found the mp_bin0 and i can now connect to ecg server but i still get it on most servers like 
198.144.177.2:27968 and 91.198.152.133:27960

**Comment by MAN-AT-ARMS** [comment]
That would be a question for those server admins. They would need that file on their server.

You can try setting the cvars vm_cgame 0 and vm_ui 0. That might work, might not.

It's really something the admins of those server would need to address. Those servers are running Omni-bot. I'm not sure if that mod has files for Mac or not.

**Comment by crichardson32** [comment]
ah ok .. 1 last question on server 216.52.143.172:27960 it is an osp one and there is a mac version of that but it requires pb .. is there a way to make it enabled?

**Comment by Mateos81** [comment]
Omni-Bot has binaries for Windows and Linux, not Mac. The latest 0.85 version supports ioRtCW x64 btw.

Since ioRtCW is a source rework, due to rights, I'm afraid like ET PunkBuster can't be included within it ^^'

**Comment by MAN-AT-ARMS** [comment]
FYI...The Mac version of OSP is built for PPC. It won't run on anything after OSX 10.6. (and actually may not run at all.)

In the case of even trying to use that on 10.6, the dll files would need renamed for use with iortcw. It certainly was never tested.
