### ISSUE TITLE
cl_consoleKeys breaks functionality for dual KB layout

### ISSUE THREAD

**Issue by donkz** [iortcw/iortcw#27]
I have US and other (russian) layouts selected from windows settings. Most common way of switching keyboards is ALT+SHIFT which can be pressed a lot during gameplay and keyboard flips EN-RU-EN all the time.

The issue with iortcw is the cl_consoleKeys functionality breaks the 100% responsiveness to tilde key.

Console appears fine if the KB layout happens to be EN (50% of the time)
The other 50% nothing happens when i press tilde, so i have to switch layout first. 

I figure this is a breaking change following the iortcw philosophy of only introducing optional changes switched off by default.

When my KB layout is different i get char ъ , which is hex 0x3f
When i type this key in console i get J (latin capital j) - which is also different from rtcw. Hex - 0x4a

So i thought implementing this would work 

seta cl_consoleKeys "~ ` 0x7e 0x60 0x3f J 0x4a"

But nothing happens. 

I think the priority should be given to original code of TILDE key and then cl_consoleKeys logic.

PS: as mentioned above, non-US keyboard input produces garbage. It always did, but it produces different garbage than before. I would be a nice feature if iortcw recognized the keystrokes and 
either 
1. translated them from RU back to basic EN automatically to avoid errors (best)
OR 
2. Like Quake live allowed unicode characters (latin and others) (no point really)

**Comment by MAN-AT-ARMS** [comment]
Does ALT+ESC not work for you to bring down console?

**Comment by donkz** [comment]
It does, didn't know it was a thing!

**Comment by MAN-AT-ARMS** [comment]
Yes. SHIFT+ESC is hard coded.

If you need help determining values to use for cl_consolekeys you can enable keyboard debugging and see what values are spit out.

in_keyboardDebug 1

**Comment by donkz** [comment]
HEre's console log. I set console keys to what seems to should work , switch layout and try tilde.

"cl_consoleKeys" is:"~ ` 0x7e 0x60 0x44a 0x00 0x35" default:"~ ` 0x7e 0x60"
  Scancode: 0x28(Return) Sym: 0x0d(Return) Q:0x0d(ENTER)
+ Scancode: 0xe2(Left Alt) Sym: 0x400000e2(Left Alt) Q:0x88(ALT)
+ Scancode: 0xe1(Left Shift) Sym: 0x400000e1(Left Shift) KMOD_LALT
Q:0x8a(SHIFT)
  Scancode: 0xe2(Left Alt) Sym: 0x400000e2(Left Alt) KMOD_LSHIFT Q:0x88(ALT)
  Scancode: 0xe1(Left Shift) Sym: 0x400000e1(Left Shift) Q:0x8a(SHIFT)
+ Scancode: 0x35(`) Sym: 0x44a(ъ) Q:0x00(0x00)
  Scancode: 0x35(`) Sym: 0x44a(ъ) Q:0x00(0x00)

here console does not come up

**Comment by donkz** [comment]
in actual wolf console the char also looks like Ñ . I found it in ascii tables as extended char dec(209) hex(0xD1). Also does not work

**Comment by MAN-AT-ARMS** [comment]
Yeah I see what was happening there. I committed a fix for it in a4b3312.

You should be able to add 0x44a as a console key now.
