### ISSUE TITLE
On Raspberry pi

### ISSUE THREAD

**Issue by sem8900** [iortcw/iortcw#29]
compilation terminated.
Makefile:2556: recipe for target 'build/release-linux-arm/renderer/tr_animation.o' failed
make[2]: *** [build/release-linux-arm/renderer/tr_animation.o] Error 1
make[2]: Leaving directory '/home/sem/iortcw/SP'
Makefile:1303: recipe for target 'targets' failed
make[1]: *** [targets] Error 2
make[1]: Leaving directory '/home/sem/iortcw/SP'
Makefile:1254: recipe for target 'release' failed
make: *** [release] Error 2

**Comment by MAN-AT-ARMS** [comment]
Need more information than that.

Which Raspberry Pi? Which distro?

Please post full console output.

**Comment by sem8900** [comment]
Ok, distro raspibian, raspberry pi 3 , full console input be soon

**Comment by sem8900** [comment]
*console output

**Comment by sem8900** [comment]
make[1]: Entering directory '/home/sem/iortcw/SP'

Building in build/release-linux-arm:
  PLATFORM: linux
  ARCH: arm
  FILE_ARCH: arm
  VERSION: 1.51-SP_GIT_b3b521e-2017-02-07
  COMPILE_PLATFORM: linux
  COMPILE_ARCH: arm
  HAVE_VM_COMPILED: true
  CC: cc
  CXX: g++

  CFLAGS:
    -Wall -fno-strict-aliasing -pipe -DUSE_ICON
    -DARCH_STRING="arm" -DUSE_OPENGLES -DNO_GZIP -Icode/zlib-1.2.8
    -DUSE_INTERNAL_JPEG -Icode/jpeg-8c -DBUILD_FREETYPE
    -Icode/freetype-2.6.4/include -DFT2_BUILD_LIBRARY -DUSE_LOCAL_HEADERS
    -DPRODUCT_VERSION="1.51-SP_GIT_b3b521e-2017-02-07" -Wformat=2
    -Wformat-security -Wno-format-nonliteral -Wstrict-aliasing=2
    -Wmissing-format-attribute -Wdisabled-optimization -MMD -DNDEBUG -O3
    -ffast-math

  CLIENT_CFLAGS:
    -Icode/SDL2/include -DUSE_OPENAL -DUSE_OPENAL_DLOPEN

  SERVER_CFLAGS:


  LDFLAGS:
    -L/opt/vc/lib

  LIBS:
    -ldl -lm

  CLIENT_LIBS:
    -lbcm_host

  Output:
    iowolfsp.arm
    main/cgame.sp.arm.so
    main/qagame.sp.arm.so
    main/ui.sp.arm.so

make[2]: Entering directory '/home/sem/iortcw/SP'
REF_CC code/renderer/tr_animation.c
In file included from code/renderer/qgl.h:38:0,
                 from code/renderer/tr_local.h:37,
                 from code/renderer/tr_animation.c:30:
code/SDL2/include/SDL_opengles.h:33:21: fatal error: GLES/gl.h: No such file or directory
 #include <GLES/gl.h>
                     ^
compilation terminated.
Makefile:2556: recipe for target 'build/release-linux-arm/renderer/tr_animation.o' failed
make[2]: *** [build/release-linux-arm/renderer/tr_animation.o] Error 1
make[2]: Leaving directory '/home/sem/iortcw/SP'
Makefile:1303: recipe for target 'targets' failed
make[1]: *** [targets] Error 2
make[1]: Leaving directory '/home/sem/iortcw/SP'
Makefile:1254: recipe for target 'release' failed
make: *** [release] Error 2

**Comment by MAN-AT-ARMS** [comment]
Are you using the build script?

./make-raspberrypi.sh

**Comment by sem8900** [comment]
I use ./make-raspberrypi.sh

**Comment by sem8900** [comment]
And i have sdl2 installed

**Comment by MAN-AT-ARMS** [comment]
Maybe something changed in Raspbian since Jessie?

Try doing this commandline:
CLIENT_CFLAGS='-D_REENTRANT -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -Icode/SDL2/include -DUSE_OPENAL -DUSE_OPENAL_DLOPEN' CLIENT_LIBS='-lSDL2 -lbcm_host' ./make-raspberrypi.sh

**Comment by MAN-AT-ARMS** [comment]
This help at all?
