### ISSUE TITLE
ioRTCW in realtRTCW 2.1 issues

### ISSUE THREAD

**Issue by donizettilorenzo** [iortcw/iortcw#31]
*r_swapinterval 1 -> CL_Initgame=1 minute (!)
*max anisotropy autoset to 2 (instead of 16) with a GeForce GTX 1050 Ti, lastest drivers

**Comment by MAN-AT-ARMS** [comment]
I believe both of those may be related to driver settings that NVIDIA 
changed. (OPENGL -> Sync to VBlank, Antialiasing Settings)

**Comment by donizettilorenzo** [comment]
*Forcing the VSync in NVCP produces the same result, so it seems you're right. Can't you avoid this behaviour redefining the r_swapinterval-related functions?
*The ANISOTROPIC filtering, not the antialiasing! Forcing 16x manually in the config file works but ioRTCW (ioWolfSP of realtRTCW 2.1) can only see 2x as the AF maximum value.

**Comment by MAN-AT-ARMS** [comment]
I think you might need r_displayrefresh set to monitor refresh to use 
that but I'm not in front of it to test (r_swapinterval).
I'll check the ansio thing but might be SDL related.

Which build are you using?

**Comment by donizettilorenzo** [comment]
I'm using this: http://www.moddb.com/mods/realrtcw-realism-mod
I'll test the interaction with r_displayrefresh, thanks!

**Comment by MAN-AT-ARMS** [comment]
Regarding the ansiotropic, do you have the cvars set?
r_ext_texture_filter_ansiotropic 1
r_ext_max_anisotropy 16

**Comment by MAN-AT-ARMS** [comment]
Patch for r_swapinterval committed in 6bf0ccf

**Comment by donizettilorenzo** [comment]
Thanks!
r_ext_max_anisotropy is the maximum AF level declared by the driver, not the actual value
The other variable is the actual value. r_ext_max_anisotropy "auto"sets to 2 instead of 16, so there's some problem interfacing with NV OpenGL driver (I think). I can force either to 16 in the config file and so have them working.

**Comment by MAN-AT-ARMS** [comment]
I'm not following what you are saying.

If you force 16x in the "Override Application settings" in the NVIDIA driver, the value of r_ext_max_anisotropy is "autoset" to 16. (Provided you have r_ext_texture_filter_anisotropic set to 1)

If you do NOT force 16x in the driver settings, the value is whatever you set the cvar r_ext_max_anisotropy to be. (Also provided you have r_ext_texture_filter_anisotropic set to 1)

At least this is the behavior I'm seeing.

**Comment by donizettilorenzo** [comment]
I'm saying that forcing NOTHING (nor in *.cfg files nor in NVCP) produces this:

seta r_ext_max_anisotropy "2"

instead of finding the "correct" max value that is "16" for the today GPUs.

r_ext_texture_filter_anisotropic can be set from 1 to 16 and is this variable that controls the AF in game.

**Comment by MAN-AT-ARMS** [comment]
Mine uses 16 when I have  r_ext_texture_filter_anisotropic set to 1 (Even with r_ext_max_anisotropy set to 2) and I'm using Application Controlled (not forced) so I'm not really seeing what you are.

**Comment by zturtleman** [comment]
@donizettilorenzo those cvars do not work how you think they do.

r_ext_texture_filter_anisotropic is only checked if it's not 0. All non-0 values including negative ones enable anisotropic filter mode. When enabled, the console prints the driver's max anisotropy. "...using GL_EXT_texture_filter_anisotropic (max: *driver's max*)"

r_ext_max_anisotropy is the user's desired anisotropy, which defaults to 2 (which is the minimal value for anisotropic filtering; 1 is the same as none). It's never set to the driver's max anisotropy. It's not broken, the user just has to set it higher if they want more anisotropy. The user can set it higher or lower than the driver supports.

Pseudocode:
```
if r_ext_texture_filter_anisotropic not equal to 0:
    setTextureFilterAnisotropic( enabled )
    desiredAnisotropy = r_ext_max_anisotropy

if  desiredAnisotropy more than driver's max_anisotropy:
    desiredAnisotropy = driver's max_anisotropy

if desiredAnisotropy less than 1:
    desiredAnisotropy = 1

setTextureAnisotropy( desiredAnisotropy )
```

**Comment by donizettilorenzo** [comment]
Thanks! My bad (misunderstood the "max" )
