### ISSUE TITLE
Scaling problems with Nvidia card.

### ISSUE THREAD

**Issue by PsYchitOut** [iortcw/iortcw#32]
I am trying to play rtcw in 1080 and running into an issue with display scaling. It seems no matter what settings I tweak either in my video card or in the game massive amounts of the screen bleed out of the boundaries of my monitor. I have an ASUS gaming laptop with a GeForce 960m.

**Comment by MAN-AT-ARMS** [comment]
Not sure. Do you have any pictures of it? Where it occurs?
Is it just this game that behaves that way?

**Comment by PsYchitOut** [comment]
Ask and you shall receive.
![20170611221806_1](https://user-images.githubusercontent.com/24470080/27017234-ffbda124-4ef4-11e7-94d1-2e6fb5df54fb.jpg)
This is what the game looks like attempting to run it at 1080p, 
![20170611221823_1](https://user-images.githubusercontent.com/24470080/27017259-3917af0a-4ef5-11e7-87fe-68dc40e32e3b.jpg)
I tried to test it in game but I can't get past the loading screen for obvious reasons
![20170611222323_1](https://user-images.githubusercontent.com/24470080/27017286-6ee47c26-4ef5-11e7-9f1c-174d0d03971f.jpg)
as you can see the problem seems to occur at just about any widescreen resolution 800X540 and above and yes while it is playable, would you want to.
I also attempted to play the game under the native setting to this result.
![20170611221419_1](https://user-images.githubusercontent.com/24470080/27017337-be19f5f0-4ef5-11e7-8fab-45f218bf8448.jpg)
While initialy promising it seems that the top and right of the screen is actually some form of artifacting.
![20170611221506_1](https://user-images.githubusercontent.com/24470080/27017376-02758d0e-4ef6-11e7-8fb2-a027b8e59b7d.jpg)
Thats what it looks like after going into my Steam guide menu
![20170611221524_1](https://user-images.githubusercontent.com/24470080/27017399-24009ff4-4ef6-11e7-82ed-81af859a4e6a.jpg)
and thats what it looks like after alt+tabbing out of the game just to address my point.
As far as your question of if this happens in other games my answer is.... kinda. As someone who plays a lot of older games on my pc for nostalgia sake do see this problem a lot with outdated engines trying to render high res graphics on their own, which is why my first instict is to seek out source ports like yours. This problem also exists in the base game with the unofficial patch, though to your guys credit iortcw handles high res 4x3 resolutions just fine while the base game messes up at just about anything over 1600x900. I read a few things online about changing some options in Nvidias config menu on display scaling although with mobile graphics cards Nvidias config setting are neutered in favor of tying them in with Intels graphics program which doesn't do a damn thing to fix the problem. Though from what I read during my research online the scaling options in Nvidias config program during recent updates doesn't seem to do jack either. Let me know if I can do anything else its always good to see people keeping the classics alive.

**Comment by Mateos81** [comment]
Here, with a Lenovo laptop, GTX 960M, 1920x1080, no issue, fyi

I have the latest LENOVO drivers (because several constructors supply different drivers, adapted to their tweaks)

**Comment by MAN-AT-ARMS** [comment]
Yeah that is strange.

Have you tried using the Automatic (Native) Setting (r_mode -2)?
Also, open console and use /seta logfile 2
This should generate an rtcwconsole.log file in your Documents/RTCW/main folder.

Please copy/paste the output of the rtcwconsole.log file.

**Comment by PsYchitOut** [comment]
I tried using native before. It was the option that gave the artifiacting in the corners but for the sake of experimentation I set it using the console to about the same result. I also made a copy of my console log for you 
logfile opened on Mon Jun 12 10:10:34 2017

Bypassing CD checks
----- Client Initialization -----
Cmd_AddCommand: map_restart already defined
----- Initializing Renderer ----
Trying to load "renderer_sp_opengl1_x64.dll" from "D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein"...
---- Renderer Initialization Complete ----
RTCWKEY found.
----- Client Initialization Complete -----
----- R_Init -----
SDL using driver "windows"
Initializing OpenGL display
Display aspect: 1.778
...setting mode 17: 1024 576
Using 24 color bits, 24 depth, 0 stencil display.
Available modes: '1280x720 1366x768 1600x900 1920x1080 1360x768 1280x768 320x200 640x400 1280x800 1440x900 1680x1050 1280x600 320x240 400x300 512x384 640x480 800x600 1024x768 1152x864 1280x960 1400x1050 1280x1024'
GL_RENDERER: GeForce GTX 960M/PCIe/SSE2
Initializing OpenGL extensions
...ignoring GL_EXT_texture_compression_s3tc
...ignoring GL_S3_s3tc
...using GL_EXT_texture_env_add
...using GL_ARB_multitexture
...using GL_EXT_compiled_vertex_array
...using GL_EXT_texture_filter_anisotropic (max: 16)
Initializing Shaders
^3WARNING: In shader file scripts/common.shader...Shader "textures/sfx/portal3a_back2" on line 822 is missing closing brace^3.
^3WARNING: In shader file scripts/ui_wolf.shader...Invalid shader name "}" on line 1849.
----- finished R_Init -----
------ Initializing Sound ------
Trying to load "OpenAL32.dll"...
Allocated 128 sources.
OpenAL default capture device is 'Microphone (Realtek High Defini'
OpenAL capture device opened.
OpenAL info:
  Vendor:         Creative Labs Inc.
  Version:        1.1
  Renderer:       Software
  AL Extensions:  EAX EAX2.0 EAX3.0 EAX4.0 EAX5.0 EAX3.0EMULATED EAX4.0EMULATED AL_EXT_OFFSET AL_EXT_LINEAR_DISTANCE AL_EXT_EXPONENT_DISTANCE
  ALC Extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_EFX
  Device:         Generic Software on Speakers (Realtek High Definition Audio)
  Available Devices:
Generic Software on Speakers (Realtek High Definition Audio)
  Input Device:   Microphone (Realtek High Defini
  Available Input Devices:
Microphone (Realtek High Defini
Sound initialization successful.
--------------------------------
--- Common Initialization Complete ---
Winsock Initialized
Hostname: DESKTOP-JC4O9K7
IP6: fe80::dcbe:a815:c6c7:8fcb%11
IP6: fe80::4af:3087:94b2:5fb0%2
IP: 192.168.43.171
IP6: 2001:0:9d38:90d7:4af:3087:94b2:5fb0
Opening IP6 socket: [::]:27960
Opening IP socket: 0.0.0.0:27960
]/seta logfile 2
Hunk_Clear: reset the hunk ok
RE_Shutdown( 1 )
----- Initializing Renderer ----
Trying to load "renderer_sp_opengl1_x64.dll" from "D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein"...
---- Renderer Initialization Complete ----
----- R_Init -----
SDL using driver "windows"
Initializing OpenGL display
Display aspect: 1.778
...setting mode 26: 1920 1080
Using 24 color bits, 24 depth, 0 stencil display.
Available modes: '1280x720 1366x768 1600x900 1920x1080 1360x768 1280x768 320x200 640x400 1280x800 1440x900 1680x1050 1280x600 320x240 400x300 512x384 640x480 800x600 1024x768 1152x864 1280x960 1400x1050 1280x1024'
GL_RENDERER: GeForce GTX 960M/PCIe/SSE2
Initializing OpenGL extensions
...ignoring GL_EXT_texture_compression_s3tc
...ignoring GL_S3_s3tc
...using GL_EXT_texture_env_add
...using GL_ARB_multitexture
...using GL_EXT_compiled_vertex_array
...using GL_EXT_texture_filter_anisotropic (max: 16)
Initializing Shaders
^3WARNING: In shader file scripts/common.shader...Shader "textures/sfx/portal3a_back2" on line 822 is missing closing brace^3.
^3WARNING: In shader file scripts/ui_wolf.shader...Invalid shader name "}" on line 1849.
----- finished R_Init -----
Hunk_Clear: reset the hunk ok
RE_Shutdown( 1 )
----- Initializing Renderer ----
Trying to load "renderer_sp_opengl1_x64.dll" from "D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein"...
---- Renderer Initialization Complete ----
----- R_Init -----
SDL using driver "windows"
Initializing OpenGL display
Display aspect: 1.778
...setting mode 14: 800 450
Using 24 color bits, 24 depth, 0 stencil display.
Available modes: '1280x720 1366x768 1600x900 1920x1080 1360x768 1280x768 320x200 640x400 1280x800 1440x900 1680x1050 1280x600 320x240 400x300 512x384 640x480 800x600 1024x768 1152x864 1280x960 1400x1050 1280x1024'
GL_RENDERER: GeForce GTX 960M/PCIe/SSE2
Initializing OpenGL extensions
...ignoring GL_EXT_texture_compression_s3tc
...ignoring GL_S3_s3tc
...using GL_EXT_texture_env_add
...using GL_ARB_multitexture
...using GL_EXT_compiled_vertex_array
...using GL_EXT_texture_filter_anisotropic (max: 16)
Initializing Shaders
^3WARNING: In shader file scripts/common.shader...Shader "textures/sfx/portal3a_back2" on line 822 is missing closing brace^3.
^3WARNING: In shader file scripts/ui_wolf.shader...Invalid shader name "}" on line 1849.
----- finished R_Init -----
Hunk_Clear: reset the hunk ok
RE_Shutdown( 1 )
----- Initializing Renderer ----
Trying to load "renderer_sp_opengl1_x64.dll" from "D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein"...
---- Renderer Initialization Complete ----
----- R_Init -----
SDL using driver "windows"
Initializing OpenGL display
Display aspect: 1.778
...setting mode -2: 1536 864
Using 24 color bits, 24 depth, 0 stencil display.
Available modes: '1280x720 1366x768 1600x900 1920x1080 1360x768 1280x768 320x200 640x400 1280x800 1440x900 1680x1050 1280x600 320x240 400x300 512x384 640x480 800x600 1024x768 1152x864 1280x960 1400x1050 1280x1024'
GL_RENDERER: GeForce GTX 960M/PCIe/SSE2
Initializing OpenGL extensions
...ignoring GL_EXT_texture_compression_s3tc
...ignoring GL_S3_s3tc
...using GL_EXT_texture_env_add
...using GL_ARB_multitexture
...using GL_EXT_compiled_vertex_array
...using GL_EXT_texture_filter_anisotropic (max: 16)
Initializing Shaders
^3WARNING: In shader file scripts/common.shader...Shader "textures/sfx/portal3a_back2" on line 822 is missing closing brace^3.
^3WARNING: In shader file scripts/ui_wolf.shader...Invalid shader name "}" on line 1849.
----- finished R_Init -----
sv_maxclients will be changed upon restarting.
------ Server Initialization ------
Server: cutscene1
RE_Shutdown( 0 )
Hunk_Clear: reset the hunk ok
Current search path:
C:\Users\iant1\Documents\RTCW\main
D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein\main\sp_rend2_shaders0.pk3 (5 files)
D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein\main\sp_pak4.pk3 (21 files)
D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein\main\sp_pak3.pk3 (14 files)
D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein\main\sp_pak2.pk3 (232 files)
D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein\main\sp_pak1.pk3 (1342 files)
D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein\main\pak0.pk3 (4775 files)
D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein\main
c:/program files (x86)/steam\SteamApps\common\Return To Castle Wolfenstein\main

handle 1: rtcwconsole.log
----------------------
6389 files in pk3 files
Gametype changed, clearing session data.
------- BotLib Initialization -------
------------ Map Loading ------------
trying to load maps/cutscene1_b0.aas
loaded maps/cutscene1_b0.aas
trying to load maps/cutscene1_b1.aas
loaded maps/cutscene1_b1.aas
-------------------------------------
AAS initialized.
AAS initialized.
-----------------------------------
RE_Shutdown( 0 )
----- R_Init -----
Initializing Shaders
^3WARNING: In shader file scripts/common.shader...Shader "textures/sfx/portal3a_back2" on line 822 is missing closing brace^3.
^3WARNING: In shader file scripts/ui_wolf.shader...Invalid shader name "}" on line 1849.
----- finished R_Init -----
LOADING... collision map
LOADING... sounds

.........................
Initializing Sound Scripts
...loading 'sound/scripts/cutscene1.sounds'
...loading 'sound/scripts/cutscene6.sounds'
...loading 'sound/scripts/cutscene9.sounds'
...loading 'sound/scripts/cutscene11.sounds'
...loading 'sound/scripts/cutscene14.sounds'
...loading 'sound/scripts/cutscene19.sounds'
...loading 'sound/scripts/escape1.sounds'
...loading 'sound/scripts/escape2.sounds'
...loading 'sound/scripts/tram.sounds'
...loading 'sound/scripts/village1.sounds'
...loading 'sound/scripts/crypt1.sounds'
...loading 'sound/scripts/crypt2.sounds'
...loading 'sound/scripts/church.sounds'
...loading 'sound/scripts/boss1.sounds'
...loading 'sound/scripts/forest.sounds'
...loading 'sound/scripts/rocket.sounds'
...loading 'sound/scripts/assault.sounds'
...loading 'sound/scripts/sfm.sounds'
...loading 'sound/scripts/factory.sounds'
...loading 'sound/scripts/trainyard.sounds'
...loading 'sound/scripts/swf.sounds'
...loading 'sound/scripts/norway.sounds'
...loading 'sound/scripts/xlabs.sounds'
...loading 'sound/scripts/boss2.sounds'
...loading 'sound/scripts/dam.sounds'
...loading 'sound/scripts/village2.sounds'
...loading 'sound/scripts/chateau.sounds'
...loading 'sound/scripts/dark.sounds'
...loading 'sound/scripts/castle.sounds'
...loading 'sound/scripts/end.sounds'
...loading 'sound/scripts/ai.sounds'
...loading 'sound/scripts/general.sounds'
...loading 'sound/scripts/combat.sounds'
...loading 'sound/scripts/movers.sounds'
done.
LOADING... graphics
LOADING... maps/cutscene1.bsp
stitched 0 LoD cracks
...loaded 2413 faces, 25 meshes, 147 trisurfs, 17 flares
LOADING... game media
LOADING...  - textures
LOADING...  - models
LOADING...  - weapons
LOADING...  - items
LOADING...  - inline models
LOADING...  - server models
LOADING...  - particles
LOADING...  - game media done
LOADING... flamechunks
LOADING... clients
LOADING... WolfPlayer
UI menu load time = 2 milli seconds
CL_InitCGame:  1.55 seconds
25 msec to draw all images
Com_TouchMemory: 0 msec
sv_maxclients will be changed upon restarting.
AAS shutdown.
------ Server Initialization ------
Server: escape1
RE_Shutdown( 0 )
Hunk_Clear: reset the hunk ok
Current search path:
C:\Users\iant1\Documents\RTCW\main
D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein\main\sp_rend2_shaders0.pk3 (5 files)
D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein\main\sp_pak4.pk3 (21 files)
D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein\main\sp_pak3.pk3 (14 files)
D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein\main\sp_pak2.pk3 (232 files)
D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein\main\sp_pak1.pk3 (1342 files)
D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein\main\pak0.pk3 (4775 files)
D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein\main
c:/program files (x86)/steam\SteamApps\common\Return To Castle Wolfenstein\main

handle 1: rtcwconsole.log
----------------------
6389 files in pk3 files
------- BotLib Initialization -------
------------ Map Loading ------------
trying to load maps/escape1_b0.aas
loaded maps/escape1_b0.aas
trying to load maps/escape1_b1.aas
loaded maps/escape1_b1.aas
-------------------------------------
AAS initialized.
AAS initialized.
-----------------------------------
RE_Shutdown( 0 )
----- R_Init -----
Initializing Shaders
^3WARNING: In shader file scripts/common.shader...Shader "textures/sfx/portal3a_back2" on line 822 is missing closing brace^3.
^3WARNING: In shader file scripts/ui_wolf.shader...Invalid shader name "}" on line 1849.
----- finished R_Init -----
LOADING... collision map
LOADING... sounds

.........................
Initializing Sound Scripts
...loading 'sound/scripts/cutscene1.sounds'
...loading 'sound/scripts/cutscene6.sounds'
...loading 'sound/scripts/cutscene9.sounds'
...loading 'sound/scripts/cutscene11.sounds'
...loading 'sound/scripts/cutscene14.sounds'
...loading 'sound/scripts/cutscene19.sounds'
...loading 'sound/scripts/escape1.sounds'
...loading 'sound/scripts/escape2.sounds'
...loading 'sound/scripts/tram.sounds'
...loading 'sound/scripts/village1.sounds'
...loading 'sound/scripts/crypt1.sounds'
...loading 'sound/scripts/crypt2.sounds'
...loading 'sound/scripts/church.sounds'
...loading 'sound/scripts/boss1.sounds'
...loading 'sound/scripts/forest.sounds'
...loading 'sound/scripts/rocket.sounds'
...loading 'sound/scripts/assault.sounds'
...loading 'sound/scripts/sfm.sounds'
...loading 'sound/scripts/factory.sounds'
...loading 'sound/scripts/trainyard.sounds'
...loading 'sound/scripts/swf.sounds'
...loading 'sound/scripts/norway.sounds'
...loading 'sound/scripts/xlabs.sounds'
...loading 'sound/scripts/boss2.sounds'
...loading 'sound/scripts/dam.sounds'
...loading 'sound/scripts/village2.sounds'
...loading 'sound/scripts/chateau.sounds'
...loading 'sound/scripts/dark.sounds'
...loading 'sound/scripts/castle.sounds'
...loading 'sound/scripts/end.sounds'
...loading 'sound/scripts/ai.sounds'
...loading 'sound/scripts/general.sounds'
...loading 'sound/scripts/combat.sounds'
...loading 'sound/scripts/movers.sounds'
done.
LOADING... graphics
LOADING... maps/escape1.bsp
stitched 12 LoD cracks
...loaded 14663 faces, 284 meshes, 367 trisurfs, 7 flares
LOADING... game media
LOADING...  - textures
LOADING...  - models
LOADING...  - weapons
LOADING...  - items
LOADING...  - inline models
LOADING...  - server models
LOADING...  - particles
LOADING...  - game media done
LOADING... flamechunks
LOADING... clients
LOADING... WolfPlayer
UI menu load time = 2 milli seconds
CL_InitCGame:  1.53 seconds
30 msec to draw all images
Com_TouchMemory: 0 msec
^3turning EXEC_NOW 'quit' into EXEC_INSERT
----- Server Shutdown (Server quit) -----
AAS shutdown.
---------------------------
----- Client Shutdown (Client quit) -----
RE_Shutdown( 1 )
Hunk_Clear: reset the hunk ok
OpenAL capture device closed.
-----------------------

**Comment by ensiform** [comment]
The problem isn't your Nvidia card. It's Windows automatically scaling with a different text scale option.  The game needs DPI awareness setup correctly to be able to have a proper resolution without affecting the size.

**Comment by Mateos81** [comment]
Right click on Desktop, Display parameters: by default in Windows 10 I had 110% but quickly changed it to 100% because I had issues with my mouse (a basic and old Microsoft one), and I'm still at 100% currently without issues fyi

**Comment by PsYchitOut** [comment]
Wow that was an embarrassingly simple fix.I have my display scaling for windows is set to 125 because at 100 the icons are way to small on my display. I roll it back and sure enough problem solved. Also by following Mateos81 suggestion and overriding the high dpi settings to run on the application settings in the compatibility tab lets the game run fine without having to manually change my settings. Thanks for the help guys.

**Comment by Mateos81** [comment]
If you want to increase the icons' size of the desktop, when you're on it, you can do a zoom with CTRL + Zoom in with the mouse scroll btw

**Comment by MAN-AT-ARMS** [comment]
Notes:

Display aspect: 1.778
**...setting mode 17: 1024 576**
Using 24 color bits, 24 depth, 0 stencil display.
Available modes: '1280x720 1366x768 1600x900 1920x1080 1360x768 1280x768 320x200 640x400 1280x800 1440x900 1680x1050 1280x600 320x240 400x300 512x384 640x480 800x600 1024x768 1152x864 1280x960 1400x1050 1280x1024'

This mode isn't supported by your monitor/screen. See available modes list.

**Display aspect: 1.778
...setting mode 14: 800 450**

This one isn't either.

**Display aspect: 1.778
...setting mode -2: 1536 864**

This appears to be the native resolution of your screen....not 1920x1080.

Also:
Trying to load "OpenAL32.dll"...
Allocated 128 sources.
OpenAL default capture device is 'Microphone (Realtek High Defini'
OpenAL capture device opened.
OpenAL info:
Vendor: Creative Labs Inc.
Version: 1.1

It shouldn't be loading this ancient version. It should be using the OpenAL64.dll file included in the release zip file.
(Which is OpenAL Soft 1.17.2)

I would recommend uninstalling that old version.

**Comment by ensiform** [comment]
It's due to the text/apps scale.  Adjusting the scale affects window sizes especially of DPI unaware windows.  You won't even get the right resolution by "checking" for desktop res in code without proper awareness of DPI.

**Comment by MrUnbecoming** [comment]
@PsYchitOut 
By the way, I found out the (potential) fix to this when combing through one of my favorite sites PCGamingWiki. If you follow this link and go all the way to the bottom, you can see that there is a problem eerily similar to what you described, fixed at the bottom.

https://pcgamingwiki.com/wiki/Return_to_Castle_Wolfenstein

"Increasing the game resolution above 800x600 causes the upper left corner of the game to take up the entire screen. One reason is that game detects a 3dfx driver (possibly caused by nGlide"

Edit wolfconfig.cfg
Go to the configuration file(s) location.
Open wolfconfig.cfg.
Change seta r_glIgnoreWicked3D "0" to seta r_glIgnoreWicked3D "1"

That sounds like the problem you're having, but maybe not.

**Comment by MrUnbecoming** [comment]
well that site is really useful, and it's how I found the source port in the first place. I have no idea what the fix would be, just figured I'd throw in my 2 cents while waiting for replies on my own issue ehe. Yes the cards are old, but nGlide (a wrapper that is often installed to run some old games) can also be recognized as an old card, even if the card actually installed is modern. So if that setting is on 0, it could be detecting an nGlide installation (or similar 3DFX and voodoo wrappers) and using that erroneously.

**Comment by ensiform** [comment]
The cvar is unlikely to be supported though with the switch to SDL for GL and platform handling. I'm sure @MAN-AT-ARMS would know for sure.

**Comment by zturtleman** [comment]
The cvar `r_glIgnoreWicked3D` exists but does nothing in RTCW GPL source code and iortcw.

To workaround issues caused by DPI scaling over 100%: Right click the iowolfsp.x86.exe -> properties -> compatibility tab -> check the box for disable display scaling for high dpi settings. This will be required for all fullscreen games released before Windows Vista and many after that.

This will not be required for iortcw after the next release due to it [disabling DPI scaling automatically](https://github.com/iortcw/iortcw/commit/0f779e8dec5eddf608980ad3ebe666b6e7c2700e).
