### ISSUE TITLE
Changing graphics quality presets produces errors when setting the renderer

### ISSUE THREAD

**Issue by skgucek** [iortcw/iortcw#33]
Going into Options\System\Graphics and changing the Graphics preset produces a yellow error box with the following messages (depends on the preset):

Error: Restricted source tried to set "cl_renderer" to "rend2"
Error: Restricted source tried to set "cl_renderer" to "opengl1"

Does not crash the game, just returns to the main menu. I can set the renderer manually via console, just the settings don't really work as intended. :-(

**Comment by MAN-AT-ARMS** [comment]
Ah yes...caused by the changes in cl_main.c as part of b6ff2bc.

Reverted that change in b27e0ff

Thanks

**Comment by skgucek** [comment]
I can confirm it's now fixed and changing graphics presets works as intendended, thanks! :-)

I have a couple of other suggestions (I registered just to post this bug) and I'm just going to post them here for your consideration:

a) By default (without a present wolfconfig.cfg) the game reverts to Recommended preset with 640x480 windowed resolution. That was a good idea back in 2001, but perhaps it's time to move on and default to High Quality preset with Automatic (native) fullscreen resolution?
b) Compiling on Win64 w/ cygwin mingw seems to produce a bunch of intermediary .d, .o and .asm files in the output directory in addition to the "real" output files (.exe, .dll and .qvm). Would adding "-pipe" to cflags get rid of this behavior or is there another way to clean the output directory of these temporary compilation files? Or is there another way to clean up output after compilation? Currently ouput produces over 1000 files, while in reality there are only 8-11 "real" ones there.
c) **_(This is not a simple fix, but a serious addition, just for your consideration in the future)_** rend2 as per the included rend2-readme.md contains many cvar settings, but currently you have to set them through console. At least r_ext_framebuffer_multisample, r_parallaxMapping, r_imageUpsample, r_imageUpsampleType, r_shadowFilter, r_shadowMapSize are the ones I played around to make the game look even better. Perhaps it's time to implement some kind of advanced renderer settings in the main menu itself?

Anyway, thanks for your support and keep up the good work! 👍

**Comment by MAN-AT-ARMS** [comment]
a) That is true, but it is also contained in a config file contained inside of a pk3. Also 640x480 windowed mode is sort of an ideal fall back since it will wok on basically any hardware or platform.
b) That's normal. The object files are what are linked together to make the exe's etc. That's not going to change.
c) The menu files inside of the pk3's are not part of the open source license so I don't believe it is permitted to modify / distribute them. I might toy with creating a new menu system for the newer rendering system but it would have to be loaded via game code. Aside from that, the cvars associated with the new renderer are somewhat of a moving target coming in and going away, etc. The code is always in flux. Maybe once it settles down I'll add something like that in the form of a rend2 related pk3 file but it's not high priority.

**Comment by skgucek** [comment]
Okay, thanks for your explanations. You're the dev, I was just suggesting, It's already great as it is. However, upon playtesting, I have new problems:

1. I compiled both win32 and win64 builds as per your Windows instructions, put all .exe and .dll files into the same folder with pk3 files in main.
2. Launched game without any config (wolfconfig.cfg) in 64-bit and set quality to High Quality with Native resolution. Didn't toy around with anything else (like rend2).
3. Started a new game, played through the first level (escape1) and saved right at the beginning of the second (escape2).
4. Launched the game in 32-bit and the game would not load the saved file, throws a yellow error box:
ReadField: function name is greater than buffer (512 chars)
+
5. Started a new game (in 32-bit), played through escape1, saved at the beginning of escape2. Loaded up 64-bit and tried loading the 32-bit savegame and it throws the same error or even crashes outright!

== Currently the saves are somehow made incompatible between different builds, is that the intended behaviour?

Attaching a picture of the error and both savegames. I'm posting here not to clutter up the issue tracked, but if you want I can start a new issue ...

![error](https://user-images.githubusercontent.com/29600564/27406722-1a68e66c-56d6-11e7-9e0f-e3e19e6aafbf.jpg)
[saves.zip](https://github.com/iortcw/iortcw/files/1092917/saves.zip)

**Comment by MAN-AT-ARMS** [comment]
You can't load 64 bit saves in 32-bit or vice versa.

**Comment by skgucek** [comment]
Thanks for your support, I apologise for forgetting to close the issue.

**Comment by MAN-AT-ARMS** [comment]
No problem. It's actually an embarrassing oversight on my part. I'll probably put out an updated release in short order because of it. Thanks
