### ISSUE TITLE
Kicking impossible because of OpenAL update

### ISSUE THREAD

**Issue by uzyfeo** [iortcw/iortcw#34]
I don't know why and how OpenAL causes this exactly, but whenever I press G key (kicking) I can't kick.

This issue was not present in 1.51 and when I tried to track it down in latest source here, I found out there is something wrong with updated OpenAL library, as when I replaced new OpenAL DLL in my build folder with the old one from 1.51, I was suddenly able to kick!

I tried it many times, it is easily reproducible.

NOTE: It could be caused by some GCC optimization, as I found out the bug is not present at all when using Debug build instead of Release one. But it is still somehow tied up to OpenAL, as I tried to build the working version 1.51 myself (to see if it is not some issue with the compiler...) and everything works fine even with all optimizations.

I'm using MSYS2's MinGW32 32bit compiler with COMPILE_ARCH=x86 to generate 32bit executables.

**Comment by MAN-AT-ARMS** [comment]
I'll test it...

**Comment by uzyfeo** [comment]
Just a little update.

Whatever is causing the issue, when i recompile OpenAL with MSVC2017 (I can't build it with my MinGW for some reason...) and copy latest compiled DLL to build directory, it works again.

Seems that whatever issue it was, it was fixed in the meantime in latest OpenAL's code base.

**Comment by MAN-AT-ARMS** [comment]
Yeah..I was just able to reproduce it..it only affects Windows...weird.
I'm going to revert it to 1.17.2 for the time being. There are other issues I noticed with it as well that don't manifest themselves in RTCW though.

**Comment by MAN-AT-ARMS** [comment]
Revert to 1.17.2 in 35a8e23

**Comment by uzyfeo** [comment]
Yep, I think it will be better for time being too.
I see that you have already done that, so I'll mark this as closed.
