### ISSUE TITLE
Graphical glitch when loading and ingame menu shown

### ISSUE THREAD

**Issue by uzyfeo** [iortcw/iortcw#35]
I recorded it here so you can see what I mean...
https://www.youtube.com/watch?v=GlXHlE80SQI

It happens when I load a game and quickly press ESC to open ingame menu.
I would fix it myself but I don't really know where to look at (just getting familiarized with the source...)

I'm suspecting some buffer not getting cleared properly.

It happens with both renderering backends, opengl1 and rend2.

NOTE: I would suggest blocking opening of ingame menu during load, as it seems kind of 'not efficient' to do so anyway, and it would also get rid of a bug in a way too. But it is just a suggestion.

**Comment by uzyfeo** [comment]
OK, I have fixed the issue as I have described in my note by adding following snippet into beginning of UIMENU_INGAME case in function void _UI_SetActiveMenu( uiMenuCommand_t  ) in ui/ui_main.c

`if (trap_Cvar_VariableValue("savegame_loading"))
				return;`

This ensures that when we are loading, we will be not allowed to open ingame menu.

**Comment by uzyfeo** [comment]
Last comment...
You can see what I have done here: https://github.com/Feldarian/RTCW-FPD/blob/3a6dca04292881fdbd109ef0bd630d57e99c34c8/SP/code/ui/ui_main.c#L7079

I don't know how to do pull request properly so if you want you can incorporate similiar fix yourself :)
It basically disallows use of ingame menu during load.

**Comment by MAN-AT-ARMS** [comment]
Fix merged in 16d4690.

You're the weird bug finder of the day!

**Comment by uzyfeo** [comment]
Heh, I have few more up my sleeve :P

I just want to see if I can figure out how to fix them myself first and then share my knowledge, basically as with previous two here :)

**Comment by uzyfeo** [comment]
Marking issue as solved
