### ISSUE TITLE
pk3 checksum problem

### ISSUE THREAD

**Issue by Corwin616** [iortcw/iortcw#36]
i have russian pack of game with addons: 
**Return To Castle Wolfenstein** (just original game with russian lang) 
game/tye/sp_pak8.pk3 4361abed69e586e055c48d15fe4655445870cd76 SHA1
game/main/pak0.pk3 069fa3c0476402452d8b639af6e5eb10d2368df0 SHA1
**Operation Trondheim 1 - Special Forces**
game/trond/sp_pak8.pk3 5ec44a614662618e67fd8f28deb3cc315dc41edf SHA1
**Operation Trondheim 2 - Red Alert**
game/redalert/sp_pak8.pk3 0a2e6cf7daea7d46dde6675eeac6a173d37504e4 SHA1
**Operation Trondheim 3 - Iron Cross**
game/ironcross/sp_pak8.pk3 cb736368de51b13f4b769e703594496260e643b5 SHA1
**Return To Castle Wolfenstein - Project 51**
game/p51/sp_pak8.pk3 caafaa78b9daade64aa8ba052483d4bce2d02cec SHA1
**Return To Castle Wolfenstein - Time Gate**
game/gate/sp_pak8.pk3 e942a54bdedb7d751cfcce2d8432fa417f8c42ce SHA1
**Return To Castle Wolfenstein - Stalingrad**
game/stalingrad/sp_pak8.pk3 900398d91dfc9f117a5aace96b6a35eaed1f282c SHA1

**Return To Castle Wolfenstein - Saboteur**
game/main/pak0.pk3 153f5afe2641960b8c76463dbddb95765bb088d3 SHA1

**Return To Castle Wolfenstein - The Curse of the Pharaohs**

and cant run any of this becouse iortcw want only original english version
how to torn off checksum?

**Comment by a-detiste** [comment]
Hi, where can those be found ?

**Comment by Corwin616** [comment]
here http://rutor.info/torrent/32109/return-to-castle-wolfenstein-antologija-2001-2006-pc

**Comment by Corwin616** [comment]
**The Curse of the Pharaohs** also have not big pk3 files in Main folder

**Comment by uzyfeo** [comment]
Well don't pirate it. Problem solved ;)

**Comment by Corwin616** [comment]
@uzyfeo To calm your conscience I bought a game in Steam for a long time ago

**Comment by uzyfeo** [comment]
Well why don't use that instead?
This is not an error but security measures, they should not be bypassed.

**Comment by Corwin616** [comment]
@uzyfeo Because I want to play russian version

**Comment by uzyfeo** [comment]
If you really have the game on Steam, what you can do is use that pk3s instead and use these pk3s that the iortcw don't want to load with little different name (sp_pak08.pk3 becomes sp_pak09.pk3 etc.)

That way, iortcw will be happy that all game files are correct and you will have russian ingame :)
This is not optimal in any way but should work as a temporary workaround.

About the mods - I don't know if these can be applied to them, but they should work as-is, as they are not main game files so theyshould not fall under the checksum validation.

**Comment by uzyfeo** [comment]
Or more optimal thing you can do is extract all pakX.pk3 files to some folder in their alphabetical order, overwritting files that are there (this is what game is basically doing when it is loading files).
Pack folder "fonts" into some pakXXX,zip archive (you can actually use letters instead of numbers, this file name in example will surely be loaded last) and lastly, change .zip to .pk3

Do the same with sp_pakX.pk3 files to some clean directory and from here you only want folders "text" and "ui". Again, pack these two folders to sp_pakXXX.zip archive and change extension to .pk3

Now you can use these files on top of Steam version to get Russian translation.

This is the right way I would say :)

**Comment by uzyfeo** [comment]
@Corwin616 Btw, sorry for kind of stupid comment with that pirate version thing... But you know - wanting help with pirated version is like asking a refund from shop for stolen goodies :P

**Comment by Corwin616** [comment]
@uzyfeo russian version contains not only text, but also audio dialogs, textures and videos

**Comment by uzyfeo** [comment]
Hmm, ok lets start with these first :)

We were doing Czech translation, along with voice over so I can give you all folder names and locations, just a second

**Comment by Corwin616** [comment]
@uzyfeo Why do need these crutches? If I do this, then others do not. 
Problem in ioRTCW, not in game. Need to disable checksum checks

**Comment by uzyfeo** [comment]
Ok, so from sp_pakX.pk3 files, you also want "sound/player" and "sound/scenaric" folders and "video" folder then.

For the textures, I don't know which are English and which not (we were not doing them...) but in both of these .pk3s (pakX.pk3 and sp_pakX.pk3) are textures folders.
Just extract them and put them in new archive as with others.

So to sum this up: 
- get "fonts" and "textures" from pakX.pk3 archives and pack them to new one.
- get "sound/player", "sound/scenaric", "text", "textures" and "ui" from sp_pakX.pk3 archives and pack them to new one.

**Comment by uzyfeo** [comment]
Well because they are security measures as I stated.

You can always make a fork and remove them yourself if you really want that. I don't know if they get removed here honestly.

**Comment by Corwin616** [comment]
Thanks, I'll try.
By the way in Russia and the CIS countries the game was sold in Russian. There were at least 6 different translations of the game: http://zoneland.ru/forum/viewtopic.php?p=2679834#2679834

**Comment by uzyfeo** [comment]
Hmm, interesting.

I'll have a look at it and maybe add it to my repo (it is base iortcw anyways for the most part) but I'm definitely not going to download torrents because of it...

Had too many troubles with them in the past, never trusting them again :/

**Comment by Corwin616** [comment]
i haven't

**Comment by MAN-AT-ARMS** [comment]
You can comment out lines 4260 and 4298 in qcommon/files.c.

https://github.com/iortcw/iortcw/blob/master/SP/code/qcommon/files.c#L4260
https://github.com/iortcw/iortcw/blob/master/SP/code/qcommon/files.c#L4298

I won't be supporting 3rd party/user modified pak files. Those Russian versions are not official releases and will not be supported in this project.

**Comment by f1ames0ff** [comment]
> here http://rutor.info/torrent/32109/return-to-castle-wolfenstein-antologija-2001-2006-pc

>  (Computer Science) Pirated Copy - informal illegally copied computer software which has had its protection codes de-activated

If you're downloading copy from anywhere and the rule above is not broken - it is not pirating.

**Comment by OpenA** [comment]
why you do not just add something like
DISABLE_CHECKSUM=1
in makefile script?
