### ISSUE TITLE
Help with Punk Buster

### ISSUE THREAD

**Issue by 3371-Alpha** [iortcw/iortcw#37]
I've found various guides for fixing the Punk Buster issue, but the problem is I'm on Mac and all the guides are for Windows. The best example for this I have is this: http://steamcommunity.com/app/9010/discussions/0/846960628224537824/
Does ioRtCW work around this issue or does it require PB?

Also, in an unrelated request, do you think you could add support for the standalone multiplayer expansion, Enemy Territory? It's a bit of a pain to switch between what is essentially the same game.

**Comment by Mateos81** [comment]
AFAIK, PunkBuster being a proprietary software, any source rework can't include it?

**Comment by MAN-AT-ARMS** [comment]
The Punkbuster code was not part of the source release and as such iortcw does not support it.

You can however obtain the latest files Punkbuster files for Windows/Mac/Linux as part of the 1.41 patch data in the downloads section. (For use with the vanilla RTCW client) Just copy the pb folder into your RTCW installation folder.

**Comment by 3371-Alpha** [comment]
Hmm, so I can't play on PB enabled servers then. That's a bit of a shame. How'd they achieve PB fixes in this project I wonder: http://www.s4ndmod.com/wordpress/ ?

Also, I know it's not your responsibility but ET:L seams to have hit a snag. There latest binaries are from a year ago and there wiki ("development blog") seams to be down.

**Comment by Mateos81** [comment]
These packages just usually contains the latest files, while PB on first game launch is supposed to grab its updates; since RtCW and ET are no longer supported by PB, the official website do no longer send updates to clients, even not the latest they had

**Comment by MAN-AT-ARMS** [comment]
You can play on Punkbuster enabled servers but only with the regular RTCW client and not with iortcw.
I have no idea where etlegacy is in terms of releases. I don't really follow it anymore.

Maybe try adding an issue to their github with whatever the snag is.
https://github.com/etlegacy/etlegacy

**Comment by Mateos81** [comment]
If you google 'etlegacy' you'll find the officiel website up and running as always...
You can follow the activity there btw
