### ISSUE TITLE
Checksum error when attempting to change crosshair in pak0

### ISSUE THREAD

**Issue by LethalManBoob** [iortcw/iortcw#39]
iortcw 1.51b-SP win_mingw64-x64 Aug 16 2017
SSE instruction set enabled
----- FS_Startup -----
Current search path:
C:\Users\upton\Documents\RTCW\main
D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein\main\sp_rend2_shaders0.pk3 (5 files)
D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein\main\sp_pak4.pk3 (21 files)
D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein\main\sp_pak3.pk3 (14 files)
D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein\main\sp_pak2.pk3 (232 files)
D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein\main\sp_pak1.pk3 (1342 files)
D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein\main\pak0.pk3 (4775 files)
D:\SteamLibrary\steamapps\common\Return to Castle Wolfenstein\main
c:/program files (x86)/steam\SteamApps\common\Return To Castle Wolfenstein\main

----------------------
6389 files in pk3 files

**************************************************
WARNING: main/pak0.pk3 is present but its checksum (1349421837)
is not correct. Please re-copy pak0.pk3 from your
legitimate RTCW CDROM.
**************************************************

The normal exe works fine.

**Comment by LethalManBoob** [comment]
Okay so I had a thought about it. Maybe its becuause I used an earlier version of iortcw?

**Comment by MAN-AT-ARMS** [comment]
Either your pak0.pk3 is modified or it's corrupt.
In any case, the checksum doesn't match what it should be from a legitimate source.

**Comment by LethalManBoob** [comment]
I took out a crosshairh file and put it in the pak0 file. The regular game works fine though. just the iowol.exe has the issue. So is it that the mod cannot handle modified base pak files?

**Comment by MAN-AT-ARMS** [comment]
That's not how you modify assets. You put them in a seperate pk3 that contains the same path and filename as the original.

**Comment by LethalManBoob** [comment]
How does one do that? But its so odd that it used to work for me.

**Comment by uzyfeo** [comment]
Yo can find how in #36 I wrote it there in one comment

**Comment by LethalManBoob** [comment]
Works perfectly. Thanks for that. :)

**Comment by uzyfeo** [comment]
@LethalManBoob You can close the thread if the issue was resolved :P

**Comment by LethalManBoob** [comment]
Thanks I forgot ;)
