### ISSUE TITLE
Custom FOV

### ISSUE THREAD

**Issue by Keith94** [iortcw/iortcw#40]
How can I properly set a custom FOV value in single-player?

Firstly, I use `cg_fixedAspect "2"` to play in widescreen.

Secondly, I tried using `seta cg_fov "120"` in the configuration file. FOV stays locked at 90(?). I entered `cg_fov 120` in the console. Does nothing. Actually all cvars I enter in the console seems to do nothing.

I think you should be allowed to increase the FOV while still getting proper scaling provided by the fixedAspect (unless there's another way to do it). I appreciate any support.

**Comment by LobsterGizzard** [comment]
which game.

**Comment by Keith94** [comment]
`cg_fov` won't work if using `cg_fixedAspect "1"` or `"2"`, though.

**Comment by LobsterGizzard** [comment]
ok that didn't seem to work for me either, but here's how i got widescreen fov to work for me. here's the cfg i wrote. https://retropwned.com/2017/11/04/return-to-castle-wolfenstein-autoexec-cfg/ let me know if you can understand where i made the necc changes.

**Comment by Keith94** [comment]
It doesn't help for using a **_custom_** FOV. But thanks.

My "simple" suggestion is the developer could add an additional value: `cg_fixedAspect "3"` which uses aspect corrected HUD/UI but does not affect the FOV, so we can use custom `cg_fov` to our liking.

**Comment by LobsterGizzard** [comment]
works fine for me. i have widescreen and fov 100, np.

**Comment by MAN-AT-ARMS** [comment]
Added cvar for this: cg_fixedAspectFOV
Set to 0 to use custom cg_fov

https://github.com/iortcw/iortcw/commit/44a3ceaa7c8c8ed23e5d8ab60a91b4a8c75928af

**Comment by Keith94** [comment]
@MAN-AT-ARMS You are awesome, thank you for the fix. 👍 

Could you attach a new build so I can try it out? I use win x64.

**Comment by MAN-AT-ARMS** [comment]
http://beach.ecgnetwork.co/iortcw/iortcw-SP-11212017-win64.zip

**Comment by Keith94** [comment]
Cool, it's working great so far.
How can I remove the flashing "Connection interrupted" text on screen?

**Comment by MAN-AT-ARMS** [comment]
Nothing with this change would have caused that. Try a fresh config.
