### ISSUE TITLE
64-bit Windows build not loading correct OpenAl dll

### ISSUE THREAD

**Issue by uzyfeo** [iortcw/iortcw#41]
On 64-bit Windows build, when I open console, iortcw tries to load OpenAl32.dll, but there's none in the game folder so it loads the one stored in System32.

Renaming OpenAl64.dll in game folder to OpenAl32.dll seems to do the work for now but it should definitely be dealt with somehow.

I see two solutions:
- renaming OpenAl64.dll to OpenAl32.dll inside libs
- do some checking inside code

**Comment by MAN-AT-ARMS** [comment]
It is checked in code. It's designed to use "OpenAL64.dll" on 64-bit.

The dll's are located in code/libs/win64 and code/libs/win32. This is to allow both 32 and 64 bit builds to coexist in the same directory.

**Comment by uzyfeo** [comment]
Yep, I saw it yesterday when I was searching for the place where some fix for this should be but it somehow doesn't work.

As I said, it tries to load OpenAl32.dll for some reason. It can be clearly seen in console that it loads default Creative lib in System32.

I can post screensshots and logs when I come home if it is needed.

If your question would be what's my system and compiler, I answered this in other issue.

**Comment by uzyfeo** [comment]
Funny thing is that I was compiling source without issues somewhen at fall last year.

I don't know if there were some changes made to Makefiles or there was some error-prone code pushed to Windows repo of GNU toolset but that doesn't change the issues at hand...

**Comment by MAN-AT-ARMS** [comment]
The ancient Creative Labs Open AL build isn't recommended and not really supported anymore. OpenAL-Soft is what is used now.

Side note:
Try using /seta s_alDriver "OpenAL64.dll"

The dll should be placed in the same directory as the .exe file.

**Comment by uzyfeo** [comment]
I know that and just to be sure I downloaded the latest release here and replaced all files in folder with my compiled ones so everything should be in their rightful place.

BTW, this issue is in the latest release from you too.
Try to check the console, you'll see what I mean.

**Comment by MAN-AT-ARMS** [comment]
I'm not seeing the same thing as you.

**Comment by uzyfeo** [comment]
www.youtube.com/watch?v=NpST7Jiwo7E

There I show before and after. As you can see, there seems to be some kind of issue and I really can't believe it would be on my system only.

**Comment by uzyfeo** [comment]
And forgot about the command...
The command works in persuading the game to load OpenAL64.dll instead of OpenAL32.

**Comment by MAN-AT-ARMS** [comment]
I committed a change to try and load OpenAL64.dll first.
It was finding the OpenAL32.dll in your system folder and so didn't use the OpenAL64.dll in the directory.

Try rebuilding and let me know how you make out.

**Comment by uzyfeo** [comment]
Works flawlessly now.
