### ISSUE TITLE
Makefile DO_REF_STR sed expression escaping issue

### ISSUE THREAD

**Issue by uzyfeo** [iortcw/iortcw#42]
The DO_REF_STR in your Makefile looks like this

```
define DO_REF_STR
$(echo_cmd) "REF_STR $<"
$(Q)rm -f $@
$(Q)echo "const char *fallbackShader_$(notdir $(basename $<)) =" >> $@
$(Q)cat $< | sed -e 's/^/\"/;s/$$/\\n\"/' | tr -d '\r' >> $@
$(Q)echo ";" >> $@
endef
```

On my system, this puts literal newline character before end quote, resulting to corrupted .c files being generated.
My solution to this issue was to modify the part with sed to 
`$(Q)cat $< | sed -e 's/^/\"/;s/$$/\\\n\"/' | tr -d '\r' >> $@`

Also, you could rewrite your sed expression as a whole to
`$(Q)cat $< | sed 's/.*/"&\\\n"/' | tr -d '\r' >> $@`

It's shorter and (at least to my eyes) more elegant, but that's up for you.

**Comment by MAN-AT-ARMS** [comment]
What system are you using?

**Comment by uzyfeo** [comment]
Windows 10 64bit with MSYS2's MinGW-w64 64bit compiler and libs...

I don't know why mingw32-make of this is behaving like this but this helps and doesn't actually break anything as far as I'm concerned.

Oh, and I can't build MP at all. Dies on DO_CGAME_something (forgot what it is...) on Q3LCC. It apparently cannot find q3cpp.exe...

When I let make print the commands and execute them manually through shell, they work.
So it is probably some bug with make, I can't really tell...

**Comment by MAN-AT-ARMS** [comment]
What's the command you're using to build?
Did you use the vanilla MSYS2 installer? I'll try and test it.

I usually use cygwin's Mingw-W64 for the Windows builds. ...
https://github.com/iortcw/iortcw/blob/master/HOWTO-Build.txt

**Comment by uzyfeo** [comment]
Yep, vanilla MSYS2 64bit instalation and then downloaded mingw-w64-x86_64-gcc, ...

Nothing else.

**Comment by MAN-AT-ARMS** [comment]
Both MP and SP build correctly for me under MSYS2.

**Comment by uzyfeo** [comment]
This is really strange...
I have fresh install of Windows, its literally week old. I don't think there should be issues on SW front?

**Comment by uzyfeo** [comment]
Wait did you build with make or mingw32-make?
MSYS2 has kind of weird packaging system. 

pacman -Syu make =\= pacman -Syu mingw-w64-x86_64-make
etc. 

Just to be sure...

I looked at what specific packages I had installed and these are the ones that make my toolchain up.
mingw-w64-x86_64-binutils
mingw-w64-x86_64-gcc
mingw-w64-x86_64-gdb
mingw-w64-x86_64-make

I'm compiling using this one make, it is called by mingw32-make and not make.

**Comment by MAN-AT-ARMS** [comment]
I just did a regular msys2 install.
Installed git
Installed mingw-w64-x86_64-gcc
Installed make
Installed bison

ARCH=x86_64 make

**Comment by uzyfeo** [comment]
Well maybe the make I'm using is broken. You probably used the latter one and therefore different one.
I'll try to install msys's make too and see if it changes anything.

**Comment by uzyfeo** [comment]
Ok mingw32-make is broken.
make from msys works so issue solved?
