### ISSUE TITLE
Unable to launch on 16.04 how to debug ?

### ISSUE THREAD

**Issue by masenocturnal** [iortcw/iortcw#43]
Hi I have purchased the most recent version of RTCW from GOG and installed it in a windows 7 VM. 
I've downloaded the latest release of IORTCW for 64bit linux and copied over the Main directory from the the installed RTCW to the IORTCW directory. 

Upon executing ./iowolfsp.x86_64  I get the following in the crashlog.

> 
> am@seattle:~/Downloads/iortcw-1.51b-linux-x86_64$ cat /home/am/.wolf/main/crashlog.txt                                        
> iortcw 1.51b-SP linux-x86_64 Aug 16 2017
> SSE instruction set enabled
> ----- FS_Startup -----
> Current search path:
> /home/am/.wolf/main
> ./main/sp_pak4.pk3 (21 files)
> ./main/sp_pak3.pk3 (14 files)
> ./main/sp_pak2.pk3 (232 files)
> ./main/sp_pak1.pk3 (1342 files)
> ./main/pak0.pk3 (4775 files)
> ./main
> 
> ----------------------
> 6384 files in pk3 files
> execing default.cfg
> execing wolfconfig.cfg
> execing autoexec.cfg
> Minimum com_hunkMegs is 128, allocating 128 megs.
> Hunk_Clear: reset the hunk ok
> Bypassing CD checks
> ----- Client Initialization -----
> Couldn't read rtcwhistory.
> Cmd_AddCommand: map_restart already defined
> ----- Initializing Renderer ----
> Trying to load "renderer_sp_opengl1_x86_64.so" from "."...
> ---- Renderer Initialization Complete ----
> RTCWKEY found.
> ----- Client Initialization Complete -----
> ----- R_Init -----
> SDL using driver "x11"
> Initializing OpenGL display
> Display aspect: 1.778
> ...setting mode 3: 640 480
> Using 24 color bits, 24 depth, 8 stencil display.
> Available modes: '1920x1080 720x400 1280x800 1440x900 640x480 800x600 1024x768 1152x864 1280x1024'
> GL_RENDERER: Mesa DRI Intel(R) Ivybridge Desktop 
> Initializing OpenGL extensions
> ...using GL_EXT_texture_compression_s3tc
> ...using GL_EXT_texture_env_add
> ...using GL_ARB_multitexture
> ...using GL_EXT_compiled_vertex_array
> ...ignoring GL_EXT_texture_filter_anisotropic
> Initializing Shaders
> ^3WARNING: In shader file scripts/common.shader...Shader "textures/sfx/portal3a_back2" on line 822 is missing closing brace^3.
> ^3WARNING: In shader file scripts/ui_wolf.shader...Invalid shader name "}" on line 1849.
> ----- finished R_Init -----
> ------ Initializing Sound ------
> Trying to load "libopenal.so.1"...
> Allocated 128 sources.
> OpenAL default capture device is 'Built-in Audio Analogue Stereo'
> OpenAL capture device opened.
> OpenAL info:
>   Vendor:         OpenAL Community
>   Version:        1.1 ALSOFT 1.16.0
>   Renderer:       OpenAL Soft
>   AL Extensions:  AL_EXT_ALAW AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length
>   ALC Extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFTX_device_clock ALC_SOFTX_HRTF ALC_SOFT_loopback ALC_SOFTX_midi_interface ALC_SOFT_pause_device
>   Device:         Built-in Audio Analogue Stereo
>   Available Devices:
> Built-in Audio Analogue Stereo
>   Input Device:   Built-in Audio Analogue Stereo
>   Available Input Devices:
> Built-in Audio Analogue Stereo
> Monitor of Built-in Audio Analogue Stereo
> Sound initialization successful.
> --------------------------------
> ----- Client Shutdown (Client fatal crashed: VM_Create on UI failed) -----
> RE_Shutdown( 1 )
> Hunk_Clear: reset the hunk ok
> OpenAL capture device closed.
> -----------------------
> VM_Create on UI failed
> 
> 
> 

Can you please advise me on how I can debug this further. 

thanks in advance

**Comment by MAN-AT-ARMS** [comment]
Make sure you have the cgame, qagame, and ui .so files in your main folder.

**Comment by masenocturnal** [comment]
Hi @MAN-AT-ARMS ,
Thanks for such a quick reply. I have copied the folder over wholesale from the version which has been installed in windows and there are cgame, qagame and ui .dll's in the directory (as supplied from the windows install) however these appear to be named slightly differently. e.g qagame_mp_x86.dll 

```
am@seattle:~/Downloads/iortcw-1.51b-linux-x86_64/main$ ls -la
total 768076
drwxrwxr-x 3 am am      4096 Apr  7 14:08 .
drwxrwxr-x 4 am am      4096 Apr  7 14:08 ..
-rw-rw-r-- 1 am am        12 Apr  7 13:30 autoexec.cfg
-rw-rw-r-- 1 am am    589824 Apr  7 13:30 cgame_mp_x86.dll
-rw-r----- 1 am am      3510 Apr  7 14:09 crashlog.txt
-rw-rw-r-- 1 am am       812 Apr  7 13:30 hunkusage.dat
-rw-rw-r-- 1 am am         5 Apr  7 14:09 iowolfsp.pid
-rw-rw-r-- 1 am am    760207 Apr  7 13:30 mp_bin.pk3
-rw-rw-r-- 1 am am  63211149 Apr  7 13:30 mp_pak0.pk3
-rw-rw-r-- 1 am am   4449596 Apr  7 13:30 mp_pak1.pk3
-rw-rw-r-- 1 am am      1118 Apr  7 13:30 mp_pak2.pk3
-rw-rw-r-- 1 am am    159762 Apr  7 13:30 mp_pak3.pk3
-rw-rw-r-- 1 am am      7799 Apr  7 13:30 mp_pak4.pk3
-rw-rw-r-- 1 am am    167075 Apr  7 13:30 mp_pak5.pk3
-rw-rw-r-- 1 am am   3485134 Apr  7 13:30 mp_pakmaps0.pk3
-rw-rw-r-- 1 am am   3765933 Apr  7 13:30 mp_pakmaps1.pk3
-rw-rw-r-- 1 am am   7408542 Apr  7 13:30 mp_pakmaps2.pk3
-rw-rw-r-- 1 am am  10780146 Apr  7 13:30 mp_pakmaps3.pk3
-rw-rw-r-- 1 am am  24171802 Apr  7 13:30 mp_pakmaps4.pk3
-rw-rw-r-- 1 am am  20024689 Apr  7 13:30 mp_pakmaps5.pk3
-rw-rw-r-- 1 am am  10080181 Apr  7 13:30 mp_pakmaps6.pk3
-rw-rw-r-- 1 am am 315823656 Apr  7 13:30 pak0.pk3
-rw-rw-r-- 1 am am    700416 Apr  7 13:30 qagame_mp_x86.dll
drwxrwxr-x 2 am am      4096 Apr  7 13:30 scripts
-rw-rw-r-- 1 am am 293887431 Apr  7 13:30 sp_pak1.pk3
-rw-rw-r-- 1 am am  11026123 Apr  7 13:30 sp_pak2.pk3
-rw-rw-r-- 1 am am    152544 Apr  7 13:30 sp_pak3.pk3
-rw-rw-r-- 1 am am  15532040 Apr  7 13:30 sp_pak4.pk3
-rw-rw-r-- 1 am am    245760 Apr  7 13:30 ui_mp_x86.dll
-rw-rw-r-- 1 am am      5910 Apr  7 13:30 wolfconfig.cfg
```


Is it possible that Good Old Games has their own 'version' of the application which is different from the original CD? If so are you aware of a place that will sell me an original CD ? I wasn't able to find my original CD which is why I purchased the version from GOG.

**Comment by uzyfeo** [comment]
Just extract and overwrite everything from the archive as @MAN-AT-ARMS said.
From the list, it is obvious you didn't extract main folder from archive as you are clearly missing vm folder and needed .so files, not mentioning packaged .pk3s.

**Comment by masenocturnal** [comment]
I had originally extracted the main folder however some instructions I was following said to replace the folder with that from the installed game; which I had done. However based on what you're saying all I needed to do was just copy the contents of main in the installed application into the main folder of iortcw. 

thank you for your quick feedback.
AM

**Comment by uzyfeo** [comment]
So I assume it worked out for you then? :)
If so, mark this issue as closed 👍

**Comment by MAN-AT-ARMS** [comment]
The naming convention for single player game modules is cgame.sp.arch.so on Unix and cgame_sp_arch.dll on Windows. This is different than the vanilla ones (which do not have space in the naming)



On April 7, 2018 10:42:02 AM EDT, Andrej Redeky <notifications@github.com> wrote:
>So I assume it worked out for you then? :)
>If so, mark this issue as closed 👍 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/iortcw/iortcw/issues/43#issuecomment-379474290

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by MAN-AT-ARMS** [comment]
Closing
