### ISSUE TITLE
System menu not showing up

### ISSUE THREAD

**Issue by mathew832** [iortcw/iortcw#45]
OS: Ubuntu 18.04
GPU: AMD 280x OpenGL version string: 3.1 Mesa 18.2.0-devel
iortcw version: 1.51c-SP (compiled from source today and previous version I downloaded elsewhere, forgot where exactly)
Relevant error in console: Error: UI/hud.menu. line (multiple line numbers here): unknown menu item keyword (multiple lines with "bottomright" and "scralign"). [Relevant pic](https://imgur.com/a/jxhpZEZ). 

On the menu before game, the system menu just doesn't show and takes me back to the main screen. Apparently [someone else](https://www.gog.com/forum/wolfenstein_series/no_system_nenu_options_in_iortcw142dwinx64) had the issue also.

**Comment by MAN-AT-ARMS** [comment]
You are using a pak file from Knightmare's engine. Do a clean install with only official pk3 files.

**Comment by mathew832** [comment]
You're right. I took my pk3 files from my Steam install and it must've been years since I used it but wasn't aware I used modded files at one time. I had to replace sp_pak4.pk3 with the correct one with checksum 4223cc6588594ec0ceee186f0e73a6e9. All is well now. Thanks.

**Comment by MAN-AT-ARMS** [comment]
Good deal.
