### ISSUE TITLE
problem run at ubuntu

### ISSUE THREAD

**Issue by johndoe71rus** [iortcw/iortcw#48]
try run build at lubuntu 18.04. 
log https://paste.ubuntu.com/p/j6q9mDPBKT/

but i can run the same files set with https://github.com/id-Software/RTCW-SP (if I do not confuse) at lubuntu 14.04. The same hardware.

**Comment by MAN-AT-ARMS** [comment]
See: https://github.com/iortcw/iortcw/issues/45

**Comment by johndoe71rus** [comment]
i think situation more interesting. The same system at external hdd. But other hardware, intel.
https://paste.ubuntu.com/p/VTr59MJjwd/
 So i think something with drivers or libs.

i will try find right *.pak file

**Comment by MAN-AT-ARMS** [comment]
https://github.com/iortcw/iortcw/releases

The correct sp_pak4.pk3 is in the patch-data-141.zip file

**Comment by johndoe71rus** [comment]
remove localized pack. Now i have spanish version (i think so)
one system 18.04, one rtcw binares pack. But 2 hardwares
dell ispiron 1501 TL-56 ATI RS480
intel system with  Sandybridge integrated video
AMD https://paste.ubuntu.com/p/tXRb2dRd6S/
Intel https://paste.ubuntu.com/p/PZbXCkDZxg/

run on intel but fail on amd
