### ISSUE TITLE
Mouselook stutter during movement

### ISSUE THREAD

**Issue by Arthandas** [iortcw/iortcw#50]
There's very noticeable mouselook microstutter during movement. It's not present in vanilla game or knightmare.
Any ideas how to fix it? I'm on Win10 x64.

**Comment by MAN-AT-ARMS** [comment]
I'll be honest, I have no idea what you mean.

**Comment by WSSDude** [comment]
I noticed it too. Movement with mouse is not very smooth for some reason.

This issue is present in ioquake3 as well, so I suspect something that was merged from it is causing this.

It is even worse on my laptop. No problems with vanilla engines in this regard.

**Comment by WSSDude** [comment]
Adressed in #52

**Comment by Harry83** [comment]
Evening all,

Great work for this patch, I admire what you guys do to keep old games rocking! With regard to the above, I can also add that this is a bit of a killer. Will you guys be able to fix it in the next release?

**Comment by WSSDude** [comment]
Well it does see like they want to keep --ffast_math in so I think maybe not :/

I understand that it can be closer to vanilla, but I frankly don't understand why stand in vanilla way all the way when things can improve in a way?

Isn't that the sole purpose of open-source - stay open to new ideas and improve?

Anyway, my "patch" of source has been available, no pull request or anything happened, so... It may be a dead case unfortunately :/

**Comment by Harry83** [comment]
Aw shame, still I don't really get it - Vanilla runs fine, so in my non-programming brain, shouldn't that extend over if the vanilla theme is being kept?

I'm obviously missing something simple - I'll get my coat now lol.

**Comment by MAN-AT-ARMS** [comment]
From what I understand, removing --ffast-math causes other issues. Maybe ZTM can explain / elaborate. I think I've seen this discussion come up before elsewhere.

**Comment by KuehnhammerTobias** [comment]
@Arthandas, @WSSDude just a question, are you sure r_swapinterval is 0? I'm asking because I can't always reproduce your issue. I'm on Win10 (64-bit) and my other machine is Win8.1 (64-bit). On Win8.1 r_swapinterval works as expected (without problems), on Win10 and r_swapinterval turned on I can confirm noticeable mouselook microstutter during movement.
It seems as if Win10 with newer gfx drivers already has something like r_swapinterval (vsync) turned on. Can you please check if r_swapinteval 0 will fix your issue on Win10?

**Comment by KainXVIII** [comment]
I noticed mouselook stuttering too (r_swapinteval 0)! If you turn with keyboard all is smooth for some reason..

**Comment by Vitoria90** [comment]
Getting this pretty bad on Win10 on the latest version. r_swapinterval 0 didn't solve it.

**Comment by MAN-AT-ARMS** [comment]
I removed -ffast-math in 82e730b8901627872c8fc7e68108e6873ca204e9. If major issues arise, it may need reverted.

**Comment by SaikoDono** [comment]
this autoexec fixed stuttering for me:

com_maxfps 144
r_swapinterval 0
r_ext_multisample 0
r_ext_framebuffer_multisample 0
cl_mouseAccel 0
cg_fixedAspect 1
cl_renderer opengl2
m_filter 0
