### ISSUE TITLE
Trouble setting up Dedicated Server

### ISSUE THREAD

**Issue by LaPorta** [iortcw/iortcw#51]
Hi everyone,

I have had much success setting up an ioquake3 dedicated server on my Mac Mini Server...not so much with iortcw. Q3 starts up no issue and works fine, but I am getting some sort of error with RTCW. I will include the Terminal text from when the server starts up and automatically shuts down. Hopefully someone can give me some insight into what the issue is.

[Terminal Saved Output 2.txt](https://github.com/iortcw/iortcw/files/2216657/Terminal.Saved.Output.2.txt)

**Comment by MAN-AT-ARMS** [comment]
Would need to see what's in the config...Obviously, there is more in your config than just the defaults (a rotation, etc.)

Also, for a dedicated you probably are better off using the terminal based builds.

**Comment by LaPorta** [comment]
Sure,

I tried it two different ways: one was with pre-set configs that i slightly modified as per the guide that was posted here a while ago:

http://brian-horning.com/rtcw-server-setup-guide/

Those didn't really lead to much, so I just tried a simple, paired-down config file like the one that I use for my Q3 server (attached).

I was unaware of straight for terminal builds. I had been using the Unix exec file iowolfmp located within the package application in macOS. I'll check those out here as well.

[autoexec.txt](https://github.com/iortcw/iortcw/files/2217020/autoexec.txt)

**Comment by MAN-AT-ARMS** [comment]
set sv_pure "1"
set bot_enable "0" //no bots available
set sv_maxRate "8000" //here for safety
set com_hunkMegs "70"
seta sv_master1 "wolfmaster.s4ndmod.com"
seta sv_master2 ""
seta sv_master3 ""
seta sv_master4 ""
seta sv_master5 ""

// Wolf Specific - time in miliseconds
set g_soldierChargeTime "10000"
set g_LTChargeTime "20000"
set g_engineerChargeTime "15000"

set m01 "set g_gametype 5; map mp_assault; set nextmap vstr m02"
set m02 "map mp_base; set nextmap vstr m03"
set m03 "map mp_beach; set nextmap vstr m04"
set m04 "map mp_castle; set nextmap vstr m05"
set m05 "map mp_depot; set nextmap vstr m06"
set m06 "map mp_sub; set nextmap vstr m07"
set m07 "map mp_village; set nextmap vstr m01"

vstr m01

1. Put that in a file and name it server.cfg
2. Clear everything out of the autoexec
3. Delete your current wolfconfig_server.cfg

4. Command line:
iowolfded.<ARCH> +set dedicated 2 +set net_port 27961 +exec server.cfg

(Don't issue the vstr on the commandline)

**Comment by LaPorta** [comment]
Ok, did all of the above, and still getting something similar as in the enclosed file. Is it possible that my installation is bad somehow? Should I perform a new installation?

[error2.txt](https://github.com/iortcw/iortcw/files/2217253/error2.txt)

**Comment by LaPorta** [comment]
I also built the Unix dedicated iowolfded app, and this returned a different error when run:
[error3.txt](https://github.com/iortcw/iortcw/files/2217260/error3.txt)

**Comment by MAN-AT-ARMS** [comment]
I don't see any errors in error2.txt (Not sure why your IP is showing all 0's though)
In error3.txt your com_hunkmegs setting is too low.

**Comment by LaPorta** [comment]
I corrected the zeros by using set net_IP....but still not sure what is going on exactly. 

It gets to running and setting heartbeat, then about 10 seconds later, the same things show up:

==== ShutdownGame ====
ShutdownGame:
------------------------------------------------------------
VM_Restart()
Loading vm file vm/qagame.mp.qvm...
File "vm/qagame.mp.qvm" found at "/Applications/RTCW/main"
...which has vmMagic VM_MAGIC_VER2
Loading 3042 jump table targets
------- Game Initialization -------
gamename: main
gamedate: Aug 16 2017

I am uncertain what that means: a file was found in a wrong place? Something is the wrong version?

Also, any ideas as to why the Assault map cfg has an error?

**Comment by MAN-AT-ARMS** [comment]
That's normal

**Comment by LaPorta** [comment]
Well, ok, now that it appears to marginally run through levels and such...the issue I have is that I cannot seem to find it on the internet, nor listed as a local server on my network. Any reason why that might be?

**Comment by MAN-AT-ARMS** [comment]
If you're behind a router you;ll need to forward the appropriate ports (27950, 27961)
Also, use your local IP for the net_ip parameter on your commandline.

**Comment by LaPorta** [comment]
Success!

The whole time, at least as far as finding the server, I had two digits in my router's port mapping transposed. Now I can find and connect to it from the client. Thank you very much for your help.

Now to configure it...

**Comment by MAN-AT-ARMS** [comment]
Good to hear. Have fun.
