### ISSUE TITLE
Imprecise hit detection in release (and more...)

### ISSUE THREAD

**Issue by WSSDude** [iortcw/iortcw#52]
I noticed many of my shots didn't connect when they clearly should. Also, physics behaved weirdly, mouse felt more stuttery,... 
I found these issues was not present in the Debug build.

Looking at the Makefile -ffast-math is enabled in Release. Removing this and recompiling fixed the issues so this can clearly be attributed to this compiler flag.
> -ffast-math
>     Sets the options -fno-math-errno, -funsafe-math-optimizations, -ffinite-math-only, -fno-rounding-math, -fno-signaling-nans, -fcx-limited-range and -fexcess-precision=fast.
>    This option causes the preprocessor macro __FAST_MATH__ to be defined.
>    This option is not turned on by any -O option besides -Ofast since it can result in incorrect output for programs that depend on an exact implementation of IEEE or ISO rules/specifications for math functions. It may, however, yield faster code for programs that do not require the guarantees of these specifications.

I think it should be removed.
I didn't experience any perceptual drop in performance without it so it just adds salt into injury without helping curing it in any mandatory way.

**Comment by MAN-AT-ARMS** [comment]
Interesting find. It probably isn't needed but I'll do a little testing on it. What compiler, platform, are you using?

**Comment by WSSDude** [comment]
MSYS2's MinGW 64-bit version, compiler GNU C Compiler 8.2.0.
`gcc version 8.2.0 (Rev1, Built by MSYS2 project)`
Everything patched to latest versions.

Specs:
CPU: Ryzen 2600x (downclocked to 3.2GHz)
GPU: GTX 1050
RAM: 2x8GB DDR4 2667MHz
OS: Windows 10 (1803) 64-bit

**Comment by WSSDude** [comment]
I included modified Makefiles in #54

**Comment by MAN-AT-ARMS** [comment]
I removed -ffast-math in 82e730b8901627872c8fc7e68108e6873ca204e9. If major issues arise, I will have to revert that change.
