### ISSUE TITLE
low FPS

### ISSUE THREAD

**Issue by SebiTimeWaster** [iortcw/iortcw#64]
Hi, i have:
Ryzen 2400G
Kubuntu 18.04 with Kernel 4.18.8
2560x1440 monitor

and i have low 30 - 50 FPS. Half Life 2 runs with 60fps flat in that resolution, everything on highest.

none of the usual fixes help, r_primitives "2" does nothing.

CPU is bored to death for the most part, i cant even see a difference between running the game or not running it. 

i don't know what to do next.

**Comment by MAN-AT-ARMS** [comment]
Try a fresh config?

**Comment by WSSDude** [comment]
Try to put "cl_renderer opengl1" and "vid_restart" afterwards into console. It may help.

If low fps remains, try to put there following commands in this order:

cl_renderer rend2
r_hdr 0
r_postProcess 0
r_toneMap 0
r_autoExposure 0
r_normalMapping 0
r_specularMapping 0
r_deluxeMapping 0
vid_restart

These commands should enable newer renderer while also disabling all of its graphical additions, which could help out on newer GPUs.

**Comment by SebiTimeWaster** [comment]
no, i still have to test this.

**Comment by SebiTimeWaster** [comment]
using cl_renderer opengl1 helped, everything over 100 FPS now. but its a bummer to not use the new renderer features.

**Comment by MAN-AT-ARMS** [comment]
You sure you have hardware accelerated graphics working?

**Comment by SebiTimeWaster** [comment]
yes? is there even a software renderer?

**Comment by SebiTimeWaster** [comment]
GL_RENDERER: AMD RAVEN (DRM 3.26.0 / 4.18.12-041812-generic, LLVM 6.0.0)
