### ISSUE TITLE
launch iortcw and specify the path of the game

### ISSUE THREAD

**Issue by legluondunet** [iortcw/iortcw#66]
Hello,

it is possible to launch  iortcw and specify the path of the game in the config file or in the command line instead of copy iortcw files and folder in the game folder?

**Comment by legluondunet** [comment]
I just tried, it doesn't work:

```
$ ./iowolfsp.x86_64 +set fs_basepath /mnt/dd2/Steam/steamapps/common/Return\ to\ Castle\ Wolfenstein/
iortcw 1.51c-SP_GIT_ef829a9a-2018-11-13 linux-x86_64 Nov 26 2018
SSE instruction set enabled
----- FS_Startup -----
Current search path:
/home/legluondunet/.wolf/main
/mnt/dd2/Steam/steamapps/common/Return to Castle Wolfenstein//main
    
----------------------
0 files in pk3 files
    

"pak0.pk3" is missing. Please copy it
from your legitimate RTCW CDROM.

Also check that your iortcw executable is in
the correct place and that every file
in the "main" directory is present and readable.


tty]Gtk-Message: 23:40:04.240: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by legluondunet** [comment]
There is a Main folder in "/mnt/dd2/Steam/steamapps/common/Return to Castle Wolfenstein/" but with a M caps.

**Comment by MAN-AT-ARMS** [comment]
I would try putting the path within quotes because of the spaces.

**Comment by legluondunet** [comment]
Same result.

**Comment by legluondunet** [comment]
is iortcw case sentive when it searches for pak0.pk3 in main folder?

**Comment by MAN-AT-ARMS** [comment]
Yes, it does appear to be case sensitive.
Also, it will not be able to find the new .so (dll) files unless you copy them to that folder.

**Comment by bbarski** [comment]
until this is corrected, you can use this script

#!/bin/bash
sudo apt-get install rtcw;
export PATH=$PATH:/usr/lib/rtcw;
sudo apt-get install steamcmd;
export PATH=$PATH:/usr/games/steamcmd;
/usr/games/steamcmd +@sSteamCmdForcePlatformType windows +login yourLogin +force_install_dir ~/.wolf/ +app_update 9010 validate +quit;
sudo mv ~/.wolf/Main ~/.wolf/main
/usr/lib/rtcw/iowolfsp
