### ISSUE TITLE
Spanish version

### ISSUE THREAD

**Issue by a-detiste** [iortcw/iortcw#7]
Hi,

I've located the Spanish dub, which trigger this warning, like the french one:
```
**************************************************
WARNING: main/sp_pak1.pk3 is present but its checksum (652879493)
is not correct. Please re-copy sp_pak1.pk3 from your
legitimate RTCW CDROM.
**************************************************
```

file main/sp_pak1.pk3?es
255164624 bytes
md5= 99a26bcd4b8511f8f43576a37a7ccbdb 

The game works perfectly, even when I didn't bother to recode scrips/translastions.cfg
from a CRLF fila to a unixy one.

http://anonscm.debian.org/cgit/pkg-games/game-data-packager.git/commit/?id=06c54202670aae47a23ab97edc6df0c6458542f5

**Comment by MAN-AT-ARMS** [comment]
I wasn't aware of a Spanish dubbed one but I did order a "Special Edition" copy so I'll check if the hash matches yours. I also found an Italian dubbed one online but it doesn't seem to be an official id release.

Not sure how many different official releases there actually are, so I guess I will add hashes as they are verified.

**Comment by a-detiste** [comment]
This version has the same `/Docs/Help/Manual/RTCW_Manual_{EN|FR|GM|IT|SP}` directories with html documentation as included in my French dub; so it's likely that there exists an official Italian version too and that's all. 

For the German version, a extra file `main/sp_pakG.pk3`is provided instead of replacing `main/sp_pak1.pk3`

> they are verified

I heard from someone that GOG.com is lacking some dubs for some games they have the right to sell and requests users to provide those; tha'ts weird, it's best to always match against the original media.

> sp_pak4.pk3

Thanks for this bit of information, I'll fix the comments.

**Comment by a-detiste** [comment]
the translation.cfg is an older version, seems like MP dubbing was scrapped https://gist.github.com/a-detiste/d1fdf4f9986d22ffe975

**Comment by Mateos81** [comment]
On a side note...
This diff is weird, why would the French of "Oops" get updated to "Désolé" which means "Sorry"? "Oups" was correct there...

**Comment by a-detiste** [comment]
I spent the summers of 2000 & 2001 copy-pasting almost single words out of HTML pages into Word documents; sent that to translators & and then copy it back into the HTML... enough to know how weirdly translation are sometimes handled.

**Comment by a-detiste** [comment]
the French texts are stored in a 'EnglishUSA' directory, as this would make sense

```
unzip -c /usr/local/games/wolfenstein/main/sp_pak1.pk3  text/EnglishUSA/village1.txt
Archive:  /usr/local/games/wolfenstein/main/sp_pak1.pk3
  inflating: text/EnglishUSA/village1.txt  

^8MISSION 2 : UN NOIR SECRET^8

^8Episode 1 : Le village^8

Message du BOS transmis par Kessler du Cercle Kreisau : nous avons appris votre capture et votre �vasion du Ch�teau Wolfenstein. La mort de l'agent Un est tragique mais vous ne pouviez rien faire.
```

**Comment by MAN-AT-ARMS** [comment]
There is a cvar for setting text language but I've never used/tested it.

**Comment by a-detiste** [comment]
Well, only people digging in the dubbed .pk3 will notice this. Now I get the mission journal rendered in `Comic Sans MS`; but maybe that's the Debian package that doesn't pull in the right font package.

**Comment by MAN-AT-ARMS** [comment]
I got a copy of the Spanish dubbed version. Your md5sum for sp_pak1.pk3 is correct.(99a26bcd4b8511f8f43576a37a7ccbdb)

I should note that sp_pak3.pk3 on this ES version is also different...
d26f576768793a046b4e03c7d0617fdf  sp_pak3.pk3

By the way...which version of sp_pak3.pk3 has md5sum 94539eded69eb99a86d752808c5e029d5915fde7? German?

**Comment by a-detiste** [comment]
I filled this bug against Debian's game-data-packager, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=803128 ; I don't ask you to special-case the French dub; but maybe this could be referenced in a readme or a FAQ; or most people would just don't care.

**Comment by a-detiste** [comment]
My Spanish version doens't include *any* sp_pak3.pk3, just like my French retail version;
so I always used the one from the 1.41 patch.

Can you compare the inner contents ?

```
unzip -l /usr/lib/rtcw/main/sp_pak3.pk3
    12862  2002-04-25 17:38   ui/ingame_system.menu
    14399  2002-04-25 17:38   ui/system.menu
     1691  2002-04-25 17:38   ui/menus.txt
     2297  2002-04-25 17:38   ui/mods.menu
    10817  2002-04-25 17:38   ui/options.menu
    10460  2002-04-25 17:38   ui/setup.menu
     1047  2002-04-25 17:38   text/EnglishUSA/escape1.txt
   196652  2002-04-25 16:16   models/mapobjects/flag/flag1a.tga
```

> By the way...which version of sp_pak3.pk3 has md5sum 94539eded69eb99a86d752808c5e029d5915fde7?

This file is found in these archive, I only know one version:

```
wolf-linux-1.4-full.x86.run
wolf-linux-1.41b.x86.run
setup_return_to_castle_wolfenstein_2.0.0.2.exe
setup_return_to_castle_wolfenstein_german_2.0.0.2.exe
```

**Comment by a-detiste** [comment]
Done: https://github.com/a-detiste/game-data-packager/commit/53e6bc40206214a125e840fae24905c6ca6d2c35

**Comment by MAN-AT-ARMS** [comment]
The Spanish sp_pak3.pk3 is probably only on the "Edición especial" version. It has the md5sum I posted earlier (d26f576768793a046b4e03c7d0617fdf).

English version is cf25d6731ed29c80303febbb177aa585.

That other sp_pak3.pk3 you have must be from that German one you have from GOG, Not sure of it's origin. I will let you know what is on the German disc version when I get it.


Archive:  sp_pak3.pk3
  Length      Date    Time    Name
---------  ---------- -----   ----
    12862  2002-04-25 17:38   ui/ingame_system.menu
    14399  2002-04-25 17:38   ui/system.menu
     1691  2002-04-25 17:38   ui/menus.txt
     2297  2002-04-25 17:38   ui/mods.menu
    10817  2002-04-25 17:38   ui/options.menu
    10460  2002-04-25 17:38   ui/setup.menu
        0  2002-05-03 11:53   ui/
        0  2002-05-03 11:53   text/EnglishUSA/
     1047  2002-04-25 17:38   text/EnglishUSA/escape1.txt
        0  2002-05-03 11:53   text/
        0  2002-05-03 11:53   models/mapobjects/
        0  2002-05-03 11:53   models/mapobjects/flag/
   196652  2002-04-25 16:16   models/mapobjects/flag/flag1a.tga
        0  2002-05-03 11:53   models/
---------                     -------
   250225                     14 files

Archive:  sp_pak3.pk3.es
  Length      Date    Time    Name
---------  ---------- -----   ----
    12963  2002-03-01 14:42   ui/ingame_system.menu
    14514  2002-03-01 14:41   ui/system.menu
     1691  2002-03-01 14:41   ui/menus.txt
     2317  2002-03-01 14:41   ui/mods.menu
    10993  2002-03-01 14:52   ui/options.menu
    10590  2002-03-01 14:53   ui/setup.menu
        0  2002-03-01 14:41   ui/
        0  2002-04-25 17:38   models/mapobjects/
        0  2002-04-25 17:38   models/mapobjects/flag/
   196652  2002-04-25 16:16   models/mapobjects/flag/flag1a.tga
        0  2002-04-25 17:38   models/
---------                     -------
   249720                     11 files

**Comment by a-detiste** [comment]
Is this  sp_pak3.pk3.es downloadable ?

**Comment by MAN-AT-ARMS** [comment]
If you need a copy of this, grab it here:
http://64.237.36.250/wolf/main/sp_pak3.pk3.SP

I may add a copy of these various official patches that aren't "widely" available to the repository at some point.

**Comment by a-detiste** [comment]
Thank as lot ! I'll use this for the Spanish version & I'll keep the repacking trick only for the French one.

https://github.com/a-detiste/game-data-packager/commit/e68b64070e72eae81050b21c52691a7bdae4cd48

I'm hosting this file on two tiny webspaces from the 90's + 1 RaspberryPi.

> That other sp_pak3.pk3 

It's like I always had this file, this is even included in my official install at /usr/local/games/wolfenstein/main/ , it just come from official patch 1.4 & 1.41.

**Comment by MAN-AT-ARMS** [comment]
OK I see what's going on here now...

The version of sp_pak3.pk3 that is copied to the main folder depends on what language you choose in the installer. Moreover, they changed sp_pak3.pk3 between version 1.3 and the newer releases. I'm only concerned with fully patched installs though.

So I have a copy of all 5 languages for sp_pak3.pk3 now. Here are the md5sums:

EN
cf25d6731ed29c80303febbb177aa585

FR
00cee7ee80cdb2920322cf37a5f65a11

SP
d26f576768793a046b4e03c7d0617fdf

IT
2e5e834ab69eacf96cc1141840adca08

GM
8a8967fb6334c3be65e714ef55b5f424

**Comment by a-detiste** [comment]
Thanks ! That's maybe an InnoSetup archive that can be decompressed with InnoExtract and it's --language parameter. 

There's a sp_pak3.pk3.IT, is there a sp_pak1.pk3.IT too ?

**Comment by MAN-AT-ARMS** [comment]
I'm assuming there is...and probably also one in German. I ordered a copy of both of these. So, when I have them in hand, I'll update the checksums of those as well.

**Comment by a-detiste** [comment]
I'm using the official French patch now too, can you update fr_sppak_checksums[] ?

By the way, the `diffscope` tool brought by the Debian Reproducible project is very usefull to recursively compare these .zip archives:
http://users.teledisnet.be/ade15809/sp_pak3.pk3.FR.html

I'll check again the German version later.

**Comment by MAN-AT-ARMS** [comment]
Fixed in 203f8d2

**Comment by MAN-AT-ARMS** [comment]
55da33452c65ef2ff62c25d0d1158bf2  sp_pak1.pk3.IT

**Comment by a-detiste** [comment]
:smile:

**Comment by MAN-AT-ARMS** [comment]
OK...so all of the German pk3 files are different with the exception of the MP ones.

7b9e0a1eb6c7412d542b330c686b232c  pak0.pk3.GM
df90d388fd11aa288b89ef7fd28a53f5  sp_pak1.pk3.GM
0b180bf8e4fbdd498769491bc7e45fb3  sp_pak2.pk3.GM

**Comment by a-detiste** [comment]
The German version sold by GOG.com use the standard pak0.pk3, but also comes with this huge `sp_pakG.pk3` .

148374118    98a612b5861e030d9d1f0c3adb1df940     main/sp_pakG.pk3

That would mean 2 different German versions to support ...

**Comment by MAN-AT-ARMS** [comment]
Ugh

**Comment by a-detiste** [comment]
Wild guess: you have the heavily censored German version as sold in Germany & GOG.com sell the German version as sold in Austria back then; but not yet available in Germany as of today.

The diffoscope tool that does a recursive compare of .zip or .deb files would help identify changes.
Or just running the game for a while & you'll quickly identify what as been censored

**Comment by a-detiste** [comment]
like, after 10 seconds of gameplay:

![](http://www.schnittberichte.com/www/SBs/4120/zflagge1.jpg)

**Comment by a-detiste** [comment]
@fabiangreffrath 

Hi Fabian, maybe you can help us here identify the different RTCW German versions.

**Comment by MAN-AT-ARMS** [comment]
http://wolfmap.ru/forum/viewtopic.php?f=123&t=2872

**Comment by a-detiste** [comment]
the GOG version:

![uncensored](https://cloud.githubusercontent.com/assets/7994192/11569818/3e5b0136-99f4-11e5-895d-2fa3426f8613.png)

**Comment by a-detiste** [comment]
well sometimes GOG.com sells games identified by ScummVM as cracked versions... 
someone even told me I should provide them *my* French version as reference; I could alter it first if I wanted and they wouldn't notice

so maybe this `sp_pakG.pk3`is something that came from a fan site that combined some assets of English & German versions

**Comment by a-detiste** [comment]
https://www.youtube.com/watch?v=pzgJXFN2Hn0

**Comment by MAN-AT-ARMS** [comment]
Yes. I've seen others like that floating around online...like that Italian one I found.
I don't know the origin of those, but obviously are not official id releases

I have the complete collection now of all the versions, in all languages, officially released.
I think I'll stick to checking just those sums because they are a known source.

**Comment by a-detiste** [comment]
I've seen this Italian dub to, it only included the text files; no sounds.

>I'll stick...

That makes sense

**Comment by MAN-AT-ARMS** [comment]
There's a pressed Russian dubbed version available too but apparently it's a bootleg,
(I don't own that one...)

It's not a huge deal though, it's not coded to error out, just print a warning.

**Comment by a-detiste** [comment]
I documented the official German version in our installation tool
https://github.com/a-detiste/game-data-packager/commit/ab596d8d4567a071695fe01b993d4f2596e2fb66

**Comment by MAN-AT-ARMS** [comment]
Nice...the German pak0.pk3 only has one changed file:
models/mapobjects/bodyparts/hel_body1.jpg ( Swastika armband )

If you're interested, I've uploaded the reports on the file differences between English->German

pak0.pk3
http://64.237.36.250/iortcw/pkgdiff_reports/pak/X_to_Y/changes_report.html
sp_pak1.pk3
http://64.237.36.250/iortcw/pkgdiff_reports/sp_pak/1_to_1/changes_report.html
sp_pak2.pk3
http://64.237.36.250/iortcw/pkgdiff_reports/sp_pak/2_to_2/changes_report.html

**Comment by MAN-AT-ARMS** [comment]
Interesting note...
The English and German pak0.pk3 file both have the same checksum.

**Comment by fabiangreffrath** [comment]
Sorry, guys, but I am afraid I cannot help you out here. I never had a German copy of this game, just a CD of the Linux version. Honestly, I never really liked the game, so I wasn't that obsessed with "version completeness" as I am with other games. ;) If you need some help translating German texts, though, of course I can help you with this!
