### ISSUE TITLE
r_depthbits "32" causes crash

### ISSUE THREAD

**Issue by Eonfge** [iortcw/iortcw#71]
**System**
Ubuntu 19.04
ioRtcw 1.51b
nvidia 4.18.56

**Setup**
This crash occured using RTCW Venom Mod 6.0. They provide a custom autoconfig.cfg with `seta r_depthbits "32"`

**How to reproduce**
Set or start ioRtcw to `r_depthbits "32"`
It also works when you start it with 24 and change it ingame, after which a vid_restart will crash the application.

**log**
[crashlog.txt](https://github.com/iortcw/iortcw/files/3145361/crashlog.txt)

**Comment by MAN-AT-ARMS** [comment]
They should change that in their mod because r_depthbits 32 isn't supported

**Comment by Eonfge** [comment]
Mmh, weird. 

Is there a reason why this might crash on Linux, but not on (presumably) Windows?

**Comment by MAN-AT-ARMS** [comment]
My guess would be hardware/driver support. I wouldn't consider it widely supported in any case. It's not the first time the Venom mod used ridiculous and/or invalid cvar settings in their configs.

**Comment by Eonfge** [comment]
Issue resolved. Future version of Venom Mod will use `r_depthbits "24"`
