### ISSUE TITLE
undefined symbol: gxv_module_class

### ISSUE THREAD

**Issue by team-penguin** [iortcw/iortcw#72]
I've tried 32 & 64 bit builds with the same result:
Trying to load "renderer_sp_opengl1_x86_64.so" from "/usr/local/games/wolf"...

Loading "renderer_sp_opengl1_x86_64.so" failed
failed:
"Failed loading /usr/local/games/wolf/renderer_sp_opengl1_x86_64.so: /usr/local/games/wolf/renderer_sp_opengl1_x86_64.so: undefined symbol: gxv_module_class"
Failed to load renderer

I can't find the symbol in my system libs, seems like it should be defined in: renderer_sp_opengl1_x86_64.so

Thanks for the help in advance.

**Comment by MAN-AT-ARMS** [comment]
It is related to the FreeType library.

Can you give more details about the system you're using? (i.e. hardware / OS / version ... etc)

Also, are you using a release binary or is it built from source?

**Comment by team-penguin** [comment]
Yes, it seems to be related to FreeType.

Here are my env details:

Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       36 bits physical, 48 bits virtual
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               23
Model name:          Intel(R) Core(TM)2 Quad CPU    Q8300  @ 2.50GHz
Stepping:            10
CPU MHz:             2431.237
CPU max MHz:         2499.0000
CPU min MHz:         2003.0000
BogoMIPS:            5000.14
L1d cache:           32K
L1i cache:           32K
L2 cache:            2048K
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge
mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall
nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni
dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm pti
dtherm

Gentoo:  [16]  default/linux/amd64/17.0/desktop (stable) *

Here is my FreeType version:
[ebuild   R    ] media-libs/freetype-2.9.1-r3:2::gentoo  USE="X adobe-cff
bzip2 cleartype_hinting png -bindist -debug -doc -fontforge -harfbuzz
-infinality -static-libs -utils" ABI_X86="32 (64) (-x32)" 0 KiB

GCC and binutils:

[ebuild   R   ~] sys-devel/gcc-7.3.0-r6:7.3.0::gentoo  USE="cxx fortran
(multilib) nls nptl objc objc++ objc-gc openmp pch (pie) sanitize ssp vtv
(-altivec) -cilk -debug -doc (-fixed-point) -go -graphite (-hardened)
(-jit) (-libssp) -mpx -pgo -regression-test -vanilla" 0 KiB
[ebuild   R    ] sys-devel/binutils-2.31.1-r6:2.31::gentoo  USE="cxx gold
nls plugins -default-gold -doc -multitarget -static-libs -test" 0 KiB


Here is the preamble that the make produces:

make[1]: Entering directory '/root/git/iortcw/SP'

Building in build/release-linux-x86_64:
  PLATFORM: linux
  ARCH: x86_64
  FILE_ARCH: x86_64
  VERSION: 1.51d-SP_GIT_6938a2da-2019-05-06
  COMPILE_PLATFORM: linux
  COMPILE_ARCH: x86_64
  HAVE_VM_COMPILED: true
  PKG_CONFIG: pkg-config
  CC: cc
  CXX: c++

  CFLAGS:
    -O2 -march=core2 -pipe -Wall -fno-strict-aliasing -pipe -DUSE_ICON
-DARCH_STRING="x86_64" -m64 -DNO_GZIP -Icode/zlib-1.2.11
-DUSE_INTERNAL_JPEG -Icode/jpeg-8c
    -DBUILD_FREETYPE -I/usr/include/freetype2 -Icode/freetype-2.9/include
-DFT2_BUILD_LIBRARY -DUSE_LOCAL_HEADERS
-DPRODUCT_VERSION="1.51d-SP_GIT_6938a2da-2019-05-06"
    -Wformat=2 -Wformat-security -Wno-format-nonliteral -Wstrict-aliasing=2
-Wmissing-format-attribute -Wdisabled-optimization -MMD -DNDEBUG -O3
-ffast-math

  CLIENT_CFLAGS:
    -D_REENTRANT -I/usr/include/SDL2 -Icode/SDL2/include -D_REENTRANT
-I/usr/include/SDL2 -DUSE_OPENAL -DUSE_OPENAL_DLOPEN -DUSE_VOIP
-DUSE_CODEC_OPUS
    -DOPUS_BUILD -DHAVE_LRINTF -DFLOAT_APPROX -DUSE_ALLOCA
-Icode/opus-1.2.1/include -Icode/opus-1.2.1/celt -Icode/opus-1.2.1/silk
-Icode/opus-1.2.1/silk/float
    -Icode/opusfile-0.9/include -Icode/libogg-1.3.3/include
-DUSE_RENDERER_DLOPEN -DUSE_MUMBLE -DUSE_BLOOM

  SERVER_CFLAGS:
    -DUSE_VOIP

  LDFLAGS:

  LIBS:
    -ldl -lm

  CLIENT_LIBS:
    -lSDL2 -lrt

  Output:
    iowolfsp.x86_64
    renderer_sp_opengl1_x86_64.so
    renderer_sp_rend2_x86_64.so
    main/cgame.sp.x86_64.so
    main/qagame.sp.x86_64.so
    main/ui.sp.x86_64.so

**Comment by team-penguin** [comment]
I forgot to mention, both pre-built and source builds have undefined the
symbol:

nm -oD *.so | grep gxv_module_class
renderer_sp_opengl1_x86_64.so:              U gxv_module_class
renderer_sp_rend2_x86_64.so:                 U gxv_module_class


ldd renderer_sp_opengl1_x86_64.so

linux-vdso.so.1 (0x00007ffeee5e4000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f6885877000)
libSDL2-2.0.so.0 => /usr/lib64/libSDL2-2.0.so.0 (0x00007f6885758000)
libfreetype.so.6 => /usr/lib64/libfreetype.so.6 (0x00007f688569c000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007f6885696000)
libm.so.6 => /lib64/libm.so.6 (0x00007f688550f000)
libmvec.so.1 => /lib64/libmvec.so.1 (0x00007f68854e3000)
libc.so.6 => /lib64/libc.so.6 (0x00007f688530f000)
/lib64/ld-linux-x86-64.so.2 (0x00007f6885f35000)
libasound.so.2 => /usr/lib64/libasound.so.2 (0x00007f688502d000)
libaudio.so.2 => /usr/lib64/libaudio.so.2 (0x00007f6884e13000)
libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007f6884cd4000)
libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007f6884cbf000)
libXcursor.so.1 => /usr/lib64/libXcursor.so.1 (0x00007f6884cb3000)
libXinerama.so.1 => /usr/lib64/libXinerama.so.1 (0x00007f6884aae000)
libXi.so.6 => /usr/lib64/libXi.so.6 (0x00007f688489e000)
libXrandr.so.2 => /usr/lib64/libXrandr.so.2 (0x00007f6884891000)
libXxf86vm.so.1 => /usr/lib64/libXxf86vm.so.1 (0x00007f688468b000)
librt.so.1 => /lib64/librt.so.1 (0x00007f6884681000)
libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f688466e000)
libpng16.so.16 => /usr/lib64/libpng16.so.16 (0x00007f6884633000)
libz.so.1 => /lib64/libz.so.1 (0x00007f688441c000)
libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libstdc++.so.6
(0x00007f688401a000)
libXt.so.6 => /usr/lib64/libXt.so.6 (0x00007f6883db1000)
libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007f6883dac000)
libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007f6883d80000)
libXrender.so.1 => /usr/lib64/libXrender.so.1 (0x00007f6883b76000)
libXfixes.so.3 => /usr/lib64/libXfixes.so.3 (0x00007f6883b6e000)
libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/libgcc_s.so.1
(0x00007f6883957000)
libSM.so.6 => /usr/lib64/libSM.so.6 (0x00007f688374f000)
libICE.so.6 => /usr/lib64/libICE.so.6 (0x00007f6883533000)
libXdmcp.so.6 => /usr/lib64/libXdmcp.so.6 (0x00007f6883529000)
libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f6883520000)
libbsd.so.0 => /usr/lib64/libbsd.so.0 (0x00007f6883309000)Here is are the
linked libs for

**Comment by MAN-AT-ARMS** [comment]
I recall an issue with Freetype 2.9.1 with missing modules, which is why I rolled it back the internal version to 2.9. I would try using 2.9 on your system.

**Comment by team-penguin** [comment]
Resolved issue with change in Makefile:
USE_FREETYPE=0
