### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by czjohns** [iortcw/iortcw#73]
In certain locations, my performance goes down, sometimes even under 40 FPS. 
In escape1, it's any area after the room where soldiers destroy the floor (including the room).
In escape2, it's this area for example (https://i.imgur.com/s8GczuD.png).

OS: Windows 10 v1809 (17763.503)
GPU: GTX 1060 6GB 
CPU: i5 4690
8GB RAM DDR3

It happens with High Quality preset, Normal preset runs with no problem.
This issue is iortcw related, because I have no problem with High Quality preset in vanilla or Knightmare patch. Tried with 1.51c and 1.51b, x64 and x86 - same result.

**Comment by MAN-AT-ARMS** [comment]
Try using the original renderer and see if that makes any difference.

In console:
cl_renderer opengl1;vid_restart

**Comment by czjohns** [comment]
No change in FPS at all :/

**Comment by czjohns** [comment]
Sorry for the previous comment. I wrote the command incorrectly.
FPS is stable with original renderer.

**Comment by czjohns** [comment]
So, is there any way to fix it other than using the different renderer? It's a weird issue, when I look at different direction from the screenshot, I get stable 91 capped fps.

**Comment by MAN-AT-ARMS** [comment]
It could be a cvar that is causing it.
Make a backup of your config and start with a fresh one. Set to the high quality preset and see if you have the performace issue with no other cvars changed.

**Comment by czjohns** [comment]
Created fresh config, used high quality and no other setting changed - still the same issue.

[wolfconfig.txt](https://github.com/iortcw/iortcw/files/3223428/wolfconfig.txt)

**Comment by KuehnhammerTobias** [comment]
@czjohns Can you please check if r_forcesun is 1 or 0? I experience big framerate drop if r_forcesun is 1.

**Comment by MAN-AT-ARMS** [comment]
These are the cvar settings for the High Quality preset. You can try changing any of these to see which may be the causing the performance issue: As mentioned above you might want to try r_forceSun 0 as the first to try:

trap_Cvar_SetValue( "r_subdivisions", 4 );
trap_Cvar_SetValue( "r_vertexlight", 0 );
trap_Cvar_SetValue( "r_lodbias", 0 );
trap_Cvar_SetValue( "r_colorbits", 32 );
trap_Cvar_SetValue( "r_depthbits", 24 );
trap_Cvar_SetValue( "r_stencilbits", 8 );
trap_Cvar_SetValue( "r_picmip", 0 );
trap_Cvar_SetValue( "r_picmip2", 0 );
trap_Cvar_SetValue( "r_texturebits", 32 );
trap_Cvar_SetValue( "r_fastSky", 0 );
trap_Cvar_SetValue( "r_dynamiclight", 1 );
trap_Cvar_SetValue( "r_inGameVideo", 1 );
trap_Cvar_SetValue( "cg_shadows", 1 );
trap_Cvar_SetValue( "cg_brassTime", 2500 );
trap_Cvar_Set( "r_texturemode", "GL_LINEAR_MIPMAP_LINEAR" );
trap_Cvar_SetValue( "r_ext_compressed_textures", 0 );
trap_Cvar_SetValue( "r_overBrightBits", 0 );
trap_Cvar_Set( "cl_renderer", "rend2" );
trap_Cvar_SetValue( "r_hdr", 1 );
trap_Cvar_SetValue( "r_postProcess", 1 );
trap_Cvar_SetValue( "r_toneMap", 1 );
trap_Cvar_SetValue( "r_autoExposure", 1 );
trap_Cvar_SetValue( "r_normalMapping", 1 );
trap_Cvar_SetValue( "r_specularMapping", 1 );
trap_Cvar_SetValue( "r_deluxeMapping", 1 );
trap_Cvar_SetValue( "r_forceSun", 1 );
trap_Cvar_SetValue( "r_drawSunRays", 1 );
trap_Cvar_SetValue( "r_sunShadows", 1 );
trap_Cvar_SetValue( "r_shadowFilter", 1 );

**Comment by czjohns** [comment]
Update:
Sorry for not responding earlier, I was busy. 
Using \r_forcesun 0 fixed it - no more FPS drops in my "escape2 test location".
