### ISSUE TITLE
alpine error 

### ISSUE THREAD

**Issue by sodomon2** [iortcw/iortcw#79]
I have a problem with the game that at the end of mission #1 gives me an error and I can not continue playing this is the error

### 6387 files in pk3 files
********************
ERROR: G_Script_ScriptParse(), Error (line 365): '}' expected, end of script found.

********************
----- Server Shutdown (Server crashed: G_Script_ScriptParse(), Error (line 365): '}' expected, end of script found.
) -----
^1Error: BotLibShutdown: bot library used before being setup
forcefully unloading qagame vm
---------------------------

**Comment by MAN-AT-ARMS** [comment]
You're going to have to provide a little more information than that

**Comment by sodomon2** [comment]
Hunk_Clear: reset the hunk ok
----- FS_Startup -----
Current search path:
/home/user/.wolf/main/sp_pak4.pk3 (21 files)
/home/user/.wolf/main/sp_pak3.pk3 (14 files)
/home/user/.wolf/main/sp_pak2.pk3 (232 files)
/home/user/.wolf/main/sp_pak1.pk3 (1345 files)
/home/user/.wolf/main/pak0.pk3 (4775 files)
/home/user/.wolf/main
./main
    
----------------------
6387 files in pk3 files
********************
ERROR: G_Script_ScriptParse(), Error (line 365): '}' expected, end of script found.

********************
----- Server Shutdown (Server crashed: G_Script_ScriptParse(), Error (line 365): '}' expected, end of script found.
) -----
^1Error: BotLibShutdown: bot library used before being setup
forcefully unloading qagame vm
---------------------------
RE_Shutdown( 0 )
Hunk_Clear: reset the hunk ok
----- R_Init -----
------- FBO_Init -------
------- GLSL_InitGPUShaders -------
loaded 276 GLSL shaders (192 gen 42 light 42 etc) in  0.29 seconds
------- R_InitVaos -------
Initializing Shaders
^3WARNING: In shader file scripts/common.shader...Shader "textures/sfx/portal3a_back2" on line 822 is missing closing brace^3.
^3WARNING: In shader file scripts/ui_wolf.shader...Invalid shader name "}" on line 1849.
----- finished R_Init -----
^3RE_RegisterFont: Unable to read font file 'fonts/bigfont'
tty]

This is what you tell me after the Escape mission is over!

**Comment by sodomon2** [comment]
Hunk_Clear: reset the hunk ok
----- FS_Startup -----
Current search path:
/home/user/.wolf/main/sp_pak4.pk3 (21 files)
/home/user/.wolf/main/sp_pak3.pk3 (14 files)
/home/user/.wolf/main/sp_pak2.pk3 (232 files)
/home/user/.wolf/main/sp_pak1.pk3 (1345 files)
/home/user/.wolf/main/pak0.pk3 (4775 files)
/home/user/.wolf/main
./main
    
----------------------
6387 files in pk3 files
********************
ERROR: G_Script_ScriptParse(), Error (line 365): '}' expected, end of script found.

********************
----- Server Shutdown (Server crashed: G_Script_ScriptParse(), Error (line 365): '}' expected, end of script found.
) -----
^1Error: BotLibShutdown: bot library used before being setup
forcefully unloading qagame vm
---------------------------
RE_Shutdown( 0 )
Hunk_Clear: reset the hunk ok
----- R_Init -----
------- FBO_Init -------
------- GLSL_InitGPUShaders -------
loaded 276 GLSL shaders (192 gen 42 light 42 etc) in  0.29 seconds
------- R_InitVaos -------
Initializing Shaders
^3WARNING: In shader file scripts/common.shader...Shader "textures/sfx/portal3a_back2" on line 822 is missing closing brace^3.
^3WARNING: In shader file scripts/ui_wolf.shader...Invalid shader name "}" on line 1849.
----- finished R_Init -----
^3RE_RegisterFont: Unable to read font file 'fonts/bigfont'
tty]

This is what you tell me after the Escape mission is over!

**Comment by sodomon2** [comment]
![1](https://user-images.githubusercontent.com/49420637/69839374-a6d49780-122d-11ea-8968-c65ee46424d6.jpg)

That's the mistake.

**Comment by MAN-AT-ARMS** [comment]
What version are you running?
What build is it?
What OS?
What other files are present?

Your sp_pak1.pk3 file doesn't seem to contain the usual number of files. Where did you get the file?

**Comment by sodomon2** [comment]
What version are you running? : 1.51c
What build is it: x86_64
What OS: Alpine Linux
What other files are present: pak0.pk3,sp_pak2.pk3 sp_pak3.pk3 sp_pak4.pk3
 
Your sp_pak1.pk3 file doesn't seem to contain the usual number of files. Where did you get the file: https://www.blizzboygames.net/return-to-castle-wolfenstein-pc-full-espanol/

It looks like the game is translated from the inside. Maybe that's the mistake.

**Comment by mckaygerhard** [comment]
it's rare due in debian 3.1 runs perfectly of course i still have an PIII i815 ibm in good shape... running a greated debian with all my games.. 

@MAN-AT-ARMS "manatars" (was incfredible that he-man toy were so belic right?) ... why that same packs can be run in my very ancient debian 3.1 sarge ? and not in the recent very fashioned  ( a stupid tendence today) alpine linux with fashioned lasted gcc and fashioned lasted libs ?

**Comment by MAN-AT-ARMS** [comment]
Add +set logfile 2 to your command line.
This will create a rtcwconsole.log file in .wolf/main
Post the contents of that file.

**Comment by sodomon2** [comment]
Here is the content

logfile opened on Tue Dec  3 10:53:08 2019

Bypassing CD checks
----- Client Initialization -----
Couldn't read rtcwhistory.
Cmd_AddCommand: map_restart already defined
----- Initializing Renderer ----
Trying to load "renderer_sp_rend2_x86_64.so" from "/home/user/Descargas/FPS/games/new/iortcw-1.51c/SP/build/release-linux-x86_64"...
---- Renderer Initialization Complete ----
RTCWKEY found.
----- Client Initialization Complete -----
----- R_Init -----
SDL using driver "x11"
Initializing OpenGL display
Display aspect: 1.707
...setting mode 17: 1024 576
Trying to get an OpenGL 3.2 core context
SDL_GL_CreateContext succeeded.
Using 24 color bits, 24 depth, 8 stencil display.
Available modes: '512x300 1024x600 640x360 720x405 864x486 960x540 1024x576 640x480 800x600'
GL_RENDERER: Mesa DRI Intel(R) Sandybridge Mobile 
Initializing OpenGL extensions
...GL_EXT_texture_compression_s3tc not found
...ignoring GL_S3_s3tc
...ignoring GL_EXT_texture_filter_anisotropic
...using GL_ARB_framebuffer_object
...using GL_ARB_vertex_array_object
...using GL_ARB_texture_float
...using GL_ARB_depth_clamp
...ignoring GL_ARB_seamless_cube_map
...using GLSL version 3.30
...GL_NVX_gpu_memory_info not found
...GL_ATI_meminfo not found
...ignoring GL_ARB_texture_compression_rgtc
...GL_ARB_texture_compression_bptc not found
...GL_EXT_direct_state_access not found
------- FBO_Init -------
------- GLSL_InitGPUShaders -------
loaded 276 GLSL shaders (192 gen 42 light 42 etc) in  0.37 seconds
------- R_InitVaos -------
Initializing Shaders
^3WARNING: In shader file scripts/common.shader...Shader "textures/sfx/portal3a_back2" on line 822 is missing closing brace^3.
^3WARNING: In shader file scripts/ui_wolf.shader...Invalid shader name "}" on line 1849.
----- finished R_Init -----
------ Initializing Sound ------
Trying to load "libopenal.so.1"...
Allocated 128 sources.
OpenAL default capture device is 'ALSA Default'
OpenAL capture device opened.
OpenAL info:
  Vendor:         OpenAL Community
  Version:        1.1 ALSOFT 1.19.1
  Renderer:       OpenAL Soft
  AL Extensions:  AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_BFORMAT AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_EXT_SOURCE_RADIUS AL_EXT_STEREO_ANGLES AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFTX_events AL_SOFTX_filter_gain_ex AL_SOFT_gain_clamp_ex AL_SOFT_loop_points AL_SOFTX_map_buffer AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length AL_SOFT_source_resampler AL_SOFT_source_spatialize
  ALC Extensions: ALC_ENUMERATE_ALL_EXT ALC_ENUMERATION_EXT ALC_EXT_CAPTURE ALC_EXT_DEDICATED ALC_EXT_disconnect ALC_EXT_EFX ALC_EXT_thread_local_context ALC_SOFT_device_clock ALC_SOFT_HRTF ALC_SOFT_loopback ALC_SOFT_output_limiter ALC_SOFT_pause_device
  Device:         ALSA Default
  Available Devices:
ALSA Default
HDA Intel PCH, ALC269VB Analog (CARD=PCH,DEV=0)
HDA Intel PCH, HDMI 0 (CARD=PCH,DEV=3)
  Input Device:   ALSA Default
  Available Input Devices:
ALSA Default
HDA Intel PCH, ALC269VB Analog (CARD=PCH,DEV=0)
Sound initialization successful.
--------------------------------
^3RE_RegisterFont: Unable to read font file 'fonts/bigfont'
--- Common Initialization Complete ---
IP: 127.0.0.1
IP: 172.16.16.20
IP: 172.22.206.92
IP: 192.168.196.51
IP6: ::1
IP6: fde0:d38b:5e4e:0:829b:20ff:fe30:c730
IP6: fe80::829b:20ff:fe30:c730%wlan0
IP6: fe80::ec9c:8fff:fe22:2636%ztyxa4fkzk
IP6: fe80::c8f5:76ff:fed3:3052%ztwdjf7vh6
Opening IP6 socket: [::]:27960
Opening IP socket: 0.0.0.0:27960
sv_maxclients will be changed upon restarting.
------ Server Initialization ------
Server: escape1
RE_Shutdown( 0 )
------- FBO_Shutdown -------
------- R_ShutdownVaos -------
------- GLSL_ShutdownGPUShaders -------
Hunk_Clear: reset the hunk ok
Current search path:
/home/user/.wolf/main/sp_pak4.pk3 (21 files)
/home/user/.wolf/main/sp_pak3.pk3 (11 files)
/home/user/.wolf/main/sp_pak2.pk3 (232 files)
/home/user/.wolf/main/sp_pak1.pk3 (1345 files)
/home/user/.wolf/main/pak0.pk3 (4775 files)
/home/user/.wolf/main
/home/user/Descargas/FPS/games/new/iortcw-1.51c/SP/build/release-linux-x86_64/main

handle 1: rtcwconsole.log
----------------------
6384 files in pk3 files
Gametype changed, clearing session data.
------- BotLib Initialization -------
------------ Map Loading ------------
trying to load maps/escape1_b0.aas
loaded maps/escape1_b0.aas
trying to load maps/escape1_b1.aas
loaded maps/escape1_b1.aas
-------------------------------------
AAS initialized.
AAS initialized.
-----------------------------------
RE_Shutdown( 0 )
----- R_Init -----
------- FBO_Init -------
------- GLSL_InitGPUShaders -------
loaded 276 GLSL shaders (192 gen 42 light 42 etc) in  0.27 seconds
------- R_InitVaos -------
Initializing Shaders
^3WARNING: In shader file scripts/common.shader...Shader "textures/sfx/portal3a_back2" on line 822 is missing closing brace^3.
^3WARNING: In shader file scripts/ui_wolf.shader...Invalid shader name "}" on line 1849.
----- finished R_Init -----
^3RE_RegisterFont: Unable to read font file 'fonts/bigfont'
LOADING... collision map
LOADING... sounds

.........................
Initializing Sound Scripts
...loading 'sound/scripts/cutscene1.sounds'
...loading 'sound/scripts/cutscene6.sounds'
...loading 'sound/scripts/cutscene9.sounds'
...loading 'sound/scripts/cutscene11.sounds'
...loading 'sound/scripts/cutscene14.sounds'
...loading 'sound/scripts/cutscene19.sounds'
...loading 'sound/scripts/escape1.sounds'
...loading 'sound/scripts/escape2.sounds'
...loading 'sound/scripts/tram.sounds'
...loading 'sound/scripts/village1.sounds'
...loading 'sound/scripts/crypt1.sounds'
...loading 'sound/scripts/crypt2.sounds'
...loading 'sound/scripts/church.sounds'
...loading 'sound/scripts/boss1.sounds'
...loading 'sound/scripts/forest.sounds'
...loading 'sound/scripts/rocket.sounds'
...loading 'sound/scripts/assault.sounds'
...loading 'sound/scripts/sfm.sounds'
...loading 'sound/scripts/factory.sounds'
...loading 'sound/scripts/trainyard.sounds'
...loading 'sound/scripts/swf.sounds'
...loading 'sound/scripts/norway.sounds'
...loading 'sound/scripts/xlabs.sounds'
...loading 'sound/scripts/boss2.sounds'
...loading 'sound/scripts/dam.sounds'
...loading 'sound/scripts/village2.sounds'
...loading 'sound/scripts/chateau.sounds'
...loading 'sound/scripts/dark.sounds'
...loading 'sound/scripts/castle.sounds'
...loading 'sound/scripts/end.sounds'
...loading 'sound/scripts/ai.sounds'
...loading 'sound/scripts/general.sounds'
...loading 'sound/scripts/combat.sounds'
...loading 'sound/scripts/movers.sounds'
done.
LOADING... graphics
LOADING... maps/escape1.bsp
^3Trisurf has bad triangles, originally shader models/mapobjects/shield/shield 34 tris 37 verts, now 32 tris
^3Trisurf has bad triangles, originally shader models/mapobjects/shield/shield 34 tris 37 verts, now 32 tris
^3Trisurf has bad triangles, originally shader models/mapobjects/shield/shield 34 tris 37 verts, now 32 tris
^3Trisurf has bad triangles, originally shader models/mapobjects/shield/shield 34 tris 37 verts, now 32 tris
^3Trisurf has bad triangles, originally shader models/mapobjects/shield/shield 34 tris 37 verts, now 32 tris
^3Trisurf has bad triangles, originally shader models/mapobjects/shield/shield 34 tris 37 verts, now 32 tris
^3Trisurf has bad triangles, originally shader models/mapobjects/shield/shield 34 tris 37 verts, now 32 tris
^3Trisurf has bad triangles, originally shader models/mapobjects/shield/shield 34 tris 37 verts, now 32 tris
^3Trisurf has bad triangles, originally shader models/mapobjects/shield/shield 34 tris 37 verts, now 32 tris
^3Trisurf has bad triangles, originally shader models/mapobjects/shield/shield 34 tris 37 verts, now 32 tris
^3Trisurf has bad triangles, originally shader models/mapobjects/shield/shield 34 tris 37 verts, now 32 tris
^3Trisurf has bad triangles, originally shader models/mapobjects/shield/shield 34 tris 37 verts, now 32 tris
^3Trisurf has bad triangles, originally shader textures/rock/roc_m01aa 1031 tris 631 verts, now 1029 tris
^3Trisurf has bad triangles, originally shader models/mapobjects/shield/shield 34 tris 37 verts, now 32 tris
^3Trisurf has bad triangles, originally shader models/mapobjects/shield/shield 34 tris 37 verts, now 32 tris
^3Trisurf has bad triangles, originally shader models/mapobjects/shield/shield 34 tris 37 verts, now 32 tris
^3Trisurf has bad triangles, originally shader models/mapobjects/shield/shield 34 tris 37 verts, now 32 tris
stitched 12 LoD cracks
...loaded 14663 faces, 284 meshes, 367 trisurfs, 7 flares
LOADING... game media
LOADING...  - textures
LOADING...  - models
LOADING...  - weapons
LOADING...  - items
LOADING...  - inline models
LOADING...  - server models
LOADING...  - particles
LOADING...  - game media done
LOADING... flamechunks
LOADING... clients
LOADING... WolfPlayer
UI menu load time = 5 milli seconds
CL_InitCGame:  5.44 seconds
58 msec to draw all images
Com_TouchMemory: 0 msec
sv_maxclients will be changed upon restarting.
AAS shutdown.
------ Server Initialization ------
Server: escape2
RE_Shutdown( 0 )
------- FBO_Shutdown -------
------- R_ShutdownVaos -------
------- GLSL_ShutdownGPUShaders -------
Hunk_Clear: reset the hunk ok
Current search path:
/home/user/.wolf/main/sp_pak4.pk3 (21 files)
/home/user/.wolf/main/sp_pak3.pk3 (11 files)
/home/user/.wolf/main/sp_pak2.pk3 (232 files)
/home/user/.wolf/main/sp_pak1.pk3 (1345 files)
/home/user/.wolf/main/pak0.pk3 (4775 files)
/home/user/.wolf/main
/home/user/Descargas/FPS/games/new/iortcw-1.51c/SP/build/release-linux-x86_64/main

handle 1: rtcwconsole.log
----------------------
6384 files in pk3 files
********************
ERROR: G_Script_ScriptParse(), Error (line 365): '}' expected, end of script found.

********************
----- Server Shutdown (Server crashed: G_Script_ScriptParse(), Error (line 365): '}' expected, end of script found.
) -----
^1Error: BotLibShutdown: bot library used before being setup
forcefully unloading qagame vm
---------------------------
RE_Shutdown( 0 )
Hunk_Clear: reset the hunk ok
----- R_Init -----
------- FBO_Init -------
------- GLSL_InitGPUShaders -------
loaded 276 GLSL shaders (192 gen 42 light 42 etc) in  0.25 seconds
------- R_InitVaos -------
Initializing Shaders
^3WARNING: In shader file scripts/common.shader...Shader "textures/sfx/portal3a_back2" on line 822 is missing closing brace^3.
^3WARNING: In shader file scripts/ui_wolf.shader...Invalid shader name "}" on line 1849.
----- finished R_Init -----
^3RE_RegisterFont: Unable to read font file 'fonts/bigfont'
^3turning EXEC_NOW 'quit' into EXEC_INSERT
----- Client Shutdown (Client quit) -----
RE_Shutdown( 1 )
------- FBO_Shutdown -------
------- R_ShutdownVaos -------
------- GLSL_ShutdownGPUShaders -------
Hunk_Clear: reset the hunk ok
OpenAL capture device closed.
-----------------------

Here is the log

[rtcwconsole.log](https://github.com/iortcw/iortcw/files/3917230/rtcwconsole.log)

**Comment by sodomon2** [comment]
Hi, it's been a while since I opened this issue, and I was wondering if you found out what the problem is.

**Comment by MAN-AT-ARMS** [comment]
Not sure if this issue warrants a response after you admitted to pirating the game.
Are you loading a save file from a different architecture?

**Comment by sodomon2** [comment]
No, I'm not loading any files from a different architecture.

**Comment by sodomon2** [comment]
I will close this as it does not take this issue seriously

**Comment by sodomon2** [comment]
I think I know what the error is, it seems to be due to the lines G_Script_ScriptParse(), Error (line * declared in g_script.c in SP/code/game

**Comment by MAN-AT-ARMS** [comment]
There was a line removed at the top of that function.

if ( !ent->scriptName ) {
		return;
	}
	if ( !level.scriptEntity ) {
		return;
	}

	buildScript = trap_Cvar_VariableIntegerValue( "com_buildScript" ); 
	//buildScript = qtrue;

	pScript = level.scriptEntity;
	wantName = qtrue;
	inScript = qfalse;
	COM_BeginParseSession( "G_Script_ScriptParse" );

Try adding this change near the top of the function and see if it changes anything for you.

**Comment by sodomon2** [comment]
in the g_script.c file?

**Comment by MAN-AT-ARMS** [comment]
Yes, in G_Script_ScriptParse function. I don't forsee it making a difference, but you can try it. I can't reproduce the problem here and the assets you are using are stolen and questionable. I do not have the issue you describe when using the Spanish version.

**Comment by sodomon2** [comment]
It should look like this, right?
`    if ( !ent->scriptName ) {
        return;
    }
    if ( !level.scriptEntity ) {
        return;
    }
    buildScript = trap_Cvar_VariableIntegerValue( "com_buildScript" ); 
    //buildScript = qtrue;

    pScript = level.scriptEntity;
    wantName = qtrue;
    inScript = qfalse;
    COM_BeginParseSession( "G_Script_ScriptParse" );
`

**Comment by MAN-AT-ARMS** [comment]
Correct. Try adding that one line and commenting out the existing one.

**Comment by sodomon2** [comment]
apparently I still get the same mistake :C
