### ISSUE TITLE
"patch-data-141.zip"

### ISSUE THREAD

**Issue by donizettilorenzo** [iortcw/iortcw#8]
Not a real "issue" but a simple question: what is this package? :|

**Comment by MAN-AT-ARMS** [comment]
It's all the official patch files ( without executables ) needed to bring any version up to 1.41 (latest)

**Comment by donizettilorenzo** [comment]
Thanks! Any difference between this package and Steam version / Old Retail+Official Patch 1.41?

**Comment by MAN-AT-ARMS** [comment]
I'm not sure what files Steam installs, but this zip contains every official file needed for a fully patched iortcw install.

In other words, every file in this zip is from the official patches. If you're fully patched already, your files should match the ones contained in the zip and you shouldn't need it.

**Comment by donizettilorenzo** [comment]
Thanks man (at arms :D ), much obliged ;)

**Comment by MAN-AT-ARMS** [comment]
I should note that there are some files in here that aren't needed (or used) for iortcw.
It's just basically a compilation of all the official 1.41 / GOTY patch files.
Some of the patch files here are for the vanilla game only but were included for completeness.

**Comment by donizettilorenzo** [comment]
Only one last question! With retail+official patches some files are in the root dir, not in the "main" dir:

*cgamex86.dll
*qagamex86.dll
*uix86.dll

If this is not a problem, well, it's done!

**Comment by MAN-AT-ARMS** [comment]
Those are the 1.0 game modules for single player.

**Comment by donizettilorenzo** [comment]
Comparing the files it's the same version of your package (and the date shows 2002, not 2001 so they are patched), only in the root folder and not in the "main" folder.

**Comment by MAN-AT-ARMS** [comment]
You're right...for Windows they stuck the single player files in the root dir. ( and also the multiplayer ones on some versions )

There hasn't been a lot of consistency, but I'm fairly sure they'll work in 'Main' regardless.

**Comment by donizettilorenzo** [comment]
Yes, they work (tested) :D
Have a good 2016 (in the spirit of Wolfenstein) ;)

**Comment by MAN-AT-ARMS** [comment]
Thank you...you too!
