### ISSUE TITLE
Custom weapon models don't work in multiplayer

### ISSUE THREAD

**Issue by 3371-Alpha** [iortcw/iortcw#80]
Currently if you attempt to use a custom weapon model in multiplayer all you get is a broken model. I've read that there's a poly limit in the multiplayer version of the engine, I'm wondering if it can be shut off. Example mods I've used: [Splatterladder RtCW HD Pack](https://www.moddb.com/mods/splatterladder-rtcw-hd-pack) and [Remade Weapons](https://www.moddb.com/games/return-to-castle-wolfenstein/addons/rw).

**Comment by MAN-AT-ARMS** [comment]
If a MP server is running in pure mode and doesn't have the pack on the server the pk3 will not be utilized.
Not an iortcw issue...

**Comment by 3371-Alpha** [comment]
I don't completely know what you mean by that to be honest but some pics of me hosting a game so you can see what I'm talking about.
![Screenshot (32)](https://user-images.githubusercontent.com/24741232/71784361-b3c07580-2fa7-11ea-9d81-fc5e9fd3ec90.png)
![Uploading Screenshot (33).png…]()

**Comment by MAN-AT-ARMS** [comment]
That's all the info you can give? Good luck

**Comment by KuehnhammerTobias** [comment]
@3371-Alpha The zip files you pointed to contains totally broken assets. Whoever made those weapon models didn't do things right. As MAN-AT-ARMS already said, this isn't an iortcw issue. I just want to say that at least I can confirm your issue.

**Comment by MAN-AT-ARMS** [comment]
Looks like these mods were intended to be used on single player
