### ISSUE TITLE
weapons config and parameter

### ISSUE THREAD

**Issue by Anders1980** [iortcw/iortcw#82]
Dear author. My question is: can the files with weapon settings be moved to an external folder in the same way as it is implemented in Call of Duty ?

**Comment by MAN-AT-ARMS** [comment]
I have no idea what you are talking about.

**Comment by Anders1980** [comment]
Have you played Call of Duty ? The pak0.pk3 archive has a weapons folder divided into two subfolders sp for single player and mp for multiplayer. Each of them contains files with weapon settings that the engine reads and that we can change.

**Comment by MAN-AT-ARMS** [comment]
I've played it...I don't see how that any of that is relevant though.

If you want to modify the game to implement something like that, go right ahead.

This project is not intended to modify the game code.
