### ISSUE TITLE
VM_Create on UI failed crash single player 

### ISSUE THREAD

**Issue by doomhg** [iortcw/iortcw#84]
All of a sudden I started getting VM_Create on UI failed trying to launch single player.
I tried starting over uninstalling iortcw but same result MP exe works fine gets to main menu.

[iortcw x64.txt](https://github.com/iortcw/iortcw/files/4313333/iortcw.x64.txt)

**Comment by MAN-AT-ARMS** [comment]
Do you have the dll files in the 'main' folder? (cgame_sp, game_sp, ui_sp)

**Comment by doomhg** [comment]
Thanks for reply. I didn't have those files in iortcw main folder. But copying  cgame_sp_x64.dll, qagame_sp_x64.dll and ui_sp_x64.dll from where the exe's are to iortcw Main like you said fixed the problem. Thanks again for the help

**Comment by MAN-AT-ARMS** [comment]
Your welcome
