### ISSUE TITLE
OpenGL Issue

### ISSUE THREAD

**Issue by dude10101** [iortcw/iortcw#87]
Hello I am having this issue. Can someone help me with this! Thanks

3763 files in pk3 files
execing default.cfg
couldn't exec language.cfg
couldn't exec autoexec.cfg
Hunk_Clear: reset the hunk ok
...detecting CPU, found Intel Pentium III
Bypassing CD checks
----- Client Initialization -----
----- Initializing Renderer ----
-------------------------------
----- Client Initialization Complete -----
----- R_Init -----
Initializing OpenGL subsystem
...initializing QGL
...calling LoadLibrary( 'C:\Windows\system32\opengl32.dll' ): succeeded
...setting mode 4: 800 600 FS
...using desktop display depth of 32
...calling CDS: failed, bad mode
...trying next higher resolution: ok
...registered window class
...created window@0,0 (800x600)
Initializing OpenGL driver
...getting DC: succeeded
...GLW_ChoosePFD( 32, 24, 0 )
...35 PFDs found
...GLW_ChoosePFD failed
...GLW_ChoosePFD( 32, 24, 0 )
...35 PFDs found
...GLW_ChoosePFD failed
...failed to find an appropriate PIXELFORMAT
...restoring display settings
...WARNING: could not set the given mode (4)
...setting mode 4: 800 600 FS
...using colorsbits of 16
...calling CDS: failed, bad mode
...trying next higher resolution: ok
...created window@0,0 (800x600)
Initializing OpenGL driver
...getting DC: succeeded
...GLW_ChoosePFD( 16, 16, 0 )
...35 PFDs found
...GLW_ChoosePFD failed
...GLW_ChoosePFD( 16, 16, 0 )
...35 PFDs found
...GLW_ChoosePFD failed
...failed to find an appropriate PIXELFORMAT
...restoring display settings
...WARNING: could not set the given mode (3)
...shutting down QGL
...unloading OpenGL DLL
...assuming '3dfxvgl' is a standalone driver
...initializing QGL
...WARNING: missing Glide installation, assuming no 3Dfx available
...shutting down QGL
----- CL_Shutdown -----
RE_Shutdown( 1 )
-----------------------
GLW_StartOpenGL() - could not load OpenGL subsystem

**Comment by MAN-AT-ARMS** [comment]
Looks like you don't have an OpenGL capable video card or driver installed.
What's the hardware and OS you are running this on?

**Comment by dude10101** [comment]
Here's the Hardware.
<img width="303" alt="Screen Shot 2020-04-10 at 3 51 33 PM" src="https://user-images.githubusercontent.com/63436576/79019012-4cd0d080-7b43-11ea-8f01-9ddb8cb1bfd4.png">

I have an Intel UHD Graphics 630 + an AMD Radeaon Pro 5500M

I am trying to play the game with Windows via bootcamp since It does not seem to be working on OS Catalina. 
Is there a simple way to make it work on Mac ?
Thank for you quick answer

**Comment by MAN-AT-ARMS** [comment]
It should work on mac but I'm not sure If Catalina has issues or not as I'm unable to install it on my Mac. I know at least one person did mention he was running it on Catalina.

In windows you need to make sure the drivers support OpenGL. I would download them from Intel/AMD directly.

**Comment by dude10101** [comment]
I read that on Mac the Catalina OS only has 64bit and therefore wont be able to play the game since it is 32bit only. Is there a workaround ?

**Comment by MAN-AT-ARMS** [comment]
The Mac version contains a 64-bit build in the app bundle. Download from releases page.

**Comment by MAN-AT-ARMS** [comment]
On Windows make sure you are downloading the correct version, 32 or 64, whichever version matches your windows build.

**Comment by dude10101** [comment]
Thanks! 
On mac when i download the version 2.60. I cannot click on the logo to install the game
![image](https://user-images.githubusercontent.com/63436576/79079585-0fed1100-7cde-11ea-991c-1ce7b97e83f7.png)

In the release page whats the difference between : i
ortcw-1.51c-mac-term.zip
iortcw-1.51c-mac-ub.zip

**Comment by MAN-AT-ARMS** [comment]
The game above is Enemy Territory. That's not what this project is...this is the original RTCW. The ub version is the app bundle one.

**Comment by dude10101** [comment]
Damn I thought it was ET. Man it it so complicated to play ET on Catalina haha

**Comment by MAN-AT-ARMS** [comment]
Maybe try ETLegacy. Not sure of their Mac status though.
