### ISSUE TITLE
Build error Raspberry pi 4

### ISSUE THREAD

**Issue by cesarpuig** [iortcw/iortcw#88]
Hi.

When I try to build from source on raspberry pi I get an error.

Commit 2f4c329 builds fine.

This is my log file:

`make[1]: se entra en el directorio '/home/pi/RetroPie-Setup/tmp/build/rtcw/SP'

Building in build/release-linux-arm:
  PLATFORM: linux
  ARCH: arm
  FILE_ARCH: arm
  VERSION: 1.51d-SP_GIT_7470e4b-2020-04-26
  COMPILE_PLATFORM: linux
  COMPILE_ARCH: arm
  HAVE_VM_COMPILED: true
  PKG_CONFIG: pkg-config
  CC: cc
  CXX: g++

  CFLAGS:
    -march=armv8-a+crc -mtune=cortex-a72 -mfpu=neon-fp-armv8 -mfloat-abi=hard -O2 -pipe -Wall -fno-strict-aliasing -pipe -DUSE_ICON -DARCH_STRING="arm" -DUSE_OPENGLES -DNO_GZIP -Icode/zlib-1.2.11
    -DUSE_INTERNAL_JPEG -Icode/jpeg-8c -DBUILD_FREETYPE -Icode/freetype-2.9/include -DFT2_BUILD_LIBRARY -DUSE_LOCAL_HEADERS -DPRODUCT_VERSION="1.51d-SP_GIT_7470e4b-2020-04-26" -Wformat=2
    -Wformat-security -Wno-format-nonliteral -Wstrict-aliasing=2 -Wmissing-format-attribute -Wdisabled-optimization -MMD -DNDEBUG -O3 -ffast-math

  CLIENT_CFLAGS:
    -D_REENTRANT -I/usr/include/SDL2 -Icode/SDL2/include -DUSE_OPENAL -DUSE_OPENAL_DLOPEN

  SERVER_CFLAGS:
    

  LDFLAGS:
    

  LIBS:
    -ldl -lm

  CLIENT_LIBS:
    -lSDL2

  Output:
    iowolfsp.arm
    main/cgame.sp.arm.so
    main/qagame.sp.arm.so
    main/ui.sp.arm.so

make[2]: se entra en el directorio '/home/pi/RetroPie-Setup/tmp/build/rtcw/SP'
CC code/client/cl_console.c
CC code/qcommon/common.c
make[2]: 'build/release-linux-arm/main/cgame.sp.arm.so' está actualizado.
make[2]: 'build/release-linux-arm/main/qagame.sp.arm.so' está actualizado.
LD build/release-linux-arm/main/ui.sp.arm.so
LD build/release-linux-arm/iowolfsp.arm
/usr/bin/ld: build/release-linux-arm/client/vm.o: en la función `VM_Create':
vm.c:(.text+0xe90): referencia a `VM_Compile' sin definir
/usr/bin/ld: build/release-linux-arm/client/vm.o: en la función `VM_Call':
vm.c:(.text+0x12e8): referencia a `VM_CallCompiled' sin definir
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2283: build/release-linux-arm/iowolfsp.arm] Error 1
make[2]: se sale del directorio '/home/pi/RetroPie-Setup/tmp/build/rtcw/SP'
make[1]: *** [Makefile:1450: targets] Error 2
make[1]: se sale del directorio '/home/pi/RetroPie-Setup/tmp/build/rtcw/SP'
make: *** [Makefile:1367: release] Error 2
make[1]: se entra en el directorio '/home/pi/RetroPie-Setup/tmp/build/rtcw/MP'

Building in build/release-linux-arm:
  PLATFORM: linux
  ARCH: arm
  FILE_ARCH: arm
  VERSION: 1.51d-MP_GIT_7470e4b-2020-04-26
  COMPILE_PLATFORM: linux
  COMPILE_ARCH: arm
  HAVE_VM_COMPILED: true
  PKG_CONFIG: pkg-config
  CC: cc
  CXX: g++

  CFLAGS:
    -march=armv8-a+crc -mtune=cortex-a72 -mfpu=neon-fp-armv8 -mfloat-abi=hard -O2 -pipe -Wall -fno-strict-aliasing -pipe -DUSE_ICON -DARCH_STRING="arm" -DUSE_OPENGLES -DNO_GZIP -Icode/zlib-1.2.11
    -DUSE_INTERNAL_JPEG -Icode/jpeg-8c -DBUILD_FREETYPE -Icode/freetype-2.9/include -DFT2_BUILD_LIBRARY -DUSE_LOCAL_HEADERS -DPRODUCT_VERSION="1.51d-MP_GIT_7470e4b-2020-04-26" -Wformat=2
    -Wformat-security -Wno-format-nonliteral -Wstrict-aliasing=2 -Wmissing-format-attribute -Wdisabled-optimization -MMD -DNDEBUG -O3 -ffast-math

  CLIENT_CFLAGS:
    -D_REENTRANT -I/usr/include/SDL2 -Icode/SDL2/include -DUSE_OPENAL -DUSE_OPENAL_DLOPEN -DUSE_PBMD5

  SERVER_CFLAGS:
    

  LDFLAGS:
    

  LIBS:
    -ldl -lm

  CLIENT_LIBS:
    -lSDL2

  Output:
    iowolfded.arm
    iowolfmp.arm
    main/cgame.mp.arm.so
    main/qagame.mp.arm.so
    main/ui.mp.arm.so
    main/vm/cgame.mp.qvm
    main/vm/qagame.mp.qvm
    main/vm/ui.mp.qvm

make[2]: se entra en el directorio '/home/pi/RetroPie-Setup/tmp/build/rtcw/MP'
DED_CC code/qcommon/common.c
CC code/client/cl_console.c
CC code/qcommon/common.c
make[2]: 'build/release-linux-arm/main/cgame.mp.arm.so' está actualizado.
make[2]: 'build/release-linux-arm/main/qagame.mp.arm.so' está actualizado.
make[2]: 'build/release-linux-arm/main/ui.mp.arm.so' está actualizado.
LD build/release-linux-arm/tools/q3rcc
LD build/release-linux-arm/tools/q3lcc
CGAME_Q3LCC code/cgame/cg_main.c
CGAME_Q3LCC code/game/bg_animation.c
CGAME_Q3LCC code/game/bg_misc.c
CGAME_Q3LCC code/game/bg_pmove.c
CGAME_Q3LCC code/game/bg_slidemove.c
CGAME_Q3LCC code/game/bg_lib.c
CGAME_Q3LCC code/cgame/cg_consolecmds.c
CGAME_Q3LCC code/cgame/cg_draw.c
CGAME_Q3LCC code/cgame/cg_drawtools.c
CGAME_Q3LCC code/cgame/cg_effects.c
CGAME_Q3LCC code/cgame/cg_ents.c
CGAME_Q3LCC code/cgame/cg_event.c
CGAME_Q3LCC code/cgame/cg_flamethrower.c
CGAME_Q3LCC code/cgame/cg_info.c
CGAME_Q3LCC code/cgame/cg_localents.c
CGAME_Q3LCC code/cgame/cg_marks.c
CGAME_Q3LCC code/cgame/cg_newdraw.c
CGAME_Q3LCC code/cgame/cg_particles.c
CGAME_Q3LCC code/cgame/cg_players.c
CGAME_Q3LCC code/cgame/cg_playerstate.c
CGAME_Q3LCC code/cgame/cg_predict.c
CGAME_Q3LCC code/cgame/cg_scoreboard.c
CGAME_Q3LCC code/cgame/cg_servercmds.c
CGAME_Q3LCC code/cgame/cg_snapshot.c
CGAME_Q3LCC code/cgame/cg_sound.c
CGAME_Q3LCC code/cgame/cg_spawn.c
CGAME_Q3LCC code/cgame/cg_trails.c
CGAME_Q3LCC code/cgame/cg_view.c
CGAME_Q3LCC code/cgame/cg_weapons.c
UI_Q3LCC code/ui/ui_shared.c
Q3LCC code/qcommon/q_math.c
Q3LCC code/qcommon/q_shared.c
GAME_Q3LCC code/game/g_main.c
GAME_Q3LCC code/game/ai_cast.c
GAME_Q3LCC code/game/ai_cast_characters.c
GAME_Q3LCC code/game/ai_cast_debug.c
GAME_Q3LCC code/game/ai_cast_events.c
GAME_Q3LCC code/game/ai_cast_fight.c
GAME_Q3LCC code/game/ai_cast_func_attack.c
GAME_Q3LCC code/game/ai_cast_func_boss1.c
GAME_Q3LCC code/game/ai_cast_funcs.c
GAME_Q3LCC code/game/ai_cast_script_actions.c
GAME_Q3LCC code/game/ai_cast_script.c
GAME_Q3LCC code/game/ai_cast_script_ents.c
GAME_Q3LCC code/game/ai_cast_sight.c
GAME_Q3LCC code/game/ai_cast_think.c
GAME_Q3LCC code/game/ai_chat.c
GAME_Q3LCC code/game/ai_cmd.c
GAME_Q3LCC code/game/ai_dmnet.c
GAME_Q3LCC code/game/ai_dmq3.c
GAME_Q3LCC code/game/ai_main.c
GAME_Q3LCC code/game/ai_team.c
GAME_Q3LCC code/game/bg_animation.c
GAME_Q3LCC code/game/bg_misc.c
GAME_Q3LCC code/game/bg_pmove.c
GAME_Q3LCC code/game/bg_slidemove.c
GAME_Q3LCC code/game/bg_lib.c
GAME_Q3LCC code/game/g_active.c
GAME_Q3LCC code/game/g_alarm.c
GAME_Q3LCC code/game/g_antilag.c
GAME_Q3LCC code/game/g_bot.c
GAME_Q3LCC code/game/g_client.c
GAME_Q3LCC code/game/g_cmds.c
GAME_Q3LCC code/game/g_combat.c
GAME_Q3LCC code/game/g_items.c
GAME_Q3LCC code/game/g_mem.c
GAME_Q3LCC code/game/g_misc.c
GAME_Q3LCC code/game/g_missile.c
GAME_Q3LCC code/game/g_mover.c
GAME_Q3LCC code/game/g_props.c
GAME_Q3LCC code/game/g_script_actions.c
GAME_Q3LCC code/game/g_script.c
GAME_Q3LCC code/game/g_session.c
GAME_Q3LCC code/game/g_spawn.c
GAME_Q3LCC code/game/g_svcmds.c
GAME_Q3LCC code/game/g_target.c
GAME_Q3LCC code/game/g_team.c
GAME_Q3LCC code/game/g_tramcar.c
GAME_Q3LCC code/game/g_trigger.c
GAME_Q3LCC code/game/g_utils.c
GAME_Q3LCC code/game/g_weapon.c
UI_Q3LCC code/ui/ui_main.c
UI_Q3LCC code/ui/ui_atoms.c
UI_Q3LCC code/ui/ui_gameinfo.c
UI_Q3LCC code/ui/ui_players.c
UI_Q3LCC code/game/bg_misc.c
UI_Q3LCC code/game/bg_lib.c
LD build/release-linux-arm/iowolfded.arm
LD build/release-linux-arm/iowolfmp.arm
Q3ASM build/release-linux-arm/main/vm/cgame.mp.qvm
Q3ASM build/release-linux-arm/main/vm/qagame.mp.qvm
/usr/bin/ld: build/release-linux-arm/ded/vm.o: en la función `VM_Create':
vm.c:(.text+0xebc): referencia a `VM_Compile' sin definir
/usr/bin/ld: build/release-linux-arm/ded/vm.o: en la función `VM_Call':
vm.c:(.text+0x1318): referencia a `VM_CallCompiled' sin definir
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2468: build/release-linux-arm/iowolfded.arm] Error 1
make[2]: *** Se espera a que terminen otras tareas....
/usr/bin/ld: build/release-linux-arm/client/vm.o: en la función `VM_Create':
vm.c:(.text+0xf18): referencia a `VM_Compile' sin definir
/usr/bin/ld: build/release-linux-arm/client/vm.o: en la función `VM_Call':
vm.c:(.text+0x1370): referencia a `VM_CallCompiled' sin definir
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2312: build/release-linux-arm/iowolfmp.arm] Error 1
make[2]: se sale del directorio '/home/pi/RetroPie-Setup/tmp/build/rtcw/MP'
make[1]: *** [Makefile:1473: targets] Error 2
make[1]: se sale del directorio '/home/pi/RetroPie-Setup/tmp/build/rtcw/MP'
make: *** [Makefile:1390: release] Error 2`

Thanks.

**Comment by MAN-AT-ARMS** [comment]
Not sure what would have changed with it. Try building a clean copy.
rm -rf build
ARCH=armv7l make

**Comment by cesarpuig** [comment]
Hi @MAN-AT-ARMS 

Builds well with this modification

I close the issue.

Thanks a lot
