### ISSUE TITLE
Resolution via in-game menu

### ISSUE THREAD

**Issue by donizettilorenzo** [iortcw/iortcw#9]
*ioRTCW 1.42d
*Deleted every config file in the RTCW folders

Can't set resolution via in-game option/menu, only with r_mode "-1" and custom values. AMD&Nvidia GPUs (Win7/Win10)
What is "r_custompixelaspect" (not "cg_fixedAspect ") variable and how to set it properly?

**Comment by MAN-AT-ARMS** [comment]
What do you mean you "can't"?

No game assets were changed, so the in-game menu only shows the resolutions that id / Activision have hard coded into the menus.

If you just want to set your resolution based on your desktop resolution, use r_mode -2

r_customaspect / r_customPixelAspect don't do anything for scaling..You don't need them. I think they might have been just left in for compatibility reasons.

**Comment by MAN-AT-ARMS** [comment]
I may add code to also show the available resolutions ( in addition to the "stock" ones ) but as of now I haven't done anything with that. I'll add that to the to-do list.

**Comment by donizettilorenzo** [comment]
"I can't" = fallback to 640x480 / windowed mode if I set a resolution.

"r_custompixelaspect" is maybe an ioquake3 variable replacing the old id tech "r_customaspect". So doesn't it have any influence on widescreen resolutions and FoV?

**Comment by MAN-AT-ARMS** [comment]
If it falls back to 640x480, then that resolution is probably not valid on your hardware.

r_customPixelAspect...
Yeah the cvar name was changed to match ioquake3 but no it doesn't and never did influence anything

cg_fov is the cvar you want to use for fov. ( if not using cg_fixedAspect )

**Comment by donizettilorenzo** [comment]
With "r_mode=-1" there's no problem at all with every resolution.

**Comment by MAN-AT-ARMS** [comment]
Some resolutions may be valid in windowed mode, but not in fullscreen mode (which is the default)
AFAIK, it's always been that way.

Maybe, I'm not understanding your question though.

**Comment by donizettilorenzo** [comment]
The problem is not the resolution (1680x1050 is working great with r_mode=1), it's the menu function that *seems* not working correctly.

**Comment by MAN-AT-ARMS** [comment]
Implemented in 7a71031
