### ISSUE TITLE
Build Errror Raspberry pi 3

### ISSUE THREAD

**Issue by cesarpuig** [iortcw/iortcw#90]
As in the raspberry pi 4 from Commit 2f4c329 build it fails in raspberry pi 3.

In the raspberry pi 4 it was solved replacing `ARCH = arm` by `ARCH = armv71`.

But this change has not fixed the problem in rpi3

I attach part of the description in case anyone can help me:

```
REF_CC code/renderer/tr_altivec.c
In file included from code/renderer/qgl.h:38:0,
                 from code/renderer/tr_local.h:37,
                 from code/renderer/tr_altivec.c:29:
/usr/include/SDL2/SDL_opengles.h:33:21: fatal error: GLES/gl.h: No existe el fichero o el directorio
 #include <GLES/gl.h>
                     ^
compilation terminated.
Makefile:2681: fallo en las instrucciones para el objetivo 'build/release-linux-arm/renderer/tr_altivec.o'
make[2]: *** [build/release-linux-arm/renderer/tr_altivec.o] Error 1
make[2]: se sale del directorio '/home/pi/RetroPie-Setup/tmp/build/iortcw-master/SP'
Makefile:1416: fallo en las instrucciones para el objetivo 'targets'
make[1]: *** [targets] Error 2
make[1]: se sale del directorio '/home/pi/RetroPie-Setup/tmp/build/iortcw-master/SP'
Makefile:1367: fallo en las instrucciones para el objetivo 'release'
make: *** [release] Error 2
```

Thank you

**Comment by MAN-AT-ARMS** [comment]
Looks like you're missing a development package

**Comment by cesarpuig** [comment]
Hi, @MAN-AT-ARMS.

It is true, in my system there is:

```
GL/gl.h
GLES2/gl2.h
GLES3/gl3.h
```

But no:

```
GLES/gl.h
```

Before installing iortcw I install these dependencies

```libsdl2-dev libsdl2-net-dev libsdl2-mixer-dev libsdl2-image-dev timidity freepats```

Can you help me? Do I have to install any previous dependencies before installing iortcw?

Thanks

**Comment by MAN-AT-ARMS** [comment]
i would try building SDL from source and installing that instead of the packaged versions

**Comment by cesarpuig** [comment]
@MAN-AT-ARMS 
This problem was solved by installing the libgles1-mesa-dev dependency.

Thank you.
