### ISSUE TITLE
Dunnos

### ISSUE THREAD

**Issue by inukaze** [iortcw/iortcw#92]
Hi there, i had download "iortcw" 141 + Patched + 151 . Put the files in the right places, and that.

1 - I can't load my older Save Game (from cracked WolfSP) Console Output : 

```
WARNING: backward compatibility, loading a version 17 saved game.
some version 17 saved games may cause crashes during play.
********************
ERROR: ReadField: function name is greater than buffer (512 chars)
********************
----- Server Shutdown (Server crashed: ReadField: function name is greater than buffer (512 chars)) -----
AAS shutdown.
forcefully unloading qagame vm
---------------------------
RE_Shutdown( 0 )
Hunk_Clear: reset the hunk ok
----- R_Init -----
Initializing Shaders
^3WARNING: In shader file scripts/common.shader...Shader "textures/sfx/portal3a_back2" on line 822 is missing closing brace^3.
^3WARNING: In shader file scripts/ui_wolf.shader...Invalid shader name "}" on line 1849.
----- finished R_Init -----
^3RE_RegisterFont: Unable to read font file 'fonts/bigfont'
^3turning EXEC_NOW 'quit' into EXEC_INSERT
----- Client Shutdown (Client quit) -----
RE_Shutdown( 1 )
Hunk_Clear: reset the hunk ok
OpenAL capture device closed.
-----------------------
```

Here the SaveGames :
[save.zip](https://github.com/iortcw/iortcw/files/4812461/save.zip)

Well i trying to load quicksave. in the follow Screenshot : 
![iortcw-151-partida_anterior](https://user-images.githubusercontent.com/1647332/85266734-4e235100-b442-11ea-8da9-9b24fb66b4e8.png)

Under Windows 7 64 Bits, directly crash when you clic the arrow on the inferior corner at bottom right of the screen for start the mission.

2 - I want to Re-Translate to Spanish the game with this engine. because i had the spanish version of game, but in some parts, the are showed are on english. 

Like the mission brief, the left part on spanish, and the right part on english : 
![iortcw-151-spanglish](https://user-images.githubusercontent.com/1647332/85267105-cc7ff300-b442-11ea-8074-78f00fdb0b5e.png)

3 - Dunno if you can add the mod https://github.com/rtcwcoop/rtcwcoop, but better adapted to support play campaing with friends, and with all events and cinematics like Single Player. to the game

Well for this mod i want to re-translate it too, because just appears on english the game msg, but the UI are on spanish. 

4 - You can add to "Safe Video Mode" when fails, for select "OpenGL1" or "rend2" because some hours ago testing on a windows machine i try to use rend2 but evers fails to start a shader, and when i click Safe Video Mode, the same error again.

**Comment by MAN-AT-ARMS** [comment]
1. 32bit save files will not work with the 64bit version.
2. There are spanish language versions of the sp_pak3.pk3 file in the release downloads
3. RTCWCoop is a mod based on this engine already.
4. I do not really understand what the question is. Try a fresh config file.

**Comment by inukaze** [comment]
>     1. 32bit save files will not work with the 64bit version.
Its the same with 32 Bits executable and with the 64 Bits executable of iortcw under windows 7

>     2. There are spanish language versions of the sp_pak3.pk3 file in the release downloads
Occurs the thing i put on the screenshot, some parts are on spanish but anothers are on english.

>     3. RTCWCoop is a mod based on this engine already.
This mod not play cinematics like in Single Player mode.

>     4. I do not really understand what the question is. Try a fresh config file.

Well on some machines if you set "rend2" like engine, can fail to start, when you try to start again.

The iortcw never ask if you want to try a "Safe Video Mode" (forcing the use of Old Engine, OpenGL) to start iorctw without problems.

**Comment by MAN-AT-ARMS** [comment]
1. If you're not saves from using an official build, then don't expect it to work.
2. I didn't create or provide the game assets, so not sure what you expect me to do with it.
3. The cut scenes break the scripting which is why they are removed. This is the engine used for coop and is a separate project.
4. It should already do that unless it is loading a config from another folder on start up.
