### ISSUE TITLE
feature request: specify custom config file folder

### ISSUE THREAD

**Issue by legluondunet** [iortcw/iortcw#96]
Hello,
on Linux per default iortcw config folder is located in /home/usr_profile/.wolf/.
Is it possible to ask iortcw to search in his executable folder for a config folder prior to use the one in the home folder?
Like this we can use custom config without use the home config.

**Comment by MAN-AT-ARMS** [comment]
This would be done by use of the fs_homepath variable.

eg.
iowolfsp.x86 +set fs_homepath "<path you want to use>"

**Comment by legluondunet** [comment]
ok thank you for your quick answer.

**Comment by legluondunet** [comment]
If I use this command:
iowolfsp.x86 +set fs_homepath .
iortcw understood correctly where it could find the config file.
But if I click on Multiplayer or single...I obtained a black screen and it crashed.
Before that it created a .wolf folder in my home folder with:
.wolf/main/iowolfsp.pid or iowolfmp.pid
Could you try to reproduce this crash?
I compiled last git version from today on Ubuntu 20.04 64 bits.

**Comment by legluondunet** [comment]
It seems that if you start iorctw with "+set fs_homepath ." option, this option is not transmited between single and/or multiplayer mode.

**Comment by legluondunet** [comment]
When I click on Multiplayer button and iortcw crashed, I have not a lot of useful information in terminal:
```

Sound initialization successful.
--------------------------------
Try loading dll file ./main/ui.mp.x86_64.so
Loading DLL file: ./main/ui.mp.x86_64.so
Sys_LoadGameDll(./main/ui.mp.x86_64.so) found vmMain function at 0x7f01631c2860
tty]
```

**Comment by MAN-AT-ARMS** [comment]
SP and MP are separate binaries and have separate configs. You would need to set them up individually.

**Comment by legluondunet** [comment]
That is what I did, but it is not enough, something does not work as expected here.

**Comment by MAN-AT-ARMS** [comment]
The fs_homepath variable is not shared. You may be able to add it to an autoexec.cfg file in the main folder to be executed on game startup

**Comment by legluondunet** [comment]
ok, I will try this solution.

**Comment by MAN-AT-ARMS** [comment]
OK. Not sure as it wasn't tested. Not sure the link between games was designed for a setup like that.

**Comment by MAN-AT-ARMS** [comment]
Curious if you tested this and it worked...

**Comment by legluondunet** [comment]
This is my results tests:
- if I put config files in game "main" folder, at first launch iortcw copy them to /home/.wolf/main folder.
After that the game still using config in my home folder.
- If I put "set fs_homepath ." in autoexec.bat, it does nothing...at first launch iortcw create a /home/.wolf/main folder and record config files here.
So for the moment I have no solution to bypass iortcw home config and use instead config files in another folder .

**Comment by MAN-AT-ARMS** [comment]
It should be autoexec.cfg and belongs in the main folder along side your pk3 files

**Comment by legluondunet** [comment]
> It should be autoexec.cfg and belongs in the main folder along side your pk3 files

Does it work for you on Linux without create or use config in home?

**Comment by MAN-AT-ARMS** [comment]
No. I would suggest creating a start script to launch the binary with the fs_homepath argument

**Comment by legluondunet** [comment]
New interesting results:
If I launch iortcw from command line like this:

`$ ./iowolfsp.x86_64 +set fs_homepath /home/legluondunet/Games/return-to-castle-wolfenstein/conf/`

 iortcw will use /home/legluondunet/Games/return-to-castle-wolfenstein/conf/ as config folder, without create a .wolf folder in my home.

Now if I launch the binary without option and my autoexec.cfg:
```

set fs_homepath /home/legluondunet/Games/return-to-castle-wolfenstein/conf/
exec x360
set devdll 1
```


```
$ ./iowolfsp.x86_64
iortcw 1.51d-SP_GIT_ed3a70d8-2020-09-13 linux-x86_64 Sep 19 2020
SSE instruction set enabled
----- FS_Startup -----
Current search path:
/home/legluondunet/.wolf/main
./main/sp_pak4.pk3 (21 files)
./main/sp_pak3.pk3 (14 files)
./main/sp_pak2.pk3 (232 files)
./main/sp_pak1.pk3 (1342 files)
./main/pak0.pk3 (4775 files)
./main
    
----------------------
6384 files in pk3 files
execing default.cfg
execing wolfconfig.cfg
execing autoexec.cfg
fs_homepath is write protected.
execing x360.cfg
Unknown command "in_restart^7"
Unknown command "in_joystickuseanalog^7"
Hunk_Clear: reset the hunk ok
Bypassing CD checks
```
It doesn't work, iortcw said "fs_homepath is write protected." and use home folder.

**Comment by MAN-AT-ARMS** [comment]
Forget the autoexec.cfg suggestion, it doesn't work because of startup order etc.

Use a start script instead.

**Comment by legluondunet** [comment]
> Use a start script instead.

yes but if I start one binary with options and I change single player to multiplayer, the options will not be transmitted to iortcw multiplayer binary...which will use home folder again. There is an issue here, the feature exists but it is not completely usable.

**Comment by MAN-AT-ARMS** [comment]
Example:
Rename the binary to something like iowolfmp.x86_64.bin
Create a start up script with name of original binary (iowolfmp.x86_64) and make it executable.
Inside the script start launch the game binary (with the new name) and add the homepath.
eg.
./iowolfmp.x86_64.bin +set fs_homepath <path>

Do this for both games.
