### ISSUE TITLE
Alt-Tab not available on Linux?

### ISSUE THREAD

**Issue by legluondunet** [iortcw/iortcw#97]
Hello,
it is not possible to use alt-tab on Linux once iortcw launched? Even in window mode?

**Comment by MAN-AT-ARMS** [comment]
This sounds more like a windows focus behavior of whatever DE you are using.
Generally, you can release focus of the game window by bringing down the console in game (before trying to switch between windows.)

**Comment by legluondunet** [comment]
> Generally, you can release focus of the game window by bringing down the console in game (before trying to switch between windows.)
Could you tell me what is the key to open console?
I tried "²" and "Tab" with an azerty keyboard without success and the key does not appear in the "command" menu ui.

**Comment by legluondunet** [comment]
ok works if I press "²" and "MAJ" with iortcw in window mode.
Does not work in fullscreen.

**Comment by MAN-AT-ARMS** [comment]
Note: Shift + Esc should work to bring down console on any keyboard layout
