### ISSUE TITLE
shaders error message

### ISSUE THREAD

**Issue by legluondunet** [iortcw/iortcw#98]
Once again I need your help, in terminal I saw this error message:

```
------- FBO_Init -------
------- GLSL_InitGPUShaders -------
loaded 276 GLSL shaders (192 gen 42 light 42 etc) in  0.15 seconds
------- R_InitVaos -------
Initializing Shaders
^3WARNING: In shader file scripts/common.shader...Shader "textures/sfx/portal3a_back2" on line 822 is missing closing brace^3.
^3WARNING: In shader file scripts/ui_wolf.shader...Invalid shader name "}" on line 1849.

```

Did I forgot something?

**Comment by MAN-AT-ARMS** [comment]
Are you using official pk3 files from a CD?

**Comment by legluondunet** [comment]
I'm using the GOG version

**Comment by MAN-AT-ARMS** [comment]
add +set logfile 2 to your commandline and paste the contents of the rtcwconsole.log file here.

**Comment by legluondunet** [comment]
`
[rtcwconsole.log](https://github.com/iortcw/iortcw/files/5250002/rtcwconsole.log)
`

**Comment by MAN-AT-ARMS** [comment]
Those 2 shader warnings are normal. I believe it's due to a typo within the official pk3 files and not iortcw related.
If your question is just about the warnings, you can ignore them.

**Comment by legluondunet** [comment]
So I will ignore them.
Thank you for your help.
