### ISSUE TITLE
iortcw linux port does not work correctly with Lutris, please help

### ISSUE THREAD

**Issue by legluondunet** [iortcw/iortcw#99]
Hello,
could you join us to resolve this issue:
https://github.com/lutris/lutris/issues/3151
I don't know if it is a Lutris or a iortcw issue, but it's very annoying as for the moment iortcw Linux port does not work correctly on Lutris.

**Comment by legluondunet** [comment]
finally find a way to launch it correctly with Lutris:
created a bash script which launch binary with "&"

**Comment by MAN-AT-ARMS** [comment]
Yes Iwas going to suggest that. Same for setting the homepath.
